// @generated by protoc-gen-es v1.10.1 with parameter "target=ts"
// @generated from file chatto/discovery/v1/compatibility.proto (package chatto.discovery.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";

/**
 * Machine-readable compatibility metadata for clients connecting to this
 * server.
 *
 * Capability keys describe protocol contracts rather than server
 * configuration or the authenticated viewer's permissions. Clients should
 * ignore unknown keys.
 *
 * @generated from message chatto.discovery.v1.ServerCompatibility
 */
export class ServerCompatibility extends Message<ServerCompatibility> {
  /**
   * Stable protocol capability keys supported by this server. Current keys:
   * `chatto.discovery.v1`, `chatto.auth.v1`, `chatto.api.v1`,
   * `chatto.admin.v1`, `chatto.api.message-search.v1`,
   * `chatto.api.room-manager-member-reads.v1`, `chatto.realtime.v1`,
   * `chatto.realtime.projection.v1`, and `chatto.role-colors.v1`.
   *
   * @generated from field: repeated string protocol_capabilities = 1;
   */
  protocolCapabilities: string[] = [];

  constructor(data?: PartialMessage<ServerCompatibility>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "chatto.discovery.v1.ServerCompatibility";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "protocol_capabilities", kind: "scalar", T: 9 /* ScalarType.STRING */, repeated: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ServerCompatibility {
    return new ServerCompatibility().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ServerCompatibility {
    return new ServerCompatibility().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ServerCompatibility {
    return new ServerCompatibility().fromJsonString(jsonString, options);
  }

  static equals(a: ServerCompatibility | PlainMessage<ServerCompatibility> | undefined, b: ServerCompatibility | PlainMessage<ServerCompatibility> | undefined): boolean {
    return proto3.util.equals(ServerCompatibility, a, b);
  }
}
