// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: chatto/admin/v1/invitations.proto

package adminv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "hmans.de/chatto/internal/pb/chatto/admin/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// AdminInviteLinkServiceName is the fully-qualified name of the AdminInviteLinkService service.
	AdminInviteLinkServiceName = "chatto.admin.v1.AdminInviteLinkService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// AdminInviteLinkServiceListInviteLinksProcedure is the fully-qualified name of the
	// AdminInviteLinkService's ListInviteLinks RPC.
	AdminInviteLinkServiceListInviteLinksProcedure = "/chatto.admin.v1.AdminInviteLinkService/ListInviteLinks"
	// AdminInviteLinkServiceGetInviteLinkProcedure is the fully-qualified name of the
	// AdminInviteLinkService's GetInviteLink RPC.
	AdminInviteLinkServiceGetInviteLinkProcedure = "/chatto.admin.v1.AdminInviteLinkService/GetInviteLink"
	// AdminInviteLinkServiceCreateInviteLinkProcedure is the fully-qualified name of the
	// AdminInviteLinkService's CreateInviteLink RPC.
	AdminInviteLinkServiceCreateInviteLinkProcedure = "/chatto.admin.v1.AdminInviteLinkService/CreateInviteLink"
	// AdminInviteLinkServiceRevokeInviteLinkProcedure is the fully-qualified name of the
	// AdminInviteLinkService's RevokeInviteLink RPC.
	AdminInviteLinkServiceRevokeInviteLinkProcedure = "/chatto.admin.v1.AdminInviteLinkService/RevokeInviteLink"
)

// AdminInviteLinkServiceClient is a client for the chatto.admin.v1.AdminInviteLinkService service.
type AdminInviteLinkServiceClient interface {
	// Lists invite links. Requires user.invite.
	ListInviteLinks(context.Context, *connect.Request[v1.ListInviteLinksRequest]) (*connect.Response[v1.ListInviteLinksResponse], error)
	// Gets one invite link. Returns NOT_FOUND when it does not exist. Requires user.invite.
	GetInviteLink(context.Context, *connect.Request[v1.GetInviteLinkRequest]) (*connect.Response[v1.GetInviteLinkResponse], error)
	// Creates an invite link. Requires user.invite.
	CreateInviteLink(context.Context, *connect.Request[v1.CreateInviteLinkRequest]) (*connect.Response[v1.CreateInviteLinkResponse], error)
	// Permanently revokes an invite link while retaining its audit history. Requires user.invite.
	RevokeInviteLink(context.Context, *connect.Request[v1.RevokeInviteLinkRequest]) (*connect.Response[v1.RevokeInviteLinkResponse], error)
}

// NewAdminInviteLinkServiceClient constructs a client for the
// chatto.admin.v1.AdminInviteLinkService service. By default, it uses the Connect protocol with the
// binary Protobuf Codec, asks for gzipped responses, and sends uncompressed requests. To use the
// gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewAdminInviteLinkServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) AdminInviteLinkServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	adminInviteLinkServiceMethods := v1.File_chatto_admin_v1_invitations_proto.Services().ByName("AdminInviteLinkService").Methods()
	return &adminInviteLinkServiceClient{
		listInviteLinks: connect.NewClient[v1.ListInviteLinksRequest, v1.ListInviteLinksResponse](
			httpClient,
			baseURL+AdminInviteLinkServiceListInviteLinksProcedure,
			connect.WithSchema(adminInviteLinkServiceMethods.ByName("ListInviteLinks")),
			connect.WithClientOptions(opts...),
		),
		getInviteLink: connect.NewClient[v1.GetInviteLinkRequest, v1.GetInviteLinkResponse](
			httpClient,
			baseURL+AdminInviteLinkServiceGetInviteLinkProcedure,
			connect.WithSchema(adminInviteLinkServiceMethods.ByName("GetInviteLink")),
			connect.WithClientOptions(opts...),
		),
		createInviteLink: connect.NewClient[v1.CreateInviteLinkRequest, v1.CreateInviteLinkResponse](
			httpClient,
			baseURL+AdminInviteLinkServiceCreateInviteLinkProcedure,
			connect.WithSchema(adminInviteLinkServiceMethods.ByName("CreateInviteLink")),
			connect.WithClientOptions(opts...),
		),
		revokeInviteLink: connect.NewClient[v1.RevokeInviteLinkRequest, v1.RevokeInviteLinkResponse](
			httpClient,
			baseURL+AdminInviteLinkServiceRevokeInviteLinkProcedure,
			connect.WithSchema(adminInviteLinkServiceMethods.ByName("RevokeInviteLink")),
			connect.WithClientOptions(opts...),
		),
	}
}

// adminInviteLinkServiceClient implements AdminInviteLinkServiceClient.
type adminInviteLinkServiceClient struct {
	listInviteLinks  *connect.Client[v1.ListInviteLinksRequest, v1.ListInviteLinksResponse]
	getInviteLink    *connect.Client[v1.GetInviteLinkRequest, v1.GetInviteLinkResponse]
	createInviteLink *connect.Client[v1.CreateInviteLinkRequest, v1.CreateInviteLinkResponse]
	revokeInviteLink *connect.Client[v1.RevokeInviteLinkRequest, v1.RevokeInviteLinkResponse]
}

// ListInviteLinks calls chatto.admin.v1.AdminInviteLinkService.ListInviteLinks.
func (c *adminInviteLinkServiceClient) ListInviteLinks(ctx context.Context, req *connect.Request[v1.ListInviteLinksRequest]) (*connect.Response[v1.ListInviteLinksResponse], error) {
	return c.listInviteLinks.CallUnary(ctx, req)
}

// GetInviteLink calls chatto.admin.v1.AdminInviteLinkService.GetInviteLink.
func (c *adminInviteLinkServiceClient) GetInviteLink(ctx context.Context, req *connect.Request[v1.GetInviteLinkRequest]) (*connect.Response[v1.GetInviteLinkResponse], error) {
	return c.getInviteLink.CallUnary(ctx, req)
}

// CreateInviteLink calls chatto.admin.v1.AdminInviteLinkService.CreateInviteLink.
func (c *adminInviteLinkServiceClient) CreateInviteLink(ctx context.Context, req *connect.Request[v1.CreateInviteLinkRequest]) (*connect.Response[v1.CreateInviteLinkResponse], error) {
	return c.createInviteLink.CallUnary(ctx, req)
}

// RevokeInviteLink calls chatto.admin.v1.AdminInviteLinkService.RevokeInviteLink.
func (c *adminInviteLinkServiceClient) RevokeInviteLink(ctx context.Context, req *connect.Request[v1.RevokeInviteLinkRequest]) (*connect.Response[v1.RevokeInviteLinkResponse], error) {
	return c.revokeInviteLink.CallUnary(ctx, req)
}

// AdminInviteLinkServiceHandler is an implementation of the chatto.admin.v1.AdminInviteLinkService
// service.
type AdminInviteLinkServiceHandler interface {
	// Lists invite links. Requires user.invite.
	ListInviteLinks(context.Context, *connect.Request[v1.ListInviteLinksRequest]) (*connect.Response[v1.ListInviteLinksResponse], error)
	// Gets one invite link. Returns NOT_FOUND when it does not exist. Requires user.invite.
	GetInviteLink(context.Context, *connect.Request[v1.GetInviteLinkRequest]) (*connect.Response[v1.GetInviteLinkResponse], error)
	// Creates an invite link. Requires user.invite.
	CreateInviteLink(context.Context, *connect.Request[v1.CreateInviteLinkRequest]) (*connect.Response[v1.CreateInviteLinkResponse], error)
	// Permanently revokes an invite link while retaining its audit history. Requires user.invite.
	RevokeInviteLink(context.Context, *connect.Request[v1.RevokeInviteLinkRequest]) (*connect.Response[v1.RevokeInviteLinkResponse], error)
}

// NewAdminInviteLinkServiceHandler builds an HTTP handler from the service implementation. It
// returns the path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewAdminInviteLinkServiceHandler(svc AdminInviteLinkServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	adminInviteLinkServiceMethods := v1.File_chatto_admin_v1_invitations_proto.Services().ByName("AdminInviteLinkService").Methods()
	adminInviteLinkServiceListInviteLinksHandler := connect.NewUnaryHandler(
		AdminInviteLinkServiceListInviteLinksProcedure,
		svc.ListInviteLinks,
		connect.WithSchema(adminInviteLinkServiceMethods.ByName("ListInviteLinks")),
		connect.WithHandlerOptions(opts...),
	)
	adminInviteLinkServiceGetInviteLinkHandler := connect.NewUnaryHandler(
		AdminInviteLinkServiceGetInviteLinkProcedure,
		svc.GetInviteLink,
		connect.WithSchema(adminInviteLinkServiceMethods.ByName("GetInviteLink")),
		connect.WithHandlerOptions(opts...),
	)
	adminInviteLinkServiceCreateInviteLinkHandler := connect.NewUnaryHandler(
		AdminInviteLinkServiceCreateInviteLinkProcedure,
		svc.CreateInviteLink,
		connect.WithSchema(adminInviteLinkServiceMethods.ByName("CreateInviteLink")),
		connect.WithHandlerOptions(opts...),
	)
	adminInviteLinkServiceRevokeInviteLinkHandler := connect.NewUnaryHandler(
		AdminInviteLinkServiceRevokeInviteLinkProcedure,
		svc.RevokeInviteLink,
		connect.WithSchema(adminInviteLinkServiceMethods.ByName("RevokeInviteLink")),
		connect.WithHandlerOptions(opts...),
	)
	return "/chatto.admin.v1.AdminInviteLinkService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case AdminInviteLinkServiceListInviteLinksProcedure:
			adminInviteLinkServiceListInviteLinksHandler.ServeHTTP(w, r)
		case AdminInviteLinkServiceGetInviteLinkProcedure:
			adminInviteLinkServiceGetInviteLinkHandler.ServeHTTP(w, r)
		case AdminInviteLinkServiceCreateInviteLinkProcedure:
			adminInviteLinkServiceCreateInviteLinkHandler.ServeHTTP(w, r)
		case AdminInviteLinkServiceRevokeInviteLinkProcedure:
			adminInviteLinkServiceRevokeInviteLinkHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedAdminInviteLinkServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedAdminInviteLinkServiceHandler struct{}

func (UnimplementedAdminInviteLinkServiceHandler) ListInviteLinks(context.Context, *connect.Request[v1.ListInviteLinksRequest]) (*connect.Response[v1.ListInviteLinksResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("chatto.admin.v1.AdminInviteLinkService.ListInviteLinks is not implemented"))
}

func (UnimplementedAdminInviteLinkServiceHandler) GetInviteLink(context.Context, *connect.Request[v1.GetInviteLinkRequest]) (*connect.Response[v1.GetInviteLinkResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("chatto.admin.v1.AdminInviteLinkService.GetInviteLink is not implemented"))
}

func (UnimplementedAdminInviteLinkServiceHandler) CreateInviteLink(context.Context, *connect.Request[v1.CreateInviteLinkRequest]) (*connect.Response[v1.CreateInviteLinkResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("chatto.admin.v1.AdminInviteLinkService.CreateInviteLink is not implemented"))
}

func (UnimplementedAdminInviteLinkServiceHandler) RevokeInviteLink(context.Context, *connect.Request[v1.RevokeInviteLinkRequest]) (*connect.Response[v1.RevokeInviteLinkResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("chatto.admin.v1.AdminInviteLinkService.RevokeInviteLink is not implemented"))
}
