// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: chatto/admin/v1/webhooks.proto

package adminv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "hmans.de/chatto/internal/pb/chatto/admin/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// AdminWebhookServiceName is the fully-qualified name of the AdminWebhookService service.
	AdminWebhookServiceName = "chatto.admin.v1.AdminWebhookService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// AdminWebhookServiceCreateWebhookProcedure is the fully-qualified name of the
	// AdminWebhookService's CreateWebhook RPC.
	AdminWebhookServiceCreateWebhookProcedure = "/chatto.admin.v1.AdminWebhookService/CreateWebhook"
	// AdminWebhookServiceUpdateWebhookProcedure is the fully-qualified name of the
	// AdminWebhookService's UpdateWebhook RPC.
	AdminWebhookServiceUpdateWebhookProcedure = "/chatto.admin.v1.AdminWebhookService/UpdateWebhook"
	// AdminWebhookServiceDeleteWebhookProcedure is the fully-qualified name of the
	// AdminWebhookService's DeleteWebhook RPC.
	AdminWebhookServiceDeleteWebhookProcedure = "/chatto.admin.v1.AdminWebhookService/DeleteWebhook"
	// AdminWebhookServiceListWebhooksProcedure is the fully-qualified name of the AdminWebhookService's
	// ListWebhooks RPC.
	AdminWebhookServiceListWebhooksProcedure = "/chatto.admin.v1.AdminWebhookService/ListWebhooks"
	// AdminWebhookServiceRegenerateWebhookTokenProcedure is the fully-qualified name of the
	// AdminWebhookService's RegenerateWebhookToken RPC.
	AdminWebhookServiceRegenerateWebhookTokenProcedure = "/chatto.admin.v1.AdminWebhookService/RegenerateWebhookToken"
)

// AdminWebhookServiceClient is a client for the chatto.admin.v1.AdminWebhookService service.
type AdminWebhookServiceClient interface {
	// Creates a webhook against a room and returns its one-time secret URL.
	// Requires `server.manage`.
	CreateWebhook(context.Context, *connect.Request[v1.CreateWebhookRequest]) (*connect.Response[v1.CreateWebhookResponse], error)
	// Updates a webhook's name, avatar, or disabled state. Requires
	// `server.manage`.
	UpdateWebhook(context.Context, *connect.Request[v1.UpdateWebhookRequest]) (*connect.Response[v1.UpdateWebhookResponse], error)
	// Deletes a webhook and disables its backing identity. Requires
	// `server.manage`.
	DeleteWebhook(context.Context, *connect.Request[v1.DeleteWebhookRequest]) (*connect.Response[v1.DeleteWebhookResponse], error)
	// Lists webhooks, optionally filtered to one room. Requires `server.manage`.
	ListWebhooks(context.Context, *connect.Request[v1.ListWebhooksRequest]) (*connect.Response[v1.ListWebhooksResponse], error)
	// Regenerates a webhook's secret token, invalidating the previous URL.
	// Requires `server.manage`.
	RegenerateWebhookToken(context.Context, *connect.Request[v1.RegenerateWebhookTokenRequest]) (*connect.Response[v1.RegenerateWebhookTokenResponse], error)
}

// NewAdminWebhookServiceClient constructs a client for the chatto.admin.v1.AdminWebhookService
// service. By default, it uses the Connect protocol with the binary Protobuf Codec, asks for
// gzipped responses, and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply
// the connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewAdminWebhookServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) AdminWebhookServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	adminWebhookServiceMethods := v1.File_chatto_admin_v1_webhooks_proto.Services().ByName("AdminWebhookService").Methods()
	return &adminWebhookServiceClient{
		createWebhook: connect.NewClient[v1.CreateWebhookRequest, v1.CreateWebhookResponse](
			httpClient,
			baseURL+AdminWebhookServiceCreateWebhookProcedure,
			connect.WithSchema(adminWebhookServiceMethods.ByName("CreateWebhook")),
			connect.WithClientOptions(opts...),
		),
		updateWebhook: connect.NewClient[v1.UpdateWebhookRequest, v1.UpdateWebhookResponse](
			httpClient,
			baseURL+AdminWebhookServiceUpdateWebhookProcedure,
			connect.WithSchema(adminWebhookServiceMethods.ByName("UpdateWebhook")),
			connect.WithClientOptions(opts...),
		),
		deleteWebhook: connect.NewClient[v1.DeleteWebhookRequest, v1.DeleteWebhookResponse](
			httpClient,
			baseURL+AdminWebhookServiceDeleteWebhookProcedure,
			connect.WithSchema(adminWebhookServiceMethods.ByName("DeleteWebhook")),
			connect.WithClientOptions(opts...),
		),
		listWebhooks: connect.NewClient[v1.ListWebhooksRequest, v1.ListWebhooksResponse](
			httpClient,
			baseURL+AdminWebhookServiceListWebhooksProcedure,
			connect.WithSchema(adminWebhookServiceMethods.ByName("ListWebhooks")),
			connect.WithClientOptions(opts...),
		),
		regenerateWebhookToken: connect.NewClient[v1.RegenerateWebhookTokenRequest, v1.RegenerateWebhookTokenResponse](
			httpClient,
			baseURL+AdminWebhookServiceRegenerateWebhookTokenProcedure,
			connect.WithSchema(adminWebhookServiceMethods.ByName("RegenerateWebhookToken")),
			connect.WithClientOptions(opts...),
		),
	}
}

// adminWebhookServiceClient implements AdminWebhookServiceClient.
type adminWebhookServiceClient struct {
	createWebhook          *connect.Client[v1.CreateWebhookRequest, v1.CreateWebhookResponse]
	updateWebhook          *connect.Client[v1.UpdateWebhookRequest, v1.UpdateWebhookResponse]
	deleteWebhook          *connect.Client[v1.DeleteWebhookRequest, v1.DeleteWebhookResponse]
	listWebhooks           *connect.Client[v1.ListWebhooksRequest, v1.ListWebhooksResponse]
	regenerateWebhookToken *connect.Client[v1.RegenerateWebhookTokenRequest, v1.RegenerateWebhookTokenResponse]
}

// CreateWebhook calls chatto.admin.v1.AdminWebhookService.CreateWebhook.
func (c *adminWebhookServiceClient) CreateWebhook(ctx context.Context, req *connect.Request[v1.CreateWebhookRequest]) (*connect.Response[v1.CreateWebhookResponse], error) {
	return c.createWebhook.CallUnary(ctx, req)
}

// UpdateWebhook calls chatto.admin.v1.AdminWebhookService.UpdateWebhook.
func (c *adminWebhookServiceClient) UpdateWebhook(ctx context.Context, req *connect.Request[v1.UpdateWebhookRequest]) (*connect.Response[v1.UpdateWebhookResponse], error) {
	return c.updateWebhook.CallUnary(ctx, req)
}

// DeleteWebhook calls chatto.admin.v1.AdminWebhookService.DeleteWebhook.
func (c *adminWebhookServiceClient) DeleteWebhook(ctx context.Context, req *connect.Request[v1.DeleteWebhookRequest]) (*connect.Response[v1.DeleteWebhookResponse], error) {
	return c.deleteWebhook.CallUnary(ctx, req)
}

// ListWebhooks calls chatto.admin.v1.AdminWebhookService.ListWebhooks.
func (c *adminWebhookServiceClient) ListWebhooks(ctx context.Context, req *connect.Request[v1.ListWebhooksRequest]) (*connect.Response[v1.ListWebhooksResponse], error) {
	return c.listWebhooks.CallUnary(ctx, req)
}

// RegenerateWebhookToken calls chatto.admin.v1.AdminWebhookService.RegenerateWebhookToken.
func (c *adminWebhookServiceClient) RegenerateWebhookToken(ctx context.Context, req *connect.Request[v1.RegenerateWebhookTokenRequest]) (*connect.Response[v1.RegenerateWebhookTokenResponse], error) {
	return c.regenerateWebhookToken.CallUnary(ctx, req)
}

// AdminWebhookServiceHandler is an implementation of the chatto.admin.v1.AdminWebhookService
// service.
type AdminWebhookServiceHandler interface {
	// Creates a webhook against a room and returns its one-time secret URL.
	// Requires `server.manage`.
	CreateWebhook(context.Context, *connect.Request[v1.CreateWebhookRequest]) (*connect.Response[v1.CreateWebhookResponse], error)
	// Updates a webhook's name, avatar, or disabled state. Requires
	// `server.manage`.
	UpdateWebhook(context.Context, *connect.Request[v1.UpdateWebhookRequest]) (*connect.Response[v1.UpdateWebhookResponse], error)
	// Deletes a webhook and disables its backing identity. Requires
	// `server.manage`.
	DeleteWebhook(context.Context, *connect.Request[v1.DeleteWebhookRequest]) (*connect.Response[v1.DeleteWebhookResponse], error)
	// Lists webhooks, optionally filtered to one room. Requires `server.manage`.
	ListWebhooks(context.Context, *connect.Request[v1.ListWebhooksRequest]) (*connect.Response[v1.ListWebhooksResponse], error)
	// Regenerates a webhook's secret token, invalidating the previous URL.
	// Requires `server.manage`.
	RegenerateWebhookToken(context.Context, *connect.Request[v1.RegenerateWebhookTokenRequest]) (*connect.Response[v1.RegenerateWebhookTokenResponse], error)
}

// NewAdminWebhookServiceHandler builds an HTTP handler from the service implementation. It returns
// the path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewAdminWebhookServiceHandler(svc AdminWebhookServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	adminWebhookServiceMethods := v1.File_chatto_admin_v1_webhooks_proto.Services().ByName("AdminWebhookService").Methods()
	adminWebhookServiceCreateWebhookHandler := connect.NewUnaryHandler(
		AdminWebhookServiceCreateWebhookProcedure,
		svc.CreateWebhook,
		connect.WithSchema(adminWebhookServiceMethods.ByName("CreateWebhook")),
		connect.WithHandlerOptions(opts...),
	)
	adminWebhookServiceUpdateWebhookHandler := connect.NewUnaryHandler(
		AdminWebhookServiceUpdateWebhookProcedure,
		svc.UpdateWebhook,
		connect.WithSchema(adminWebhookServiceMethods.ByName("UpdateWebhook")),
		connect.WithHandlerOptions(opts...),
	)
	adminWebhookServiceDeleteWebhookHandler := connect.NewUnaryHandler(
		AdminWebhookServiceDeleteWebhookProcedure,
		svc.DeleteWebhook,
		connect.WithSchema(adminWebhookServiceMethods.ByName("DeleteWebhook")),
		connect.WithHandlerOptions(opts...),
	)
	adminWebhookServiceListWebhooksHandler := connect.NewUnaryHandler(
		AdminWebhookServiceListWebhooksProcedure,
		svc.ListWebhooks,
		connect.WithSchema(adminWebhookServiceMethods.ByName("ListWebhooks")),
		connect.WithHandlerOptions(opts...),
	)
	adminWebhookServiceRegenerateWebhookTokenHandler := connect.NewUnaryHandler(
		AdminWebhookServiceRegenerateWebhookTokenProcedure,
		svc.RegenerateWebhookToken,
		connect.WithSchema(adminWebhookServiceMethods.ByName("RegenerateWebhookToken")),
		connect.WithHandlerOptions(opts...),
	)
	return "/chatto.admin.v1.AdminWebhookService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case AdminWebhookServiceCreateWebhookProcedure:
			adminWebhookServiceCreateWebhookHandler.ServeHTTP(w, r)
		case AdminWebhookServiceUpdateWebhookProcedure:
			adminWebhookServiceUpdateWebhookHandler.ServeHTTP(w, r)
		case AdminWebhookServiceDeleteWebhookProcedure:
			adminWebhookServiceDeleteWebhookHandler.ServeHTTP(w, r)
		case AdminWebhookServiceListWebhooksProcedure:
			adminWebhookServiceListWebhooksHandler.ServeHTTP(w, r)
		case AdminWebhookServiceRegenerateWebhookTokenProcedure:
			adminWebhookServiceRegenerateWebhookTokenHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedAdminWebhookServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedAdminWebhookServiceHandler struct{}

func (UnimplementedAdminWebhookServiceHandler) CreateWebhook(context.Context, *connect.Request[v1.CreateWebhookRequest]) (*connect.Response[v1.CreateWebhookResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("chatto.admin.v1.AdminWebhookService.CreateWebhook is not implemented"))
}

func (UnimplementedAdminWebhookServiceHandler) UpdateWebhook(context.Context, *connect.Request[v1.UpdateWebhookRequest]) (*connect.Response[v1.UpdateWebhookResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("chatto.admin.v1.AdminWebhookService.UpdateWebhook is not implemented"))
}

func (UnimplementedAdminWebhookServiceHandler) DeleteWebhook(context.Context, *connect.Request[v1.DeleteWebhookRequest]) (*connect.Response[v1.DeleteWebhookResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("chatto.admin.v1.AdminWebhookService.DeleteWebhook is not implemented"))
}

func (UnimplementedAdminWebhookServiceHandler) ListWebhooks(context.Context, *connect.Request[v1.ListWebhooksRequest]) (*connect.Response[v1.ListWebhooksResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("chatto.admin.v1.AdminWebhookService.ListWebhooks is not implemented"))
}

func (UnimplementedAdminWebhookServiceHandler) RegenerateWebhookToken(context.Context, *connect.Request[v1.RegenerateWebhookTokenRequest]) (*connect.Response[v1.RegenerateWebhookTokenResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("chatto.admin.v1.AdminWebhookService.RegenerateWebhookToken is not implemented"))
}
