// @generated by protoc-gen-connect-es v1.7.0 with parameter "target=ts"
// @generated from file chatto/api/v1/messages.proto (package chatto.api.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { FetchLinkPreviewRequest, FetchLinkPreviewResponse } from "./link_previews_pb.js";
import { MethodKind } from "@bufbuild/protobuf";
import { BatchGetMessagesRequest, BatchGetMessagesResponse, CreateMessageRequest, CreateMessageResponse, DeleteAttachmentRequest, DeleteAttachmentResponse, DeleteLinkPreviewRequest, DeleteLinkPreviewResponse, DeleteMessageRequest, DeleteMessageResponse, GetMessageRequest, GetMessageResponse, UpdateMessageRequest, UpdateMessageResponse } from "./messages_pb.js";
import { AddReactionRequest, AddReactionResponse, RemoveReactionRequest, RemoveReactionResponse } from "./reactions_pb.js";

/**
 * Creates messages in room and thread timelines.
 *
 * @generated from service chatto.api.v1.MessageService
 */
export const MessageService = {
  typeName: "chatto.api.v1.MessageService",
  methods: {
    /**
     * Fetches and caches metadata for a composer URL. Authentication is required
     * to avoid exposing the preview fetcher as an unauthenticated network proxy.
     * Successful responses include a short-lived token accepted by CreateMessage.
     *
     * @generated from rpc chatto.api.v1.MessageService.FetchLinkPreview
     */
    fetchLinkPreview: {
      name: "FetchLinkPreview",
      I: FetchLinkPreviewRequest,
      O: FetchLinkPreviewResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Creates a message for the current user. The user must be a room member and
     * must have message.post for room messages or message.post-in-thread for
     * thread replies. Echoing a thread reply also requires message.echo and
     * message.post.
     *
     * @generated from rpc chatto.api.v1.MessageService.CreateMessage
     */
    createMessage: {
      name: "CreateMessage",
      I: CreateMessageRequest,
      O: CreateMessageResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Edits a message body. Authors can edit their own messages at any time, with
     * no time limit. Non-authors need message.manage and cannot change channel
     * echo state.
     *
     * @generated from rpc chatto.api.v1.MessageService.UpdateMessage
     */
    updateMessage: {
      name: "UpdateMessage",
      I: UpdateMessageRequest,
      O: UpdateMessageResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Retracts a message. Authors can delete their own messages. Non-authors need
     * message.manage.
     *
     * @generated from rpc chatto.api.v1.MessageService.DeleteMessage
     */
    deleteMessage: {
      name: "DeleteMessage",
      I: DeleteMessageRequest,
      O: DeleteMessageResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Removes one attachment from the author's own message.
     *
     * @generated from rpc chatto.api.v1.MessageService.DeleteAttachment
     */
    deleteAttachment: {
      name: "DeleteAttachment",
      I: DeleteAttachmentRequest,
      O: DeleteAttachmentResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Removes the accepted link preview from the author's own message.
     *
     * @generated from rpc chatto.api.v1.MessageService.DeleteLinkPreview
     */
    deleteLinkPreview: {
      name: "DeleteLinkPreview",
      I: DeleteLinkPreviewRequest,
      O: DeleteLinkPreviewResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Reads one renderable message, including current body, attachment metadata,
     * link preview, reactions, thread metadata, and pin state. Authentication and room
     * membership are required. Returns NOT_FOUND when the event does not exist,
     * is not a message, has been retracted, or belongs to a different room.
     *
     * @generated from rpc chatto.api.v1.MessageService.GetMessage
     */
    getMessage: {
      name: "GetMessage",
      I: GetMessageRequest,
      O: GetMessageResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Reads many renderable messages and their current pin state in one room. Authentication and room
     * membership are required. Missing, retracted, non-message, and wrong-room
     * event IDs are omitted. Results preserve first-seen request order and
     * repeated event IDs are de-duplicated.
     *
     * @generated from rpc chatto.api.v1.MessageService.BatchGetMessages
     */
    batchGetMessages: {
      name: "BatchGetMessages",
      I: BatchGetMessagesRequest,
      O: BatchGetMessagesResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Adds a reaction to a message. The user must be a room member and have
     * message.react in the target room.
     *
     * @generated from rpc chatto.api.v1.MessageService.AddReaction
     */
    addReaction: {
      name: "AddReaction",
      I: AddReactionRequest,
      O: AddReactionResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Removes a reaction from a message. The user must be a room member and have
     * message.react in the target room.
     *
     * @generated from rpc chatto.api.v1.MessageService.RemoveReaction
     */
    removeReaction: {
      name: "RemoveReaction",
      I: RemoveReactionRequest,
      O: RemoveReactionResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;
