// @generated by protoc-gen-connect-es v1.7.0 with parameter "target=ts"
// @generated from file chatto/admin/v1/webhooks.proto (package chatto.admin.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { CreateWebhookRequest, CreateWebhookResponse, DeleteWebhookRequest, DeleteWebhookResponse, ListWebhooksRequest, ListWebhooksResponse, RegenerateWebhookTokenRequest, RegenerateWebhookTokenResponse, UpdateWebhookRequest, UpdateWebhookResponse } from "./webhooks_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * AdminWebhookService manages channel webhooks. Every RPC requires the
 * `webhook.manage` permission, held by the owner and admin roles by default.
 *
 * @generated from service chatto.admin.v1.AdminWebhookService
 */
export const AdminWebhookService = {
  typeName: "chatto.admin.v1.AdminWebhookService",
  methods: {
    /**
     * Creates a webhook against a room and returns its one-time secret URL.
     * Requires `webhook.manage`.
     *
     * @generated from rpc chatto.admin.v1.AdminWebhookService.CreateWebhook
     */
    createWebhook: {
      name: "CreateWebhook",
      I: CreateWebhookRequest,
      O: CreateWebhookResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Updates a webhook's name, avatar, or disabled state. Requires
     * `webhook.manage`.
     *
     * @generated from rpc chatto.admin.v1.AdminWebhookService.UpdateWebhook
     */
    updateWebhook: {
      name: "UpdateWebhook",
      I: UpdateWebhookRequest,
      O: UpdateWebhookResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Deletes a webhook and disables its backing identity. Requires
     * `webhook.manage`.
     *
     * @generated from rpc chatto.admin.v1.AdminWebhookService.DeleteWebhook
     */
    deleteWebhook: {
      name: "DeleteWebhook",
      I: DeleteWebhookRequest,
      O: DeleteWebhookResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Lists webhooks, optionally filtered to one room. Requires `webhook.manage`.
     *
     * @generated from rpc chatto.admin.v1.AdminWebhookService.ListWebhooks
     */
    listWebhooks: {
      name: "ListWebhooks",
      I: ListWebhooksRequest,
      O: ListWebhooksResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Regenerates a webhook's secret token, invalidating the previous URL.
     * Requires `webhook.manage`.
     *
     * @generated from rpc chatto.admin.v1.AdminWebhookService.RegenerateWebhookToken
     */
    regenerateWebhookToken: {
      name: "RegenerateWebhookToken",
      I: RegenerateWebhookTokenRequest,
      O: RegenerateWebhookTokenResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;
