// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: chatto/admin/v1/roles.proto

package adminv1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	v1 "hmans.de/chatto/internal/pb/chatto/api/v1"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Role metadata plus administrative permission state.
type AdminRole struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Public role metadata shared with ordinary role catalog reads.
	Role *v1.Role `protobuf:"bytes,1,opt,name=role,proto3" json:"role,omitempty"`
	// Permissions granted by this role.
	Permissions []string `protobuf:"bytes,2,rep,name=permissions,proto3" json:"permissions,omitempty"`
	// Permissions denied by this role.
	PermissionDenials []string `protobuf:"bytes,3,rep,name=permission_denials,json=permissionDenials,proto3" json:"permission_denials,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *AdminRole) Reset() {
	*x = AdminRole{}
	mi := &file_chatto_admin_v1_roles_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminRole) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminRole) ProtoMessage() {}

func (x *AdminRole) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_admin_v1_roles_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminRole.ProtoReflect.Descriptor instead.
func (*AdminRole) Descriptor() ([]byte, []int) {
	return file_chatto_admin_v1_roles_proto_rawDescGZIP(), []int{0}
}

func (x *AdminRole) GetRole() *v1.Role {
	if x != nil {
		return x.Role
	}
	return nil
}

func (x *AdminRole) GetPermissions() []string {
	if x != nil {
		return x.Permissions
	}
	return nil
}

func (x *AdminRole) GetPermissionDenials() []string {
	if x != nil {
		return x.PermissionDenials
	}
	return nil
}

// Request the role catalog.
type ListRolesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRolesRequest) Reset() {
	*x = ListRolesRequest{}
	mi := &file_chatto_admin_v1_roles_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRolesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRolesRequest) ProtoMessage() {}

func (x *ListRolesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_admin_v1_roles_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRolesRequest.ProtoReflect.Descriptor instead.
func (*ListRolesRequest) Descriptor() ([]byte, []int) {
	return file_chatto_admin_v1_roles_proto_rawDescGZIP(), []int{1}
}

// Finite role catalog snapshot plus viewer role-management capabilities.
type ListRolesResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Roles sorted by position.
	Roles []*AdminRole `protobuf:"bytes,1,rep,name=roles,proto3" json:"roles,omitempty"`
	// Whether the caller may create/update/delete role definitions.
	ViewerCanManageRoles bool `protobuf:"varint,2,opt,name=viewer_can_manage_roles,json=viewerCanManageRoles,proto3" json:"viewer_can_manage_roles,omitempty"`
	// Whether the caller may assign/revoke roles and view role rosters.
	ViewerCanAssignRoles bool `protobuf:"varint,3,opt,name=viewer_can_assign_roles,json=viewerCanAssignRoles,proto3" json:"viewer_can_assign_roles,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *ListRolesResponse) Reset() {
	*x = ListRolesResponse{}
	mi := &file_chatto_admin_v1_roles_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRolesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRolesResponse) ProtoMessage() {}

func (x *ListRolesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_admin_v1_roles_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRolesResponse.ProtoReflect.Descriptor instead.
func (*ListRolesResponse) Descriptor() ([]byte, []int) {
	return file_chatto_admin_v1_roles_proto_rawDescGZIP(), []int{2}
}

func (x *ListRolesResponse) GetRoles() []*AdminRole {
	if x != nil {
		return x.Roles
	}
	return nil
}

func (x *ListRolesResponse) GetViewerCanManageRoles() bool {
	if x != nil {
		return x.ViewerCanManageRoles
	}
	return false
}

func (x *ListRolesResponse) GetViewerCanAssignRoles() bool {
	if x != nil {
		return x.ViewerCanAssignRoles
	}
	return false
}

// Request one role.
type GetRoleRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Stable role name.
	Name          string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRoleRequest) Reset() {
	*x = GetRoleRequest{}
	mi := &file_chatto_admin_v1_roles_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRoleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRoleRequest) ProtoMessage() {}

func (x *GetRoleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_admin_v1_roles_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRoleRequest.ProtoReflect.Descriptor instead.
func (*GetRoleRequest) Descriptor() ([]byte, []int) {
	return file_chatto_admin_v1_roles_proto_rawDescGZIP(), []int{3}
}

func (x *GetRoleRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// One role plus role-management metadata.
type GetRoleResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Requested role.
	Role *AdminRole `protobuf:"bytes,1,opt,name=role,proto3" json:"role,omitempty"`
	// Explicit users with this role. Empty unless the caller may assign roles.
	Users []*v1.User `protobuf:"bytes,2,rep,name=users,proto3" json:"users,omitempty"`
	// Whether the caller may create/update/delete role definitions.
	ViewerCanManageRoles bool `protobuf:"varint,3,opt,name=viewer_can_manage_roles,json=viewerCanManageRoles,proto3" json:"viewer_can_manage_roles,omitempty"`
	// Whether the caller may assign/revoke roles and view role rosters.
	ViewerCanAssignRoles bool `protobuf:"varint,4,opt,name=viewer_can_assign_roles,json=viewerCanAssignRoles,proto3" json:"viewer_can_assign_roles,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *GetRoleResponse) Reset() {
	*x = GetRoleResponse{}
	mi := &file_chatto_admin_v1_roles_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRoleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRoleResponse) ProtoMessage() {}

func (x *GetRoleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_admin_v1_roles_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRoleResponse.ProtoReflect.Descriptor instead.
func (*GetRoleResponse) Descriptor() ([]byte, []int) {
	return file_chatto_admin_v1_roles_proto_rawDescGZIP(), []int{4}
}

func (x *GetRoleResponse) GetRole() *AdminRole {
	if x != nil {
		return x.Role
	}
	return nil
}

func (x *GetRoleResponse) GetUsers() []*v1.User {
	if x != nil {
		return x.Users
	}
	return nil
}

func (x *GetRoleResponse) GetViewerCanManageRoles() bool {
	if x != nil {
		return x.ViewerCanManageRoles
	}
	return false
}

func (x *GetRoleResponse) GetViewerCanAssignRoles() bool {
	if x != nil {
		return x.ViewerCanAssignRoles
	}
	return false
}

// Request to create a role.
type CreateRoleRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Stable role name.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Display name shown in admin and mention UIs.
	DisplayName string `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	// Optional role description.
	Description string `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	// Whether messages may notify users assigned to this role.
	Pingable bool `protobuf:"varint,4,opt,name=pingable,proto3" json:"pingable,omitempty"`
	// Optional 24-bit RGB colour used for member names. Zero uses the client
	// theme's default colour.
	Color         uint32 `protobuf:"varint,5,opt,name=color,proto3" json:"color,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRoleRequest) Reset() {
	*x = CreateRoleRequest{}
	mi := &file_chatto_admin_v1_roles_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRoleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRoleRequest) ProtoMessage() {}

func (x *CreateRoleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_admin_v1_roles_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRoleRequest.ProtoReflect.Descriptor instead.
func (*CreateRoleRequest) Descriptor() ([]byte, []int) {
	return file_chatto_admin_v1_roles_proto_rawDescGZIP(), []int{5}
}

func (x *CreateRoleRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateRoleRequest) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *CreateRoleRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateRoleRequest) GetPingable() bool {
	if x != nil {
		return x.Pingable
	}
	return false
}

func (x *CreateRoleRequest) GetColor() uint32 {
	if x != nil {
		return x.Color
	}
	return 0
}

// Result of creating a role.
type CreateRoleResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Created role.
	Role          *AdminRole `protobuf:"bytes,1,opt,name=role,proto3" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRoleResponse) Reset() {
	*x = CreateRoleResponse{}
	mi := &file_chatto_admin_v1_roles_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRoleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRoleResponse) ProtoMessage() {}

func (x *CreateRoleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_admin_v1_roles_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRoleResponse.ProtoReflect.Descriptor instead.
func (*CreateRoleResponse) Descriptor() ([]byte, []int) {
	return file_chatto_admin_v1_roles_proto_rawDescGZIP(), []int{6}
}

func (x *CreateRoleResponse) GetRole() *AdminRole {
	if x != nil {
		return x.Role
	}
	return nil
}

// Request to update role metadata.
type UpdateRoleRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Stable role name.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Display name shown in admin and mention UIs, when changing it.
	DisplayName *string `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3,oneof" json:"display_name,omitempty"`
	// Role description, when changing it. Empty clears the description.
	Description *string `protobuf:"bytes,3,opt,name=description,proto3,oneof" json:"description,omitempty"`
	// Whether messages may notify users assigned to this role, when changing it.
	Pingable *bool `protobuf:"varint,4,opt,name=pingable,proto3,oneof" json:"pingable,omitempty"`
	// 24-bit RGB colour, when changing it. Zero restores the client theme's
	// default colour.
	Color         *uint32 `protobuf:"varint,5,opt,name=color,proto3,oneof" json:"color,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateRoleRequest) Reset() {
	*x = UpdateRoleRequest{}
	mi := &file_chatto_admin_v1_roles_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRoleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRoleRequest) ProtoMessage() {}

func (x *UpdateRoleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_admin_v1_roles_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRoleRequest.ProtoReflect.Descriptor instead.
func (*UpdateRoleRequest) Descriptor() ([]byte, []int) {
	return file_chatto_admin_v1_roles_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateRoleRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateRoleRequest) GetDisplayName() string {
	if x != nil && x.DisplayName != nil {
		return *x.DisplayName
	}
	return ""
}

func (x *UpdateRoleRequest) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *UpdateRoleRequest) GetPingable() bool {
	if x != nil && x.Pingable != nil {
		return *x.Pingable
	}
	return false
}

func (x *UpdateRoleRequest) GetColor() uint32 {
	if x != nil && x.Color != nil {
		return *x.Color
	}
	return 0
}

// Result of updating a role.
type UpdateRoleResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Updated role.
	Role          *AdminRole `protobuf:"bytes,1,opt,name=role,proto3" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateRoleResponse) Reset() {
	*x = UpdateRoleResponse{}
	mi := &file_chatto_admin_v1_roles_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRoleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRoleResponse) ProtoMessage() {}

func (x *UpdateRoleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_admin_v1_roles_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRoleResponse.ProtoReflect.Descriptor instead.
func (*UpdateRoleResponse) Descriptor() ([]byte, []int) {
	return file_chatto_admin_v1_roles_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateRoleResponse) GetRole() *AdminRole {
	if x != nil {
		return x.Role
	}
	return nil
}

// Request to delete a role.
type DeleteRoleRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Stable role name.
	Name          string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRoleRequest) Reset() {
	*x = DeleteRoleRequest{}
	mi := &file_chatto_admin_v1_roles_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRoleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRoleRequest) ProtoMessage() {}

func (x *DeleteRoleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_admin_v1_roles_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRoleRequest.ProtoReflect.Descriptor instead.
func (*DeleteRoleRequest) Descriptor() ([]byte, []int) {
	return file_chatto_admin_v1_roles_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteRoleRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// Result of deleting a role.
type DeleteRoleResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// True when the request completed.
	Deleted       bool `protobuf:"varint,1,opt,name=deleted,proto3" json:"deleted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRoleResponse) Reset() {
	*x = DeleteRoleResponse{}
	mi := &file_chatto_admin_v1_roles_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRoleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRoleResponse) ProtoMessage() {}

func (x *DeleteRoleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_admin_v1_roles_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRoleResponse.ProtoReflect.Descriptor instead.
func (*DeleteRoleResponse) Descriptor() ([]byte, []int) {
	return file_chatto_admin_v1_roles_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteRoleResponse) GetDeleted() bool {
	if x != nil {
		return x.Deleted
	}
	return false
}

// Request to replace custom role order.
type ReorderRolesRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Ordered custom role names. The list must include every custom role exactly
	// once; system roles keep fixed positions and must not be included.
	RoleNames     []string `protobuf:"bytes,1,rep,name=role_names,json=roleNames,proto3" json:"role_names,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReorderRolesRequest) Reset() {
	*x = ReorderRolesRequest{}
	mi := &file_chatto_admin_v1_roles_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReorderRolesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReorderRolesRequest) ProtoMessage() {}

func (x *ReorderRolesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_admin_v1_roles_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReorderRolesRequest.ProtoReflect.Descriptor instead.
func (*ReorderRolesRequest) Descriptor() ([]byte, []int) {
	return file_chatto_admin_v1_roles_proto_rawDescGZIP(), []int{11}
}

func (x *ReorderRolesRequest) GetRoleNames() []string {
	if x != nil {
		return x.RoleNames
	}
	return nil
}

// Result of replacing custom role order.
type ReorderRolesResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Full role catalog after reordering.
	Roles         []*AdminRole `protobuf:"bytes,1,rep,name=roles,proto3" json:"roles,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReorderRolesResponse) Reset() {
	*x = ReorderRolesResponse{}
	mi := &file_chatto_admin_v1_roles_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReorderRolesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReorderRolesResponse) ProtoMessage() {}

func (x *ReorderRolesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_admin_v1_roles_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReorderRolesResponse.ProtoReflect.Descriptor instead.
func (*ReorderRolesResponse) Descriptor() ([]byte, []int) {
	return file_chatto_admin_v1_roles_proto_rawDescGZIP(), []int{12}
}

func (x *ReorderRolesResponse) GetRoles() []*AdminRole {
	if x != nil {
		return x.Roles
	}
	return nil
}

var File_chatto_admin_v1_roles_proto protoreflect.FileDescriptor

const file_chatto_admin_v1_roles_proto_rawDesc = "" +
	"\n" +
	"\x1bchatto/admin/v1/roles.proto\x12\x0fchatto.admin.v1\x1a\x1bbuf/validate/validate.proto\x1a\x19chatto/api/v1/roles.proto\x1a\x19chatto/api/v1/users.proto\"\x85\x01\n" +
	"\tAdminRole\x12'\n" +
	"\x04role\x18\x01 \x01(\v2\x13.chatto.api.v1.RoleR\x04role\x12 \n" +
	"\vpermissions\x18\x02 \x03(\tR\vpermissions\x12-\n" +
	"\x12permission_denials\x18\x03 \x03(\tR\x11permissionDenials\"\x12\n" +
	"\x10ListRolesRequest\"\xb3\x01\n" +
	"\x11ListRolesResponse\x120\n" +
	"\x05roles\x18\x01 \x03(\v2\x1a.chatto.admin.v1.AdminRoleR\x05roles\x125\n" +
	"\x17viewer_can_manage_roles\x18\x02 \x01(\bR\x14viewerCanManageRoles\x125\n" +
	"\x17viewer_can_assign_roles\x18\x03 \x01(\bR\x14viewerCanAssignRoles\"-\n" +
	"\x0eGetRoleRequest\x12\x1b\n" +
	"\x04name\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x04name\"\xda\x01\n" +
	"\x0fGetRoleResponse\x12.\n" +
	"\x04role\x18\x01 \x01(\v2\x1a.chatto.admin.v1.AdminRoleR\x04role\x12)\n" +
	"\x05users\x18\x02 \x03(\v2\x13.chatto.api.v1.UserR\x05users\x125\n" +
	"\x17viewer_can_manage_roles\x18\x03 \x01(\bR\x14viewerCanManageRoles\x125\n" +
	"\x17viewer_can_assign_roles\x18\x04 \x01(\bR\x14viewerCanAssignRoles\"\xc6\x01\n" +
	"\x11CreateRoleRequest\x12\x1b\n" +
	"\x04name\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x04name\x12*\n" +
	"\fdisplay_name\x18\x02 \x01(\tB\a\xbaH\x04r\x02\x18PR\vdisplayName\x12*\n" +
	"\vdescription\x18\x03 \x01(\tB\b\xbaH\x05r\x03\x18\xf4\x03R\vdescription\x12\x1a\n" +
	"\bpingable\x18\x04 \x01(\bR\bpingable\x12 \n" +
	"\x05color\x18\x05 \x01(\rB\n" +
	"\xbaH\a*\x05\x18\xff\xff\xff\aR\x05color\"D\n" +
	"\x12CreateRoleResponse\x12.\n" +
	"\x04role\x18\x01 \x01(\v2\x1a.chatto.admin.v1.AdminRoleR\x04role\"\x92\x02\n" +
	"\x11UpdateRoleRequest\x12\x1b\n" +
	"\x04name\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x04name\x12/\n" +
	"\fdisplay_name\x18\x02 \x01(\tB\a\xbaH\x04r\x02\x18PH\x00R\vdisplayName\x88\x01\x01\x12/\n" +
	"\vdescription\x18\x03 \x01(\tB\b\xbaH\x05r\x03\x18\xf4\x03H\x01R\vdescription\x88\x01\x01\x12\x1f\n" +
	"\bpingable\x18\x04 \x01(\bH\x02R\bpingable\x88\x01\x01\x12%\n" +
	"\x05color\x18\x05 \x01(\rB\n" +
	"\xbaH\a*\x05\x18\xff\xff\xff\aH\x03R\x05color\x88\x01\x01B\x0f\n" +
	"\r_display_nameB\x0e\n" +
	"\f_descriptionB\v\n" +
	"\t_pingableB\b\n" +
	"\x06_color\"D\n" +
	"\x12UpdateRoleResponse\x12.\n" +
	"\x04role\x18\x01 \x01(\v2\x1a.chatto.admin.v1.AdminRoleR\x04role\"0\n" +
	"\x11DeleteRoleRequest\x12\x1b\n" +
	"\x04name\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x04name\".\n" +
	"\x12DeleteRoleResponse\x12\x18\n" +
	"\adeleted\x18\x01 \x01(\bR\adeleted\"E\n" +
	"\x13ReorderRolesRequest\x12.\n" +
	"\n" +
	"role_names\x18\x01 \x03(\tB\x0f\xbaH\f\x92\x01\t\x10\xe8\a\"\x04r\x02\x10\x01R\troleNames\"H\n" +
	"\x14ReorderRolesResponse\x120\n" +
	"\x05roles\x18\x01 \x03(\v2\x1a.chatto.admin.v1.AdminRoleR\x05roles2\x96\x04\n" +
	"\x10AdminRoleService\x12R\n" +
	"\tListRoles\x12!.chatto.admin.v1.ListRolesRequest\x1a\".chatto.admin.v1.ListRolesResponse\x12L\n" +
	"\aGetRole\x12\x1f.chatto.admin.v1.GetRoleRequest\x1a .chatto.admin.v1.GetRoleResponse\x12U\n" +
	"\n" +
	"CreateRole\x12\".chatto.admin.v1.CreateRoleRequest\x1a#.chatto.admin.v1.CreateRoleResponse\x12U\n" +
	"\n" +
	"UpdateRole\x12\".chatto.admin.v1.UpdateRoleRequest\x1a#.chatto.admin.v1.UpdateRoleResponse\x12U\n" +
	"\n" +
	"DeleteRole\x12\".chatto.admin.v1.DeleteRoleRequest\x1a#.chatto.admin.v1.DeleteRoleResponse\x12[\n" +
	"\fReorderRoles\x12$.chatto.admin.v1.ReorderRolesRequest\x1a%.chatto.admin.v1.ReorderRolesResponseB\xb4\x01\n" +
	"\x13com.chatto.admin.v1B\n" +
	"RolesProtoP\x01Z3hmans.de/chatto/internal/pb/chatto/admin/v1;adminv1\xa2\x02\x03CAX\xaa\x02\x0fChatto.Admin.V1\xca\x02\x0fChatto\\Admin\\V1\xe2\x02\x1bChatto\\Admin\\V1\\GPBMetadata\xea\x02\x11Chatto::Admin::V1b\x06proto3"

var (
	file_chatto_admin_v1_roles_proto_rawDescOnce sync.Once
	file_chatto_admin_v1_roles_proto_rawDescData []byte
)

func file_chatto_admin_v1_roles_proto_rawDescGZIP() []byte {
	file_chatto_admin_v1_roles_proto_rawDescOnce.Do(func() {
		file_chatto_admin_v1_roles_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_chatto_admin_v1_roles_proto_rawDesc), len(file_chatto_admin_v1_roles_proto_rawDesc)))
	})
	return file_chatto_admin_v1_roles_proto_rawDescData
}

var file_chatto_admin_v1_roles_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_chatto_admin_v1_roles_proto_goTypes = []any{
	(*AdminRole)(nil),            // 0: chatto.admin.v1.AdminRole
	(*ListRolesRequest)(nil),     // 1: chatto.admin.v1.ListRolesRequest
	(*ListRolesResponse)(nil),    // 2: chatto.admin.v1.ListRolesResponse
	(*GetRoleRequest)(nil),       // 3: chatto.admin.v1.GetRoleRequest
	(*GetRoleResponse)(nil),      // 4: chatto.admin.v1.GetRoleResponse
	(*CreateRoleRequest)(nil),    // 5: chatto.admin.v1.CreateRoleRequest
	(*CreateRoleResponse)(nil),   // 6: chatto.admin.v1.CreateRoleResponse
	(*UpdateRoleRequest)(nil),    // 7: chatto.admin.v1.UpdateRoleRequest
	(*UpdateRoleResponse)(nil),   // 8: chatto.admin.v1.UpdateRoleResponse
	(*DeleteRoleRequest)(nil),    // 9: chatto.admin.v1.DeleteRoleRequest
	(*DeleteRoleResponse)(nil),   // 10: chatto.admin.v1.DeleteRoleResponse
	(*ReorderRolesRequest)(nil),  // 11: chatto.admin.v1.ReorderRolesRequest
	(*ReorderRolesResponse)(nil), // 12: chatto.admin.v1.ReorderRolesResponse
	(*v1.Role)(nil),              // 13: chatto.api.v1.Role
	(*v1.User)(nil),              // 14: chatto.api.v1.User
}
var file_chatto_admin_v1_roles_proto_depIdxs = []int32{
	13, // 0: chatto.admin.v1.AdminRole.role:type_name -> chatto.api.v1.Role
	0,  // 1: chatto.admin.v1.ListRolesResponse.roles:type_name -> chatto.admin.v1.AdminRole
	0,  // 2: chatto.admin.v1.GetRoleResponse.role:type_name -> chatto.admin.v1.AdminRole
	14, // 3: chatto.admin.v1.GetRoleResponse.users:type_name -> chatto.api.v1.User
	0,  // 4: chatto.admin.v1.CreateRoleResponse.role:type_name -> chatto.admin.v1.AdminRole
	0,  // 5: chatto.admin.v1.UpdateRoleResponse.role:type_name -> chatto.admin.v1.AdminRole
	0,  // 6: chatto.admin.v1.ReorderRolesResponse.roles:type_name -> chatto.admin.v1.AdminRole
	1,  // 7: chatto.admin.v1.AdminRoleService.ListRoles:input_type -> chatto.admin.v1.ListRolesRequest
	3,  // 8: chatto.admin.v1.AdminRoleService.GetRole:input_type -> chatto.admin.v1.GetRoleRequest
	5,  // 9: chatto.admin.v1.AdminRoleService.CreateRole:input_type -> chatto.admin.v1.CreateRoleRequest
	7,  // 10: chatto.admin.v1.AdminRoleService.UpdateRole:input_type -> chatto.admin.v1.UpdateRoleRequest
	9,  // 11: chatto.admin.v1.AdminRoleService.DeleteRole:input_type -> chatto.admin.v1.DeleteRoleRequest
	11, // 12: chatto.admin.v1.AdminRoleService.ReorderRoles:input_type -> chatto.admin.v1.ReorderRolesRequest
	2,  // 13: chatto.admin.v1.AdminRoleService.ListRoles:output_type -> chatto.admin.v1.ListRolesResponse
	4,  // 14: chatto.admin.v1.AdminRoleService.GetRole:output_type -> chatto.admin.v1.GetRoleResponse
	6,  // 15: chatto.admin.v1.AdminRoleService.CreateRole:output_type -> chatto.admin.v1.CreateRoleResponse
	8,  // 16: chatto.admin.v1.AdminRoleService.UpdateRole:output_type -> chatto.admin.v1.UpdateRoleResponse
	10, // 17: chatto.admin.v1.AdminRoleService.DeleteRole:output_type -> chatto.admin.v1.DeleteRoleResponse
	12, // 18: chatto.admin.v1.AdminRoleService.ReorderRoles:output_type -> chatto.admin.v1.ReorderRolesResponse
	13, // [13:19] is the sub-list for method output_type
	7,  // [7:13] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_chatto_admin_v1_roles_proto_init() }
func file_chatto_admin_v1_roles_proto_init() {
	if File_chatto_admin_v1_roles_proto != nil {
		return
	}
	file_chatto_admin_v1_roles_proto_msgTypes[7].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_chatto_admin_v1_roles_proto_rawDesc), len(file_chatto_admin_v1_roles_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_chatto_admin_v1_roles_proto_goTypes,
		DependencyIndexes: file_chatto_admin_v1_roles_proto_depIdxs,
		MessageInfos:      file_chatto_admin_v1_roles_proto_msgTypes,
	}.Build()
	File_chatto_admin_v1_roles_proto = out.File
	file_chatto_admin_v1_roles_proto_goTypes = nil
	file_chatto_admin_v1_roles_proto_depIdxs = nil
}
