// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: chatto/admin/v1/webhooks.proto

package adminv1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	v1 "hmans.de/chatto/internal/pb/chatto/api/v1"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// A channel webhook: a token-authorized endpoint that posts messages into a
// specific room under a synthetic, non-human webhook identity (FDR-035). The
// secret token is embedded in the post URL and is only ever returned once, at
// creation and regeneration time.
type Webhook struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Webhook identifier.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Room this webhook posts into.
	RoomId string `protobuf:"bytes,2,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	// Human-facing webhook name and default author display name.
	Name string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	// Default avatar image URL for the webhook identity, when set.
	AvatarUrl *string `protobuf:"bytes,4,opt,name=avatar_url,json=avatarUrl,proto3,oneof" json:"avatar_url,omitempty"`
	// User ID of the administrator who created the webhook.
	CreatedBy string `protobuf:"bytes,5,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`
	// Creation time in Unix milliseconds.
	CreatedAtMs int64 `protobuf:"varint,6,opt,name=created_at_ms,json=createdAtMs,proto3" json:"created_at_ms,omitempty"`
	// When true, the webhook is retained but rejects inbound posts.
	Disabled bool `protobuf:"varint,7,opt,name=disabled,proto3" json:"disabled,omitempty"`
	// User ID of the synthetic webhook user that authors this webhook's messages.
	UserId        string `protobuf:"bytes,8,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Webhook) Reset() {
	*x = Webhook{}
	mi := &file_chatto_admin_v1_webhooks_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Webhook) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Webhook) ProtoMessage() {}

func (x *Webhook) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_admin_v1_webhooks_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Webhook.ProtoReflect.Descriptor instead.
func (*Webhook) Descriptor() ([]byte, []int) {
	return file_chatto_admin_v1_webhooks_proto_rawDescGZIP(), []int{0}
}

func (x *Webhook) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Webhook) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *Webhook) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Webhook) GetAvatarUrl() string {
	if x != nil && x.AvatarUrl != nil {
		return *x.AvatarUrl
	}
	return ""
}

func (x *Webhook) GetCreatedBy() string {
	if x != nil {
		return x.CreatedBy
	}
	return ""
}

func (x *Webhook) GetCreatedAtMs() int64 {
	if x != nil {
		return x.CreatedAtMs
	}
	return 0
}

func (x *Webhook) GetDisabled() bool {
	if x != nil {
		return x.Disabled
	}
	return false
}

func (x *Webhook) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

// Request to create a webhook against a room.
type CreateWebhookRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required. Room the webhook posts into.
	RoomId string `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	// Required. Webhook name / default author display name.
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// Optional default avatar image, processed into a stored asset.
	Avatar        *v1.ImageUpload `protobuf:"bytes,3,opt,name=avatar,proto3" json:"avatar,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateWebhookRequest) Reset() {
	*x = CreateWebhookRequest{}
	mi := &file_chatto_admin_v1_webhooks_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateWebhookRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateWebhookRequest) ProtoMessage() {}

func (x *CreateWebhookRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_admin_v1_webhooks_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateWebhookRequest.ProtoReflect.Descriptor instead.
func (*CreateWebhookRequest) Descriptor() ([]byte, []int) {
	return file_chatto_admin_v1_webhooks_proto_rawDescGZIP(), []int{1}
}

func (x *CreateWebhookRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *CreateWebhookRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateWebhookRequest) GetAvatar() *v1.ImageUpload {
	if x != nil {
		return x.Avatar
	}
	return nil
}

// Result of creating a webhook, including the one-time secret.
type CreateWebhookResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The created webhook.
	Webhook *Webhook `protobuf:"bytes,1,opt,name=webhook,proto3" json:"webhook,omitempty"`
	// Raw secret token. Shown once; only its hash is stored server-side.
	Token string `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	// Full post URL (base URL + webhook id + token). Shown once.
	Url           string `protobuf:"bytes,3,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateWebhookResponse) Reset() {
	*x = CreateWebhookResponse{}
	mi := &file_chatto_admin_v1_webhooks_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateWebhookResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateWebhookResponse) ProtoMessage() {}

func (x *CreateWebhookResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_admin_v1_webhooks_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateWebhookResponse.ProtoReflect.Descriptor instead.
func (*CreateWebhookResponse) Descriptor() ([]byte, []int) {
	return file_chatto_admin_v1_webhooks_proto_rawDescGZIP(), []int{2}
}

func (x *CreateWebhookResponse) GetWebhook() *Webhook {
	if x != nil {
		return x.Webhook
	}
	return nil
}

func (x *CreateWebhookResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *CreateWebhookResponse) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

// Request to update a webhook's mutable fields. Unset fields are unchanged.
type UpdateWebhookRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required. Webhook to update.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// New name, when changing it.
	Name *string `protobuf:"bytes,2,opt,name=name,proto3,oneof" json:"name,omitempty"`
	// New avatar image, when replacing it.
	Avatar *v1.ImageUpload `protobuf:"bytes,3,opt,name=avatar,proto3" json:"avatar,omitempty"`
	// When true, remove the current avatar (mutually exclusive with `avatar`).
	ClearAvatar *bool `protobuf:"varint,4,opt,name=clear_avatar,json=clearAvatar,proto3,oneof" json:"clear_avatar,omitempty"`
	// New disabled state, when changing it.
	Disabled      *bool `protobuf:"varint,5,opt,name=disabled,proto3,oneof" json:"disabled,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateWebhookRequest) Reset() {
	*x = UpdateWebhookRequest{}
	mi := &file_chatto_admin_v1_webhooks_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateWebhookRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateWebhookRequest) ProtoMessage() {}

func (x *UpdateWebhookRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_admin_v1_webhooks_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateWebhookRequest.ProtoReflect.Descriptor instead.
func (*UpdateWebhookRequest) Descriptor() ([]byte, []int) {
	return file_chatto_admin_v1_webhooks_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateWebhookRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateWebhookRequest) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *UpdateWebhookRequest) GetAvatar() *v1.ImageUpload {
	if x != nil {
		return x.Avatar
	}
	return nil
}

func (x *UpdateWebhookRequest) GetClearAvatar() bool {
	if x != nil && x.ClearAvatar != nil {
		return *x.ClearAvatar
	}
	return false
}

func (x *UpdateWebhookRequest) GetDisabled() bool {
	if x != nil && x.Disabled != nil {
		return *x.Disabled
	}
	return false
}

// Result of updating a webhook.
type UpdateWebhookResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The updated webhook.
	Webhook       *Webhook `protobuf:"bytes,1,opt,name=webhook,proto3" json:"webhook,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateWebhookResponse) Reset() {
	*x = UpdateWebhookResponse{}
	mi := &file_chatto_admin_v1_webhooks_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateWebhookResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateWebhookResponse) ProtoMessage() {}

func (x *UpdateWebhookResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_admin_v1_webhooks_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateWebhookResponse.ProtoReflect.Descriptor instead.
func (*UpdateWebhookResponse) Descriptor() ([]byte, []int) {
	return file_chatto_admin_v1_webhooks_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateWebhookResponse) GetWebhook() *Webhook {
	if x != nil {
		return x.Webhook
	}
	return nil
}

// Request to delete a webhook by ID.
type DeleteWebhookRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required. Webhook to delete.
	Id            string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteWebhookRequest) Reset() {
	*x = DeleteWebhookRequest{}
	mi := &file_chatto_admin_v1_webhooks_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteWebhookRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteWebhookRequest) ProtoMessage() {}

func (x *DeleteWebhookRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_admin_v1_webhooks_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteWebhookRequest.ProtoReflect.Descriptor instead.
func (*DeleteWebhookRequest) Descriptor() ([]byte, []int) {
	return file_chatto_admin_v1_webhooks_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteWebhookRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// Result of deleting a webhook.
type DeleteWebhookResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteWebhookResponse) Reset() {
	*x = DeleteWebhookResponse{}
	mi := &file_chatto_admin_v1_webhooks_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteWebhookResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteWebhookResponse) ProtoMessage() {}

func (x *DeleteWebhookResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_admin_v1_webhooks_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteWebhookResponse.ProtoReflect.Descriptor instead.
func (*DeleteWebhookResponse) Descriptor() ([]byte, []int) {
	return file_chatto_admin_v1_webhooks_proto_rawDescGZIP(), []int{6}
}

// Request to list webhooks, optionally filtered to one room.
type ListWebhooksRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// When set, only webhooks posting into this room are returned.
	RoomId        *string `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3,oneof" json:"room_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListWebhooksRequest) Reset() {
	*x = ListWebhooksRequest{}
	mi := &file_chatto_admin_v1_webhooks_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListWebhooksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListWebhooksRequest) ProtoMessage() {}

func (x *ListWebhooksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_admin_v1_webhooks_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListWebhooksRequest.ProtoReflect.Descriptor instead.
func (*ListWebhooksRequest) Descriptor() ([]byte, []int) {
	return file_chatto_admin_v1_webhooks_proto_rawDescGZIP(), []int{7}
}

func (x *ListWebhooksRequest) GetRoomId() string {
	if x != nil && x.RoomId != nil {
		return *x.RoomId
	}
	return ""
}

// Response carrying the matching webhooks.
type ListWebhooksResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Webhooks, ordered by creation time.
	Webhooks      []*Webhook `protobuf:"bytes,1,rep,name=webhooks,proto3" json:"webhooks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListWebhooksResponse) Reset() {
	*x = ListWebhooksResponse{}
	mi := &file_chatto_admin_v1_webhooks_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListWebhooksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListWebhooksResponse) ProtoMessage() {}

func (x *ListWebhooksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_admin_v1_webhooks_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListWebhooksResponse.ProtoReflect.Descriptor instead.
func (*ListWebhooksResponse) Descriptor() ([]byte, []int) {
	return file_chatto_admin_v1_webhooks_proto_rawDescGZIP(), []int{8}
}

func (x *ListWebhooksResponse) GetWebhooks() []*Webhook {
	if x != nil {
		return x.Webhooks
	}
	return nil
}

// Request to regenerate a webhook's secret token, invalidating the previous one.
type RegenerateWebhookTokenRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required. Webhook whose token is regenerated.
	Id            string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegenerateWebhookTokenRequest) Reset() {
	*x = RegenerateWebhookTokenRequest{}
	mi := &file_chatto_admin_v1_webhooks_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegenerateWebhookTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegenerateWebhookTokenRequest) ProtoMessage() {}

func (x *RegenerateWebhookTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_admin_v1_webhooks_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegenerateWebhookTokenRequest.ProtoReflect.Descriptor instead.
func (*RegenerateWebhookTokenRequest) Descriptor() ([]byte, []int) {
	return file_chatto_admin_v1_webhooks_proto_rawDescGZIP(), []int{9}
}

func (x *RegenerateWebhookTokenRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// Result of regenerating a webhook token, including the new one-time secret.
type RegenerateWebhookTokenResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The webhook.
	Webhook *Webhook `protobuf:"bytes,1,opt,name=webhook,proto3" json:"webhook,omitempty"`
	// New raw secret token. Shown once.
	Token string `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	// New full post URL. Shown once.
	Url           string `protobuf:"bytes,3,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegenerateWebhookTokenResponse) Reset() {
	*x = RegenerateWebhookTokenResponse{}
	mi := &file_chatto_admin_v1_webhooks_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegenerateWebhookTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegenerateWebhookTokenResponse) ProtoMessage() {}

func (x *RegenerateWebhookTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_admin_v1_webhooks_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegenerateWebhookTokenResponse.ProtoReflect.Descriptor instead.
func (*RegenerateWebhookTokenResponse) Descriptor() ([]byte, []int) {
	return file_chatto_admin_v1_webhooks_proto_rawDescGZIP(), []int{10}
}

func (x *RegenerateWebhookTokenResponse) GetWebhook() *Webhook {
	if x != nil {
		return x.Webhook
	}
	return nil
}

func (x *RegenerateWebhookTokenResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *RegenerateWebhookTokenResponse) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

var File_chatto_admin_v1_webhooks_proto protoreflect.FileDescriptor

const file_chatto_admin_v1_webhooks_proto_rawDesc = "" +
	"\n" +
	"\x1echatto/admin/v1/webhooks.proto\x12\x0fchatto.admin.v1\x1a\x1bbuf/validate/validate.proto\x1a\x1achatto/api/v1/common.proto\"\xf1\x01\n" +
	"\aWebhook\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\aroom_id\x18\x02 \x01(\tR\x06roomId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\"\n" +
	"\n" +
	"avatar_url\x18\x04 \x01(\tH\x00R\tavatarUrl\x88\x01\x01\x12\x1d\n" +
	"\n" +
	"created_by\x18\x05 \x01(\tR\tcreatedBy\x12\"\n" +
	"\rcreated_at_ms\x18\x06 \x01(\x03R\vcreatedAtMs\x12\x1a\n" +
	"\bdisabled\x18\a \x01(\bR\bdisabled\x12\x17\n" +
	"\auser_id\x18\b \x01(\tR\x06userIdB\r\n" +
	"\v_avatar_url\"\x8b\x01\n" +
	"\x14CreateWebhookRequest\x12 \n" +
	"\aroom_id\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x06roomId\x12\x1d\n" +
	"\x04name\x18\x02 \x01(\tB\t\xbaH\x06r\x04\x10\x01\x18PR\x04name\x122\n" +
	"\x06avatar\x18\x03 \x01(\v2\x1a.chatto.api.v1.ImageUploadR\x06avatar\"s\n" +
	"\x15CreateWebhookResponse\x122\n" +
	"\awebhook\x18\x01 \x01(\v2\x18.chatto.admin.v1.WebhookR\awebhook\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\x12\x10\n" +
	"\x03url\x18\x03 \x01(\tR\x03url\"\xf5\x01\n" +
	"\x14UpdateWebhookRequest\x12\x17\n" +
	"\x02id\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x02id\x12 \n" +
	"\x04name\x18\x02 \x01(\tB\a\xbaH\x04r\x02\x18PH\x00R\x04name\x88\x01\x01\x122\n" +
	"\x06avatar\x18\x03 \x01(\v2\x1a.chatto.api.v1.ImageUploadR\x06avatar\x12&\n" +
	"\fclear_avatar\x18\x04 \x01(\bH\x01R\vclearAvatar\x88\x01\x01\x12\x1f\n" +
	"\bdisabled\x18\x05 \x01(\bH\x02R\bdisabled\x88\x01\x01B\a\n" +
	"\x05_nameB\x0f\n" +
	"\r_clear_avatarB\v\n" +
	"\t_disabled\"K\n" +
	"\x15UpdateWebhookResponse\x122\n" +
	"\awebhook\x18\x01 \x01(\v2\x18.chatto.admin.v1.WebhookR\awebhook\"/\n" +
	"\x14DeleteWebhookRequest\x12\x17\n" +
	"\x02id\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x02id\"\x17\n" +
	"\x15DeleteWebhookResponse\"?\n" +
	"\x13ListWebhooksRequest\x12\x1c\n" +
	"\aroom_id\x18\x01 \x01(\tH\x00R\x06roomId\x88\x01\x01B\n" +
	"\n" +
	"\b_room_id\"L\n" +
	"\x14ListWebhooksResponse\x124\n" +
	"\bwebhooks\x18\x01 \x03(\v2\x18.chatto.admin.v1.WebhookR\bwebhooks\"8\n" +
	"\x1dRegenerateWebhookTokenRequest\x12\x17\n" +
	"\x02id\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x02id\"|\n" +
	"\x1eRegenerateWebhookTokenResponse\x122\n" +
	"\awebhook\x18\x01 \x01(\v2\x18.chatto.admin.v1.WebhookR\awebhook\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\x12\x10\n" +
	"\x03url\x18\x03 \x01(\tR\x03url2\x8d\x04\n" +
	"\x13AdminWebhookService\x12^\n" +
	"\rCreateWebhook\x12%.chatto.admin.v1.CreateWebhookRequest\x1a&.chatto.admin.v1.CreateWebhookResponse\x12^\n" +
	"\rUpdateWebhook\x12%.chatto.admin.v1.UpdateWebhookRequest\x1a&.chatto.admin.v1.UpdateWebhookResponse\x12^\n" +
	"\rDeleteWebhook\x12%.chatto.admin.v1.DeleteWebhookRequest\x1a&.chatto.admin.v1.DeleteWebhookResponse\x12[\n" +
	"\fListWebhooks\x12$.chatto.admin.v1.ListWebhooksRequest\x1a%.chatto.admin.v1.ListWebhooksResponse\x12y\n" +
	"\x16RegenerateWebhookToken\x12..chatto.admin.v1.RegenerateWebhookTokenRequest\x1a/.chatto.admin.v1.RegenerateWebhookTokenResponseB\xb7\x01\n" +
	"\x13com.chatto.admin.v1B\rWebhooksProtoP\x01Z3hmans.de/chatto/internal/pb/chatto/admin/v1;adminv1\xa2\x02\x03CAX\xaa\x02\x0fChatto.Admin.V1\xca\x02\x0fChatto\\Admin\\V1\xe2\x02\x1bChatto\\Admin\\V1\\GPBMetadata\xea\x02\x11Chatto::Admin::V1b\x06proto3"

var (
	file_chatto_admin_v1_webhooks_proto_rawDescOnce sync.Once
	file_chatto_admin_v1_webhooks_proto_rawDescData []byte
)

func file_chatto_admin_v1_webhooks_proto_rawDescGZIP() []byte {
	file_chatto_admin_v1_webhooks_proto_rawDescOnce.Do(func() {
		file_chatto_admin_v1_webhooks_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_chatto_admin_v1_webhooks_proto_rawDesc), len(file_chatto_admin_v1_webhooks_proto_rawDesc)))
	})
	return file_chatto_admin_v1_webhooks_proto_rawDescData
}

var file_chatto_admin_v1_webhooks_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_chatto_admin_v1_webhooks_proto_goTypes = []any{
	(*Webhook)(nil),                        // 0: chatto.admin.v1.Webhook
	(*CreateWebhookRequest)(nil),           // 1: chatto.admin.v1.CreateWebhookRequest
	(*CreateWebhookResponse)(nil),          // 2: chatto.admin.v1.CreateWebhookResponse
	(*UpdateWebhookRequest)(nil),           // 3: chatto.admin.v1.UpdateWebhookRequest
	(*UpdateWebhookResponse)(nil),          // 4: chatto.admin.v1.UpdateWebhookResponse
	(*DeleteWebhookRequest)(nil),           // 5: chatto.admin.v1.DeleteWebhookRequest
	(*DeleteWebhookResponse)(nil),          // 6: chatto.admin.v1.DeleteWebhookResponse
	(*ListWebhooksRequest)(nil),            // 7: chatto.admin.v1.ListWebhooksRequest
	(*ListWebhooksResponse)(nil),           // 8: chatto.admin.v1.ListWebhooksResponse
	(*RegenerateWebhookTokenRequest)(nil),  // 9: chatto.admin.v1.RegenerateWebhookTokenRequest
	(*RegenerateWebhookTokenResponse)(nil), // 10: chatto.admin.v1.RegenerateWebhookTokenResponse
	(*v1.ImageUpload)(nil),                 // 11: chatto.api.v1.ImageUpload
}
var file_chatto_admin_v1_webhooks_proto_depIdxs = []int32{
	11, // 0: chatto.admin.v1.CreateWebhookRequest.avatar:type_name -> chatto.api.v1.ImageUpload
	0,  // 1: chatto.admin.v1.CreateWebhookResponse.webhook:type_name -> chatto.admin.v1.Webhook
	11, // 2: chatto.admin.v1.UpdateWebhookRequest.avatar:type_name -> chatto.api.v1.ImageUpload
	0,  // 3: chatto.admin.v1.UpdateWebhookResponse.webhook:type_name -> chatto.admin.v1.Webhook
	0,  // 4: chatto.admin.v1.ListWebhooksResponse.webhooks:type_name -> chatto.admin.v1.Webhook
	0,  // 5: chatto.admin.v1.RegenerateWebhookTokenResponse.webhook:type_name -> chatto.admin.v1.Webhook
	1,  // 6: chatto.admin.v1.AdminWebhookService.CreateWebhook:input_type -> chatto.admin.v1.CreateWebhookRequest
	3,  // 7: chatto.admin.v1.AdminWebhookService.UpdateWebhook:input_type -> chatto.admin.v1.UpdateWebhookRequest
	5,  // 8: chatto.admin.v1.AdminWebhookService.DeleteWebhook:input_type -> chatto.admin.v1.DeleteWebhookRequest
	7,  // 9: chatto.admin.v1.AdminWebhookService.ListWebhooks:input_type -> chatto.admin.v1.ListWebhooksRequest
	9,  // 10: chatto.admin.v1.AdminWebhookService.RegenerateWebhookToken:input_type -> chatto.admin.v1.RegenerateWebhookTokenRequest
	2,  // 11: chatto.admin.v1.AdminWebhookService.CreateWebhook:output_type -> chatto.admin.v1.CreateWebhookResponse
	4,  // 12: chatto.admin.v1.AdminWebhookService.UpdateWebhook:output_type -> chatto.admin.v1.UpdateWebhookResponse
	6,  // 13: chatto.admin.v1.AdminWebhookService.DeleteWebhook:output_type -> chatto.admin.v1.DeleteWebhookResponse
	8,  // 14: chatto.admin.v1.AdminWebhookService.ListWebhooks:output_type -> chatto.admin.v1.ListWebhooksResponse
	10, // 15: chatto.admin.v1.AdminWebhookService.RegenerateWebhookToken:output_type -> chatto.admin.v1.RegenerateWebhookTokenResponse
	11, // [11:16] is the sub-list for method output_type
	6,  // [6:11] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_chatto_admin_v1_webhooks_proto_init() }
func file_chatto_admin_v1_webhooks_proto_init() {
	if File_chatto_admin_v1_webhooks_proto != nil {
		return
	}
	file_chatto_admin_v1_webhooks_proto_msgTypes[0].OneofWrappers = []any{}
	file_chatto_admin_v1_webhooks_proto_msgTypes[3].OneofWrappers = []any{}
	file_chatto_admin_v1_webhooks_proto_msgTypes[7].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_chatto_admin_v1_webhooks_proto_rawDesc), len(file_chatto_admin_v1_webhooks_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_chatto_admin_v1_webhooks_proto_goTypes,
		DependencyIndexes: file_chatto_admin_v1_webhooks_proto_depIdxs,
		MessageInfos:      file_chatto_admin_v1_webhooks_proto_msgTypes,
	}.Build()
	File_chatto_admin_v1_webhooks_proto = out.File
	file_chatto_admin_v1_webhooks_proto_goTypes = nil
	file_chatto_admin_v1_webhooks_proto_depIdxs = nil
}
