// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: chatto/core/v1/invitation_events.proto

package corev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// InvitationCreatedEvent establishes one server invitation and its immutable
// admission constraints. The shareable signed code is deliberately not stored.
type InvitationCreatedEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InvitationId  string                 `protobuf:"bytes,1,opt,name=invitation_id,json=invitationId,proto3" json:"invitation_id,omitempty"`
	MaxUses       *uint32                `protobuf:"varint,2,opt,name=max_uses,json=maxUses,proto3,oneof" json:"max_uses,omitempty"`
	ExpiresAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InvitationCreatedEvent) Reset() {
	*x = InvitationCreatedEvent{}
	mi := &file_chatto_core_v1_invitation_events_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InvitationCreatedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvitationCreatedEvent) ProtoMessage() {}

func (x *InvitationCreatedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_core_v1_invitation_events_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvitationCreatedEvent.ProtoReflect.Descriptor instead.
func (*InvitationCreatedEvent) Descriptor() ([]byte, []int) {
	return file_chatto_core_v1_invitation_events_proto_rawDescGZIP(), []int{0}
}

func (x *InvitationCreatedEvent) GetInvitationId() string {
	if x != nil {
		return x.InvitationId
	}
	return ""
}

func (x *InvitationCreatedEvent) GetMaxUses() uint32 {
	if x != nil && x.MaxUses != nil {
		return *x.MaxUses
	}
	return 0
}

func (x *InvitationCreatedEvent) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

// InvitationRedeemedEvent records the account admitted by an invitation.
type InvitationRedeemedEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InvitationId  string                 `protobuf:"bytes,1,opt,name=invitation_id,json=invitationId,proto3" json:"invitation_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InvitationRedeemedEvent) Reset() {
	*x = InvitationRedeemedEvent{}
	mi := &file_chatto_core_v1_invitation_events_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InvitationRedeemedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvitationRedeemedEvent) ProtoMessage() {}

func (x *InvitationRedeemedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_core_v1_invitation_events_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvitationRedeemedEvent.ProtoReflect.Descriptor instead.
func (*InvitationRedeemedEvent) Descriptor() ([]byte, []int) {
	return file_chatto_core_v1_invitation_events_proto_rawDescGZIP(), []int{1}
}

func (x *InvitationRedeemedEvent) GetInvitationId() string {
	if x != nil {
		return x.InvitationId
	}
	return ""
}

func (x *InvitationRedeemedEvent) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

// InvitationRevokedEvent permanently revokes an invitation.
type InvitationRevokedEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InvitationId  string                 `protobuf:"bytes,1,opt,name=invitation_id,json=invitationId,proto3" json:"invitation_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InvitationRevokedEvent) Reset() {
	*x = InvitationRevokedEvent{}
	mi := &file_chatto_core_v1_invitation_events_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InvitationRevokedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvitationRevokedEvent) ProtoMessage() {}

func (x *InvitationRevokedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_core_v1_invitation_events_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvitationRevokedEvent.ProtoReflect.Descriptor instead.
func (*InvitationRevokedEvent) Descriptor() ([]byte, []int) {
	return file_chatto_core_v1_invitation_events_proto_rawDescGZIP(), []int{2}
}

func (x *InvitationRevokedEvent) GetInvitationId() string {
	if x != nil {
		return x.InvitationId
	}
	return ""
}

var File_chatto_core_v1_invitation_events_proto protoreflect.FileDescriptor

const file_chatto_core_v1_invitation_events_proto_rawDesc = "" +
	"\n" +
	"&chatto/core/v1/invitation_events.proto\x12\x0echatto.core.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xa5\x01\n" +
	"\x16InvitationCreatedEvent\x12#\n" +
	"\rinvitation_id\x18\x01 \x01(\tR\finvitationId\x12\x1e\n" +
	"\bmax_uses\x18\x02 \x01(\rH\x00R\amaxUses\x88\x01\x01\x129\n" +
	"\n" +
	"expires_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAtB\v\n" +
	"\t_max_uses\"W\n" +
	"\x17InvitationRedeemedEvent\x12#\n" +
	"\rinvitation_id\x18\x01 \x01(\tR\finvitationId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"=\n" +
	"\x16InvitationRevokedEvent\x12#\n" +
	"\rinvitation_id\x18\x01 \x01(\tR\finvitationIdB\xb8\x01\n" +
	"\x12com.chatto.core.v1B\x15InvitationEventsProtoP\x01Z1hmans.de/chatto/internal/pb/chatto/core/v1;corev1\xa2\x02\x03CCX\xaa\x02\x0eChatto.Core.V1\xca\x02\x0eChatto\\Core\\V1\xe2\x02\x1aChatto\\Core\\V1\\GPBMetadata\xea\x02\x10Chatto::Core::V1b\x06proto3"

var (
	file_chatto_core_v1_invitation_events_proto_rawDescOnce sync.Once
	file_chatto_core_v1_invitation_events_proto_rawDescData []byte
)

func file_chatto_core_v1_invitation_events_proto_rawDescGZIP() []byte {
	file_chatto_core_v1_invitation_events_proto_rawDescOnce.Do(func() {
		file_chatto_core_v1_invitation_events_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_chatto_core_v1_invitation_events_proto_rawDesc), len(file_chatto_core_v1_invitation_events_proto_rawDesc)))
	})
	return file_chatto_core_v1_invitation_events_proto_rawDescData
}

var file_chatto_core_v1_invitation_events_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_chatto_core_v1_invitation_events_proto_goTypes = []any{
	(*InvitationCreatedEvent)(nil),  // 0: chatto.core.v1.InvitationCreatedEvent
	(*InvitationRedeemedEvent)(nil), // 1: chatto.core.v1.InvitationRedeemedEvent
	(*InvitationRevokedEvent)(nil),  // 2: chatto.core.v1.InvitationRevokedEvent
	(*timestamppb.Timestamp)(nil),   // 3: google.protobuf.Timestamp
}
var file_chatto_core_v1_invitation_events_proto_depIdxs = []int32{
	3, // 0: chatto.core.v1.InvitationCreatedEvent.expires_at:type_name -> google.protobuf.Timestamp
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_chatto_core_v1_invitation_events_proto_init() }
func file_chatto_core_v1_invitation_events_proto_init() {
	if File_chatto_core_v1_invitation_events_proto != nil {
		return
	}
	file_chatto_core_v1_invitation_events_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_chatto_core_v1_invitation_events_proto_rawDesc), len(file_chatto_core_v1_invitation_events_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_chatto_core_v1_invitation_events_proto_goTypes,
		DependencyIndexes: file_chatto_core_v1_invitation_events_proto_depIdxs,
		MessageInfos:      file_chatto_core_v1_invitation_events_proto_msgTypes,
	}.Build()
	File_chatto_core_v1_invitation_events_proto = out.File
	file_chatto_core_v1_invitation_events_proto_goTypes = nil
	file_chatto_core_v1_invitation_events_proto_depIdxs = nil
}
