// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: chatto/core/v1/live_events.proto

package corev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// LiveEvent is the wire-format envelope for transient pubsub signals.
// These events are never stored in EVT and are not projection input. They
// are delivered over the live.sync.> subject family and adapted by myEvents
// into public realtime events.
//
// Durable facts belong in Event on the EVT stream. Do not add new transient
// variants to Event.
type LiveEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Universal event identifier (NanoID) for dedupe and client-side idempotency.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// When this live signal was created.
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// ID of the user or system actor that triggered this signal.
	ActorId string `protobuf:"bytes,3,opt,name=actor_id,json=actorId,proto3" json:"actor_id,omitempty"`
	// Types that are valid to be assigned to Event:
	//
	//	*LiveEvent_UserCreated
	//	*LiveEvent_UserDeleted
	//	*LiveEvent_UserProfileUpdated
	//	*LiveEvent_ServerUserPreferencesUpdated
	//	*LiveEvent_NotificationLevelChanged
	//	*LiveEvent_ThreadFollowChanged
	//	*LiveEvent_ServerMemberDeleted
	//	*LiveEvent_ServerUpdated
	//	*LiveEvent_UserTyping
	//	*LiveEvent_PresenceChanged
	//	*LiveEvent_MentionNotification
	//	*LiveEvent_NewDirectMessageNotification
	//	*LiveEvent_CallParticipantJoined
	//	*LiveEvent_CallParticipantLeft
	//	*LiveEvent_NotificationCreated
	//	*LiveEvent_NotificationDismissed
	//	*LiveEvent_RoomMarkedAsRead
	//	*LiveEvent_MentionStatusCleared
	//	*LiveEvent_RoomGroupsUpdated
	//	*LiveEvent_SessionTerminated
	Event         isLiveEvent_Event `protobuf_oneof:"event"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LiveEvent) Reset() {
	*x = LiveEvent{}
	mi := &file_chatto_core_v1_live_events_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LiveEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LiveEvent) ProtoMessage() {}

func (x *LiveEvent) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_core_v1_live_events_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LiveEvent.ProtoReflect.Descriptor instead.
func (*LiveEvent) Descriptor() ([]byte, []int) {
	return file_chatto_core_v1_live_events_proto_rawDescGZIP(), []int{0}
}

func (x *LiveEvent) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *LiveEvent) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *LiveEvent) GetActorId() string {
	if x != nil {
		return x.ActorId
	}
	return ""
}

func (x *LiveEvent) GetEvent() isLiveEvent_Event {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *LiveEvent) GetUserCreated() *UserCreatedEvent {
	if x != nil {
		if x, ok := x.Event.(*LiveEvent_UserCreated); ok {
			return x.UserCreated
		}
	}
	return nil
}

// Deprecated: Marked as deprecated in chatto/core/v1/live_events.proto.
func (x *LiveEvent) GetUserDeleted() *UserDeletedEvent {
	if x != nil {
		if x, ok := x.Event.(*LiveEvent_UserDeleted); ok {
			return x.UserDeleted
		}
	}
	return nil
}

func (x *LiveEvent) GetUserProfileUpdated() *UserProfileUpdatedEvent {
	if x != nil {
		if x, ok := x.Event.(*LiveEvent_UserProfileUpdated); ok {
			return x.UserProfileUpdated
		}
	}
	return nil
}

func (x *LiveEvent) GetServerUserPreferencesUpdated() *ServerUserPreferencesUpdatedEvent {
	if x != nil {
		if x, ok := x.Event.(*LiveEvent_ServerUserPreferencesUpdated); ok {
			return x.ServerUserPreferencesUpdated
		}
	}
	return nil
}

func (x *LiveEvent) GetNotificationLevelChanged() *NotificationLevelChangedEvent {
	if x != nil {
		if x, ok := x.Event.(*LiveEvent_NotificationLevelChanged); ok {
			return x.NotificationLevelChanged
		}
	}
	return nil
}

func (x *LiveEvent) GetThreadFollowChanged() *ThreadFollowChangedEvent {
	if x != nil {
		if x, ok := x.Event.(*LiveEvent_ThreadFollowChanged); ok {
			return x.ThreadFollowChanged
		}
	}
	return nil
}

func (x *LiveEvent) GetServerMemberDeleted() *ServerMemberDeletedEvent {
	if x != nil {
		if x, ok := x.Event.(*LiveEvent_ServerMemberDeleted); ok {
			return x.ServerMemberDeleted
		}
	}
	return nil
}

func (x *LiveEvent) GetServerUpdated() *ServerUpdatedEvent {
	if x != nil {
		if x, ok := x.Event.(*LiveEvent_ServerUpdated); ok {
			return x.ServerUpdated
		}
	}
	return nil
}

func (x *LiveEvent) GetUserTyping() *UserTypingEvent {
	if x != nil {
		if x, ok := x.Event.(*LiveEvent_UserTyping); ok {
			return x.UserTyping
		}
	}
	return nil
}

func (x *LiveEvent) GetPresenceChanged() *PresenceChangedEvent {
	if x != nil {
		if x, ok := x.Event.(*LiveEvent_PresenceChanged); ok {
			return x.PresenceChanged
		}
	}
	return nil
}

func (x *LiveEvent) GetMentionNotification() *MentionNotificationEvent {
	if x != nil {
		if x, ok := x.Event.(*LiveEvent_MentionNotification); ok {
			return x.MentionNotification
		}
	}
	return nil
}

func (x *LiveEvent) GetNewDirectMessageNotification() *NewDirectMessageNotificationEvent {
	if x != nil {
		if x, ok := x.Event.(*LiveEvent_NewDirectMessageNotification); ok {
			return x.NewDirectMessageNotification
		}
	}
	return nil
}

func (x *LiveEvent) GetCallParticipantJoined() *CallParticipantJoinedEvent {
	if x != nil {
		if x, ok := x.Event.(*LiveEvent_CallParticipantJoined); ok {
			return x.CallParticipantJoined
		}
	}
	return nil
}

func (x *LiveEvent) GetCallParticipantLeft() *CallParticipantLeftEvent {
	if x != nil {
		if x, ok := x.Event.(*LiveEvent_CallParticipantLeft); ok {
			return x.CallParticipantLeft
		}
	}
	return nil
}

func (x *LiveEvent) GetNotificationCreated() *NotificationCreatedEvent {
	if x != nil {
		if x, ok := x.Event.(*LiveEvent_NotificationCreated); ok {
			return x.NotificationCreated
		}
	}
	return nil
}

func (x *LiveEvent) GetNotificationDismissed() *NotificationDismissedEvent {
	if x != nil {
		if x, ok := x.Event.(*LiveEvent_NotificationDismissed); ok {
			return x.NotificationDismissed
		}
	}
	return nil
}

func (x *LiveEvent) GetRoomMarkedAsRead() *RoomMarkedAsReadEvent {
	if x != nil {
		if x, ok := x.Event.(*LiveEvent_RoomMarkedAsRead); ok {
			return x.RoomMarkedAsRead
		}
	}
	return nil
}

func (x *LiveEvent) GetMentionStatusCleared() *MentionStatusClearedEvent {
	if x != nil {
		if x, ok := x.Event.(*LiveEvent_MentionStatusCleared); ok {
			return x.MentionStatusCleared
		}
	}
	return nil
}

func (x *LiveEvent) GetRoomGroupsUpdated() *RoomGroupsUpdatedEvent {
	if x != nil {
		if x, ok := x.Event.(*LiveEvent_RoomGroupsUpdated); ok {
			return x.RoomGroupsUpdated
		}
	}
	return nil
}

func (x *LiveEvent) GetSessionTerminated() *SessionTerminatedEvent {
	if x != nil {
		if x, ok := x.Event.(*LiveEvent_SessionTerminated); ok {
			return x.SessionTerminated
		}
	}
	return nil
}

type isLiveEvent_Event interface {
	isLiveEvent_Event()
}

type LiveEvent_UserCreated struct {
	// ----- User lifecycle / preferences -----
	UserCreated *UserCreatedEvent `protobuf:"bytes,20,opt,name=user_created,json=userCreated,proto3,oneof"`
}

type LiveEvent_UserDeleted struct {
	// Deprecated. Account deletion no longer publishes this transient signal;
	// clients receive session_terminated for the deleted user's own sessions and
	// server_member_deleted for server-wide invalidation.
	//
	// Deprecated: Marked as deprecated in chatto/core/v1/live_events.proto.
	UserDeleted *UserDeletedEvent `protobuf:"bytes,21,opt,name=user_deleted,json=userDeleted,proto3,oneof"`
}

type LiveEvent_UserProfileUpdated struct {
	UserProfileUpdated *UserProfileUpdatedEvent `protobuf:"bytes,22,opt,name=user_profile_updated,json=userProfileUpdated,proto3,oneof"`
}

type LiveEvent_ServerUserPreferencesUpdated struct {
	ServerUserPreferencesUpdated *ServerUserPreferencesUpdatedEvent `protobuf:"bytes,23,opt,name=server_user_preferences_updated,json=serverUserPreferencesUpdated,proto3,oneof"`
}

type LiveEvent_NotificationLevelChanged struct {
	NotificationLevelChanged *NotificationLevelChangedEvent `protobuf:"bytes,24,opt,name=notification_level_changed,json=notificationLevelChanged,proto3,oneof"`
}

type LiveEvent_ThreadFollowChanged struct {
	ThreadFollowChanged *ThreadFollowChangedEvent `protobuf:"bytes,25,opt,name=thread_follow_changed,json=threadFollowChanged,proto3,oneof"`
}

type LiveEvent_ServerMemberDeleted struct {
	// ----- Server membership / lifecycle -----
	ServerMemberDeleted *ServerMemberDeletedEvent `protobuf:"bytes,30,opt,name=server_member_deleted,json=serverMemberDeleted,proto3,oneof"`
}

type LiveEvent_ServerUpdated struct {
	ServerUpdated *ServerUpdatedEvent `protobuf:"bytes,31,opt,name=server_updated,json=serverUpdated,proto3,oneof"`
}

type LiveEvent_UserTyping struct {
	// ----- Typing -----
	UserTyping *UserTypingEvent `protobuf:"bytes,40,opt,name=user_typing,json=userTyping,proto3,oneof"`
}

type LiveEvent_PresenceChanged struct {
	// ----- Presence -----
	PresenceChanged *PresenceChangedEvent `protobuf:"bytes,45,opt,name=presence_changed,json=presenceChanged,proto3,oneof"`
}

type LiveEvent_MentionNotification struct {
	// ----- Notifications -----
	MentionNotification *MentionNotificationEvent `protobuf:"bytes,50,opt,name=mention_notification,json=mentionNotification,proto3,oneof"`
}

type LiveEvent_NewDirectMessageNotification struct {
	NewDirectMessageNotification *NewDirectMessageNotificationEvent `protobuf:"bytes,51,opt,name=new_direct_message_notification,json=newDirectMessageNotification,proto3,oneof"`
}

type LiveEvent_CallParticipantJoined struct {
	// ----- Voice calls -----
	CallParticipantJoined *CallParticipantJoinedEvent `protobuf:"bytes,60,opt,name=call_participant_joined,json=callParticipantJoined,proto3,oneof"`
}

type LiveEvent_CallParticipantLeft struct {
	CallParticipantLeft *CallParticipantLeftEvent `protobuf:"bytes,61,opt,name=call_participant_left,json=callParticipantLeft,proto3,oneof"`
}

type LiveEvent_NotificationCreated struct {
	// ----- Notification sync -----
	NotificationCreated *NotificationCreatedEvent `protobuf:"bytes,70,opt,name=notification_created,json=notificationCreated,proto3,oneof"`
}

type LiveEvent_NotificationDismissed struct {
	NotificationDismissed *NotificationDismissedEvent `protobuf:"bytes,71,opt,name=notification_dismissed,json=notificationDismissed,proto3,oneof"`
}

type LiveEvent_RoomMarkedAsRead struct {
	// ----- Unread indicators -----
	RoomMarkedAsRead *RoomMarkedAsReadEvent `protobuf:"bytes,80,opt,name=room_marked_as_read,json=roomMarkedAsRead,proto3,oneof"`
}

type LiveEvent_MentionStatusCleared struct {
	MentionStatusCleared *MentionStatusClearedEvent `protobuf:"bytes,81,opt,name=mention_status_cleared,json=mentionStatusCleared,proto3,oneof"`
}

type LiveEvent_RoomGroupsUpdated struct {
	// ----- Room layout -----
	RoomGroupsUpdated *RoomGroupsUpdatedEvent `protobuf:"bytes,90,opt,name=room_groups_updated,json=roomGroupsUpdated,proto3,oneof"`
}

type LiveEvent_SessionTerminated struct {
	// ----- Session termination -----
	SessionTerminated *SessionTerminatedEvent `protobuf:"bytes,100,opt,name=session_terminated,json=sessionTerminated,proto3,oneof"`
}

func (*LiveEvent_UserCreated) isLiveEvent_Event() {}

func (*LiveEvent_UserDeleted) isLiveEvent_Event() {}

func (*LiveEvent_UserProfileUpdated) isLiveEvent_Event() {}

func (*LiveEvent_ServerUserPreferencesUpdated) isLiveEvent_Event() {}

func (*LiveEvent_NotificationLevelChanged) isLiveEvent_Event() {}

func (*LiveEvent_ThreadFollowChanged) isLiveEvent_Event() {}

func (*LiveEvent_ServerMemberDeleted) isLiveEvent_Event() {}

func (*LiveEvent_ServerUpdated) isLiveEvent_Event() {}

func (*LiveEvent_UserTyping) isLiveEvent_Event() {}

func (*LiveEvent_PresenceChanged) isLiveEvent_Event() {}

func (*LiveEvent_MentionNotification) isLiveEvent_Event() {}

func (*LiveEvent_NewDirectMessageNotification) isLiveEvent_Event() {}

func (*LiveEvent_CallParticipantJoined) isLiveEvent_Event() {}

func (*LiveEvent_CallParticipantLeft) isLiveEvent_Event() {}

func (*LiveEvent_NotificationCreated) isLiveEvent_Event() {}

func (*LiveEvent_NotificationDismissed) isLiveEvent_Event() {}

func (*LiveEvent_RoomMarkedAsRead) isLiveEvent_Event() {}

func (*LiveEvent_MentionStatusCleared) isLiveEvent_Event() {}

func (*LiveEvent_RoomGroupsUpdated) isLiveEvent_Event() {}

func (*LiveEvent_SessionTerminated) isLiveEvent_Event() {}

// HeartbeatEvent is a synthetic event with no payload. StreamMyEvents
// emits one every ~15 seconds so clients can detect a dead subscription
// on an otherwise-healthy WebSocket. It is never persisted and never
// travels over NATS.
type HeartbeatEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatEvent) Reset() {
	*x = HeartbeatEvent{}
	mi := &file_chatto_core_v1_live_events_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatEvent) ProtoMessage() {}

func (x *HeartbeatEvent) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_core_v1_live_events_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatEvent.ProtoReflect.Descriptor instead.
func (*HeartbeatEvent) Descriptor() ([]byte, []int) {
	return file_chatto_core_v1_live_events_proto_rawDescGZIP(), []int{1}
}

// NotificationLevelChangedEvent is published when a user changes their notification
// level for the server or a specific room. User-scoped: only delivered to the user
// who changed it.
type NotificationLevelChangedEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The room whose notification level was changed (empty for server-level changes).
	RoomId string `protobuf:"bytes,2,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	// The explicitly set level.
	Level NotificationLevel `protobuf:"varint,3,opt,name=level,proto3,enum=chatto.core.v1.NotificationLevel" json:"level,omitempty"`
	// The effective level after inheritance resolution.
	EffectiveLevel NotificationLevel `protobuf:"varint,4,opt,name=effective_level,json=effectiveLevel,proto3,enum=chatto.core.v1.NotificationLevel" json:"effective_level,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *NotificationLevelChangedEvent) Reset() {
	*x = NotificationLevelChangedEvent{}
	mi := &file_chatto_core_v1_live_events_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotificationLevelChangedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotificationLevelChangedEvent) ProtoMessage() {}

func (x *NotificationLevelChangedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_core_v1_live_events_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotificationLevelChangedEvent.ProtoReflect.Descriptor instead.
func (*NotificationLevelChangedEvent) Descriptor() ([]byte, []int) {
	return file_chatto_core_v1_live_events_proto_rawDescGZIP(), []int{2}
}

func (x *NotificationLevelChangedEvent) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *NotificationLevelChangedEvent) GetLevel() NotificationLevel {
	if x != nil {
		return x.Level
	}
	return NotificationLevel_NOTIFICATION_LEVEL_UNSPECIFIED
}

func (x *NotificationLevelChangedEvent) GetEffectiveLevel() NotificationLevel {
	if x != nil {
		return x.EffectiveLevel
	}
	return NotificationLevel_NOTIFICATION_LEVEL_UNSPECIFIED
}

type ServerUpdatedEvent struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	ServerId    string                 `protobuf:"bytes,1,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	Name        string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	// URL to the server's logo, or empty if no logo is set.
	LogoUrl string `protobuf:"bytes,4,opt,name=logo_url,json=logoUrl,proto3" json:"logo_url,omitempty"`
	// URL to the server's banner, or empty if no banner is set.
	BannerUrl     string `protobuf:"bytes,5,opt,name=banner_url,json=bannerUrl,proto3" json:"banner_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerUpdatedEvent) Reset() {
	*x = ServerUpdatedEvent{}
	mi := &file_chatto_core_v1_live_events_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerUpdatedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerUpdatedEvent) ProtoMessage() {}

func (x *ServerUpdatedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_core_v1_live_events_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerUpdatedEvent.ProtoReflect.Descriptor instead.
func (*ServerUpdatedEvent) Descriptor() ([]byte, []int) {
	return file_chatto_core_v1_live_events_proto_rawDescGZIP(), []int{3}
}

func (x *ServerUpdatedEvent) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

func (x *ServerUpdatedEvent) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ServerUpdatedEvent) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ServerUpdatedEvent) GetLogoUrl() string {
	if x != nil {
		return x.LogoUrl
	}
	return ""
}

func (x *ServerUpdatedEvent) GetBannerUrl() string {
	if x != nil {
		return x.BannerUrl
	}
	return ""
}

// Notifies clients that a user is typing in a room or thread.
// Published directly to NATS Core (bypasses JetStream storage).
// Clients should implement timeout-based clearing (e.g., 6 seconds).
type UserTypingEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Room ID where the user is typing
	RoomId string `protobuf:"bytes,2,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	// Thread root event ID (optional). If set, the user is typing a reply in this thread.
	// If empty, the user is typing in the main room view.
	ThreadRootEventId *string `protobuf:"bytes,3,opt,name=thread_root_event_id,json=threadRootEventId,proto3,oneof" json:"thread_root_event_id,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *UserTypingEvent) Reset() {
	*x = UserTypingEvent{}
	mi := &file_chatto_core_v1_live_events_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserTypingEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserTypingEvent) ProtoMessage() {}

func (x *UserTypingEvent) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_core_v1_live_events_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserTypingEvent.ProtoReflect.Descriptor instead.
func (*UserTypingEvent) Descriptor() ([]byte, []int) {
	return file_chatto_core_v1_live_events_proto_rawDescGZIP(), []int{4}
}

func (x *UserTypingEvent) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *UserTypingEvent) GetThreadRootEventId() string {
	if x != nil && x.ThreadRootEventId != nil {
		return *x.ThreadRootEventId
	}
	return ""
}

// Notifies clients that a user's presence status changed.
// Published when a user comes online, goes offline, or changes their status.
// The user whose presence changed is identified by the parent envelope's actor_id.
// Presence is server-wide; the server context is implicit in the subscription.
type PresenceChangedEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The user's new presence status ("ONLINE", "OFFLINE", "AWAY", "DO_NOT_DISTURB")
	Status        string `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PresenceChangedEvent) Reset() {
	*x = PresenceChangedEvent{}
	mi := &file_chatto_core_v1_live_events_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PresenceChangedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PresenceChangedEvent) ProtoMessage() {}

func (x *PresenceChangedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_core_v1_live_events_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PresenceChangedEvent.ProtoReflect.Descriptor instead.
func (*PresenceChangedEvent) Descriptor() ([]byte, []int) {
	return file_chatto_core_v1_live_events_proto_rawDescGZIP(), []int{5}
}

func (x *PresenceChangedEvent) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

// Notifies a user that they were mentioned in a message.
// Published as a server-scoped live event to the mentioned user.
// This is a transient notification — the KV bucket tracks persistent state.
type MentionNotificationEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Room ID where the mention occurred
	RoomId string `protobuf:"bytes,2,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	// User ID of the person who mentioned them (the message author)
	MentionedByUserId string `protobuf:"bytes,3,opt,name=mentioned_by_user_id,json=mentionedByUserId,proto3" json:"mentioned_by_user_id,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *MentionNotificationEvent) Reset() {
	*x = MentionNotificationEvent{}
	mi := &file_chatto_core_v1_live_events_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MentionNotificationEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MentionNotificationEvent) ProtoMessage() {}

func (x *MentionNotificationEvent) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_core_v1_live_events_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MentionNotificationEvent.ProtoReflect.Descriptor instead.
func (*MentionNotificationEvent) Descriptor() ([]byte, []int) {
	return file_chatto_core_v1_live_events_proto_rawDescGZIP(), []int{6}
}

func (x *MentionNotificationEvent) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *MentionNotificationEvent) GetMentionedByUserId() string {
	if x != nil {
		return x.MentionedByUserId
	}
	return ""
}

// Notifies a user that a new message was posted in a DM conversation they're part of.
// Published as a server-scoped live event to all participants except the sender.
// Every DM message triggers this notification (unlike mentions which are opt-in).
type NewDirectMessageNotificationEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Room ID of the DM conversation
	RoomId string `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	// User ID of the person who sent the message
	SenderId      string `protobuf:"bytes,2,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NewDirectMessageNotificationEvent) Reset() {
	*x = NewDirectMessageNotificationEvent{}
	mi := &file_chatto_core_v1_live_events_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NewDirectMessageNotificationEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewDirectMessageNotificationEvent) ProtoMessage() {}

func (x *NewDirectMessageNotificationEvent) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_core_v1_live_events_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewDirectMessageNotificationEvent.ProtoReflect.Descriptor instead.
func (*NewDirectMessageNotificationEvent) Descriptor() ([]byte, []int) {
	return file_chatto_core_v1_live_events_proto_rawDescGZIP(), []int{7}
}

func (x *NewDirectMessageNotificationEvent) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *NewDirectMessageNotificationEvent) GetSenderId() string {
	if x != nil {
		return x.SenderId
	}
	return ""
}

// Published when a new notification is created for a user.
// Enables real-time notification updates in the UI.
type NotificationCreatedEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The notification ID
	NotificationId string `protobuf:"bytes,1,opt,name=notification_id,json=notificationId,proto3" json:"notification_id,omitempty"`
	// Navigation context (optional fields for routing)
	RoomId      string `protobuf:"bytes,3,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	EventId     string `protobuf:"bytes,4,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	InReplyToId string `protobuf:"bytes,5,opt,name=in_reply_to_id,json=inReplyToId,proto3" json:"in_reply_to_id,omitempty"`
	// True when clients should update notification state without playing a local
	// alert sound. Used for Do Not Disturb delivery.
	Silent        bool `protobuf:"varint,6,opt,name=silent,proto3" json:"silent,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotificationCreatedEvent) Reset() {
	*x = NotificationCreatedEvent{}
	mi := &file_chatto_core_v1_live_events_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotificationCreatedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotificationCreatedEvent) ProtoMessage() {}

func (x *NotificationCreatedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_core_v1_live_events_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotificationCreatedEvent.ProtoReflect.Descriptor instead.
func (*NotificationCreatedEvent) Descriptor() ([]byte, []int) {
	return file_chatto_core_v1_live_events_proto_rawDescGZIP(), []int{8}
}

func (x *NotificationCreatedEvent) GetNotificationId() string {
	if x != nil {
		return x.NotificationId
	}
	return ""
}

func (x *NotificationCreatedEvent) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *NotificationCreatedEvent) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *NotificationCreatedEvent) GetInReplyToId() string {
	if x != nil {
		return x.InReplyToId
	}
	return ""
}

func (x *NotificationCreatedEvent) GetSilent() bool {
	if x != nil {
		return x.Silent
	}
	return false
}

// Published when a notification is dismissed by the user.
// Enables cross-device sync of dismissed notifications.
type NotificationDismissedEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The dismissed notification ID
	NotificationId string `protobuf:"bytes,1,opt,name=notification_id,json=notificationId,proto3" json:"notification_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *NotificationDismissedEvent) Reset() {
	*x = NotificationDismissedEvent{}
	mi := &file_chatto_core_v1_live_events_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotificationDismissedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotificationDismissedEvent) ProtoMessage() {}

func (x *NotificationDismissedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_core_v1_live_events_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotificationDismissedEvent.ProtoReflect.Descriptor instead.
func (*NotificationDismissedEvent) Descriptor() ([]byte, []int) {
	return file_chatto_core_v1_live_events_proto_rawDescGZIP(), []int{9}
}

func (x *NotificationDismissedEvent) GetNotificationId() string {
	if x != nil {
		return x.NotificationId
	}
	return ""
}

// ThreadFollowChangedEvent invalidates one user's viewer-specific thread state.
// It is published for follow/unfollow and read-marker changes and is user-scoped
// for multi-tab/multi-device projection convergence.
type ThreadFollowChangedEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The room containing the thread.
	RoomId string `protobuf:"bytes,2,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	// The root event ID of the thread.
	ThreadRootEventId string `protobuf:"bytes,3,opt,name=thread_root_event_id,json=threadRootEventId,proto3" json:"thread_root_event_id,omitempty"`
	// Whether the user is now following (true) or not following (false).
	IsFollowing   bool `protobuf:"varint,4,opt,name=is_following,json=isFollowing,proto3" json:"is_following,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ThreadFollowChangedEvent) Reset() {
	*x = ThreadFollowChangedEvent{}
	mi := &file_chatto_core_v1_live_events_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ThreadFollowChangedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ThreadFollowChangedEvent) ProtoMessage() {}

func (x *ThreadFollowChangedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_core_v1_live_events_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ThreadFollowChangedEvent.ProtoReflect.Descriptor instead.
func (*ThreadFollowChangedEvent) Descriptor() ([]byte, []int) {
	return file_chatto_core_v1_live_events_proto_rawDescGZIP(), []int{10}
}

func (x *ThreadFollowChangedEvent) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *ThreadFollowChangedEvent) GetThreadRootEventId() string {
	if x != nil {
		return x.ThreadRootEventId
	}
	return ""
}

func (x *ThreadFollowChangedEvent) GetIsFollowing() bool {
	if x != nil {
		return x.IsFollowing
	}
	return false
}

// Published to the user who marked a room as read. This enables real-time
// updates to other tabs/devices for the same user.
type RoomMarkedAsReadEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Room ID that was marked as read
	RoomId        string `protobuf:"bytes,2,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoomMarkedAsReadEvent) Reset() {
	*x = RoomMarkedAsReadEvent{}
	mi := &file_chatto_core_v1_live_events_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoomMarkedAsReadEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomMarkedAsReadEvent) ProtoMessage() {}

func (x *RoomMarkedAsReadEvent) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_core_v1_live_events_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomMarkedAsReadEvent.ProtoReflect.Descriptor instead.
func (*RoomMarkedAsReadEvent) Descriptor() ([]byte, []int) {
	return file_chatto_core_v1_live_events_proto_rawDescGZIP(), []int{11}
}

func (x *RoomMarkedAsReadEvent) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

// Published to the user whose mention indicator for a room was cleared.
// Fires whenever the server-side mention KV flag (`room_mention_status.*`) is
// deleted — that happens when the user marks a room as read (auto on entry or
// explicit) or dismisses a mention notification on any device. Other devices
// use this to drop the orange dot for the room without waiting for a refetch.
type MentionStatusClearedEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Room ID whose mention indicator was cleared
	RoomId        string `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MentionStatusClearedEvent) Reset() {
	*x = MentionStatusClearedEvent{}
	mi := &file_chatto_core_v1_live_events_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MentionStatusClearedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MentionStatusClearedEvent) ProtoMessage() {}

func (x *MentionStatusClearedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_core_v1_live_events_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MentionStatusClearedEvent.ProtoReflect.Descriptor instead.
func (*MentionStatusClearedEvent) Descriptor() ([]byte, []int) {
	return file_chatto_core_v1_live_events_proto_rawDescGZIP(), []int{12}
}

func (x *MentionStatusClearedEvent) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

// Notifies clients that the channel-room groups (their ordering, names,
// or membership) were updated. Clients should refetch `Server.roomGroups`.
// Published as a live server event (not stored in JetStream).
type RoomGroupsUpdatedEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoomGroupsUpdatedEvent) Reset() {
	*x = RoomGroupsUpdatedEvent{}
	mi := &file_chatto_core_v1_live_events_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoomGroupsUpdatedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomGroupsUpdatedEvent) ProtoMessage() {}

func (x *RoomGroupsUpdatedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_core_v1_live_events_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomGroupsUpdatedEvent.ProtoReflect.Descriptor instead.
func (*RoomGroupsUpdatedEvent) Descriptor() ([]byte, []int) {
	return file_chatto_core_v1_live_events_proto_rawDescGZIP(), []int{13}
}

// Notifies a user that their session has been terminated.
// Published as a user-scoped event on logout or admin boot.
// The subscription handler closes the stream after forwarding this event,
// ensuring the WebSocket connection is torn down server-side.
type SessionTerminatedEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Reason for termination: "logout", "admin_boot", "account_deleted"
	Reason        string `protobuf:"bytes,1,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionTerminatedEvent) Reset() {
	*x = SessionTerminatedEvent{}
	mi := &file_chatto_core_v1_live_events_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionTerminatedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionTerminatedEvent) ProtoMessage() {}

func (x *SessionTerminatedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_core_v1_live_events_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionTerminatedEvent.ProtoReflect.Descriptor instead.
func (*SessionTerminatedEvent) Descriptor() ([]byte, []int) {
	return file_chatto_core_v1_live_events_proto_rawDescGZIP(), []int{14}
}

func (x *SessionTerminatedEvent) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

var File_chatto_core_v1_live_events_proto protoreflect.FileDescriptor

const file_chatto_core_v1_live_events_proto_rawDesc = "" +
	"\n" +
	" chatto/core/v1/live_events.proto\x12\x0echatto.core.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a chatto/core/v1/room_events.proto\x1a chatto/core/v1/user_events.proto\x1a%chatto/core/v1/user_preferences.proto\"\x83\x10\n" +
	"\tLiveEvent\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x129\n" +
	"\n" +
	"created_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12\x19\n" +
	"\bactor_id\x18\x03 \x01(\tR\aactorId\x12E\n" +
	"\fuser_created\x18\x14 \x01(\v2 .chatto.core.v1.UserCreatedEventH\x00R\vuserCreated\x12I\n" +
	"\fuser_deleted\x18\x15 \x01(\v2 .chatto.core.v1.UserDeletedEventB\x02\x18\x01H\x00R\vuserDeleted\x12[\n" +
	"\x14user_profile_updated\x18\x16 \x01(\v2'.chatto.core.v1.UserProfileUpdatedEventH\x00R\x12userProfileUpdated\x12z\n" +
	"\x1fserver_user_preferences_updated\x18\x17 \x01(\v21.chatto.core.v1.ServerUserPreferencesUpdatedEventH\x00R\x1cserverUserPreferencesUpdated\x12m\n" +
	"\x1anotification_level_changed\x18\x18 \x01(\v2-.chatto.core.v1.NotificationLevelChangedEventH\x00R\x18notificationLevelChanged\x12^\n" +
	"\x15thread_follow_changed\x18\x19 \x01(\v2(.chatto.core.v1.ThreadFollowChangedEventH\x00R\x13threadFollowChanged\x12^\n" +
	"\x15server_member_deleted\x18\x1e \x01(\v2(.chatto.core.v1.ServerMemberDeletedEventH\x00R\x13serverMemberDeleted\x12K\n" +
	"\x0eserver_updated\x18\x1f \x01(\v2\".chatto.core.v1.ServerUpdatedEventH\x00R\rserverUpdated\x12B\n" +
	"\vuser_typing\x18( \x01(\v2\x1f.chatto.core.v1.UserTypingEventH\x00R\n" +
	"userTyping\x12Q\n" +
	"\x10presence_changed\x18- \x01(\v2$.chatto.core.v1.PresenceChangedEventH\x00R\x0fpresenceChanged\x12]\n" +
	"\x14mention_notification\x182 \x01(\v2(.chatto.core.v1.MentionNotificationEventH\x00R\x13mentionNotification\x12z\n" +
	"\x1fnew_direct_message_notification\x183 \x01(\v21.chatto.core.v1.NewDirectMessageNotificationEventH\x00R\x1cnewDirectMessageNotification\x12d\n" +
	"\x17call_participant_joined\x18< \x01(\v2*.chatto.core.v1.CallParticipantJoinedEventH\x00R\x15callParticipantJoined\x12^\n" +
	"\x15call_participant_left\x18= \x01(\v2(.chatto.core.v1.CallParticipantLeftEventH\x00R\x13callParticipantLeft\x12]\n" +
	"\x14notification_created\x18F \x01(\v2(.chatto.core.v1.NotificationCreatedEventH\x00R\x13notificationCreated\x12c\n" +
	"\x16notification_dismissed\x18G \x01(\v2*.chatto.core.v1.NotificationDismissedEventH\x00R\x15notificationDismissed\x12V\n" +
	"\x13room_marked_as_read\x18P \x01(\v2%.chatto.core.v1.RoomMarkedAsReadEventH\x00R\x10roomMarkedAsRead\x12a\n" +
	"\x16mention_status_cleared\x18Q \x01(\v2).chatto.core.v1.MentionStatusClearedEventH\x00R\x14mentionStatusCleared\x12X\n" +
	"\x13room_groups_updated\x18Z \x01(\v2&.chatto.core.v1.RoomGroupsUpdatedEventH\x00R\x11roomGroupsUpdated\x12W\n" +
	"\x12session_terminated\x18d \x01(\v2&.chatto.core.v1.SessionTerminatedEventH\x00R\x11sessionTerminatedB\a\n" +
	"\x05eventJ\x04\b\n" +
	"\x10\vJ\x04\b)\x10*R\x0econfig_updatedR\x1avideo_processing_completed\"\x10\n" +
	"\x0eHeartbeatEvent\"\xcd\x01\n" +
	"\x1dNotificationLevelChangedEvent\x12\x17\n" +
	"\aroom_id\x18\x02 \x01(\tR\x06roomId\x127\n" +
	"\x05level\x18\x03 \x01(\x0e2!.chatto.core.v1.NotificationLevelR\x05level\x12J\n" +
	"\x0feffective_level\x18\x04 \x01(\x0e2!.chatto.core.v1.NotificationLevelR\x0eeffectiveLevelJ\x04\b\x01\x10\x02R\bspace_id\"\xa1\x01\n" +
	"\x12ServerUpdatedEvent\x12\x1b\n" +
	"\tserver_id\x18\x01 \x01(\tR\bserverId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x19\n" +
	"\blogo_url\x18\x04 \x01(\tR\alogoUrl\x12\x1d\n" +
	"\n" +
	"banner_url\x18\x05 \x01(\tR\tbannerUrl\"\x89\x01\n" +
	"\x0fUserTypingEvent\x12\x17\n" +
	"\aroom_id\x18\x02 \x01(\tR\x06roomId\x124\n" +
	"\x14thread_root_event_id\x18\x03 \x01(\tH\x00R\x11threadRootEventId\x88\x01\x01B\x17\n" +
	"\x15_thread_root_event_idJ\x04\b\x01\x10\x02R\bspace_id\".\n" +
	"\x14PresenceChangedEvent\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\"t\n" +
	"\x18MentionNotificationEvent\x12\x17\n" +
	"\aroom_id\x18\x02 \x01(\tR\x06roomId\x12/\n" +
	"\x14mentioned_by_user_id\x18\x03 \x01(\tR\x11mentionedByUserIdJ\x04\b\x01\x10\x02R\bspace_id\"Y\n" +
	"!NewDirectMessageNotificationEvent\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\x12\x1b\n" +
	"\tsender_id\x18\x02 \x01(\tR\bsenderId\"\xc4\x01\n" +
	"\x18NotificationCreatedEvent\x12'\n" +
	"\x0fnotification_id\x18\x01 \x01(\tR\x0enotificationId\x12\x17\n" +
	"\aroom_id\x18\x03 \x01(\tR\x06roomId\x12\x19\n" +
	"\bevent_id\x18\x04 \x01(\tR\aeventId\x12#\n" +
	"\x0ein_reply_to_id\x18\x05 \x01(\tR\vinReplyToId\x12\x16\n" +
	"\x06silent\x18\x06 \x01(\bR\x06silentJ\x04\b\x02\x10\x03R\bspace_id\"E\n" +
	"\x1aNotificationDismissedEvent\x12'\n" +
	"\x0fnotification_id\x18\x01 \x01(\tR\x0enotificationId\"\x97\x01\n" +
	"\x18ThreadFollowChangedEvent\x12\x17\n" +
	"\aroom_id\x18\x02 \x01(\tR\x06roomId\x12/\n" +
	"\x14thread_root_event_id\x18\x03 \x01(\tR\x11threadRootEventId\x12!\n" +
	"\fis_following\x18\x04 \x01(\bR\visFollowingJ\x04\b\x01\x10\x02R\bspace_id\"@\n" +
	"\x15RoomMarkedAsReadEvent\x12\x17\n" +
	"\aroom_id\x18\x02 \x01(\tR\x06roomIdJ\x04\b\x01\x10\x02R\bspace_id\"4\n" +
	"\x19MentionStatusClearedEvent\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\"(\n" +
	"\x16RoomGroupsUpdatedEventJ\x04\b\x01\x10\x02R\bspace_id\"0\n" +
	"\x16SessionTerminatedEvent\x12\x16\n" +
	"\x06reason\x18\x01 \x01(\tR\x06reasonB\xb2\x01\n" +
	"\x12com.chatto.core.v1B\x0fLiveEventsProtoP\x01Z1hmans.de/chatto/internal/pb/chatto/core/v1;corev1\xa2\x02\x03CCX\xaa\x02\x0eChatto.Core.V1\xca\x02\x0eChatto\\Core\\V1\xe2\x02\x1aChatto\\Core\\V1\\GPBMetadata\xea\x02\x10Chatto::Core::V1b\x06proto3"

var (
	file_chatto_core_v1_live_events_proto_rawDescOnce sync.Once
	file_chatto_core_v1_live_events_proto_rawDescData []byte
)

func file_chatto_core_v1_live_events_proto_rawDescGZIP() []byte {
	file_chatto_core_v1_live_events_proto_rawDescOnce.Do(func() {
		file_chatto_core_v1_live_events_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_chatto_core_v1_live_events_proto_rawDesc), len(file_chatto_core_v1_live_events_proto_rawDesc)))
	})
	return file_chatto_core_v1_live_events_proto_rawDescData
}

var file_chatto_core_v1_live_events_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_chatto_core_v1_live_events_proto_goTypes = []any{
	(*LiveEvent)(nil),                         // 0: chatto.core.v1.LiveEvent
	(*HeartbeatEvent)(nil),                    // 1: chatto.core.v1.HeartbeatEvent
	(*NotificationLevelChangedEvent)(nil),     // 2: chatto.core.v1.NotificationLevelChangedEvent
	(*ServerUpdatedEvent)(nil),                // 3: chatto.core.v1.ServerUpdatedEvent
	(*UserTypingEvent)(nil),                   // 4: chatto.core.v1.UserTypingEvent
	(*PresenceChangedEvent)(nil),              // 5: chatto.core.v1.PresenceChangedEvent
	(*MentionNotificationEvent)(nil),          // 6: chatto.core.v1.MentionNotificationEvent
	(*NewDirectMessageNotificationEvent)(nil), // 7: chatto.core.v1.NewDirectMessageNotificationEvent
	(*NotificationCreatedEvent)(nil),          // 8: chatto.core.v1.NotificationCreatedEvent
	(*NotificationDismissedEvent)(nil),        // 9: chatto.core.v1.NotificationDismissedEvent
	(*ThreadFollowChangedEvent)(nil),          // 10: chatto.core.v1.ThreadFollowChangedEvent
	(*RoomMarkedAsReadEvent)(nil),             // 11: chatto.core.v1.RoomMarkedAsReadEvent
	(*MentionStatusClearedEvent)(nil),         // 12: chatto.core.v1.MentionStatusClearedEvent
	(*RoomGroupsUpdatedEvent)(nil),            // 13: chatto.core.v1.RoomGroupsUpdatedEvent
	(*SessionTerminatedEvent)(nil),            // 14: chatto.core.v1.SessionTerminatedEvent
	(*timestamppb.Timestamp)(nil),             // 15: google.protobuf.Timestamp
	(*UserCreatedEvent)(nil),                  // 16: chatto.core.v1.UserCreatedEvent
	(*UserDeletedEvent)(nil),                  // 17: chatto.core.v1.UserDeletedEvent
	(*UserProfileUpdatedEvent)(nil),           // 18: chatto.core.v1.UserProfileUpdatedEvent
	(*ServerUserPreferencesUpdatedEvent)(nil), // 19: chatto.core.v1.ServerUserPreferencesUpdatedEvent
	(*ServerMemberDeletedEvent)(nil),          // 20: chatto.core.v1.ServerMemberDeletedEvent
	(*CallParticipantJoinedEvent)(nil),        // 21: chatto.core.v1.CallParticipantJoinedEvent
	(*CallParticipantLeftEvent)(nil),          // 22: chatto.core.v1.CallParticipantLeftEvent
	(NotificationLevel)(0),                    // 23: chatto.core.v1.NotificationLevel
}
var file_chatto_core_v1_live_events_proto_depIdxs = []int32{
	15, // 0: chatto.core.v1.LiveEvent.created_at:type_name -> google.protobuf.Timestamp
	16, // 1: chatto.core.v1.LiveEvent.user_created:type_name -> chatto.core.v1.UserCreatedEvent
	17, // 2: chatto.core.v1.LiveEvent.user_deleted:type_name -> chatto.core.v1.UserDeletedEvent
	18, // 3: chatto.core.v1.LiveEvent.user_profile_updated:type_name -> chatto.core.v1.UserProfileUpdatedEvent
	19, // 4: chatto.core.v1.LiveEvent.server_user_preferences_updated:type_name -> chatto.core.v1.ServerUserPreferencesUpdatedEvent
	2,  // 5: chatto.core.v1.LiveEvent.notification_level_changed:type_name -> chatto.core.v1.NotificationLevelChangedEvent
	10, // 6: chatto.core.v1.LiveEvent.thread_follow_changed:type_name -> chatto.core.v1.ThreadFollowChangedEvent
	20, // 7: chatto.core.v1.LiveEvent.server_member_deleted:type_name -> chatto.core.v1.ServerMemberDeletedEvent
	3,  // 8: chatto.core.v1.LiveEvent.server_updated:type_name -> chatto.core.v1.ServerUpdatedEvent
	4,  // 9: chatto.core.v1.LiveEvent.user_typing:type_name -> chatto.core.v1.UserTypingEvent
	5,  // 10: chatto.core.v1.LiveEvent.presence_changed:type_name -> chatto.core.v1.PresenceChangedEvent
	6,  // 11: chatto.core.v1.LiveEvent.mention_notification:type_name -> chatto.core.v1.MentionNotificationEvent
	7,  // 12: chatto.core.v1.LiveEvent.new_direct_message_notification:type_name -> chatto.core.v1.NewDirectMessageNotificationEvent
	21, // 13: chatto.core.v1.LiveEvent.call_participant_joined:type_name -> chatto.core.v1.CallParticipantJoinedEvent
	22, // 14: chatto.core.v1.LiveEvent.call_participant_left:type_name -> chatto.core.v1.CallParticipantLeftEvent
	8,  // 15: chatto.core.v1.LiveEvent.notification_created:type_name -> chatto.core.v1.NotificationCreatedEvent
	9,  // 16: chatto.core.v1.LiveEvent.notification_dismissed:type_name -> chatto.core.v1.NotificationDismissedEvent
	11, // 17: chatto.core.v1.LiveEvent.room_marked_as_read:type_name -> chatto.core.v1.RoomMarkedAsReadEvent
	12, // 18: chatto.core.v1.LiveEvent.mention_status_cleared:type_name -> chatto.core.v1.MentionStatusClearedEvent
	13, // 19: chatto.core.v1.LiveEvent.room_groups_updated:type_name -> chatto.core.v1.RoomGroupsUpdatedEvent
	14, // 20: chatto.core.v1.LiveEvent.session_terminated:type_name -> chatto.core.v1.SessionTerminatedEvent
	23, // 21: chatto.core.v1.NotificationLevelChangedEvent.level:type_name -> chatto.core.v1.NotificationLevel
	23, // 22: chatto.core.v1.NotificationLevelChangedEvent.effective_level:type_name -> chatto.core.v1.NotificationLevel
	23, // [23:23] is the sub-list for method output_type
	23, // [23:23] is the sub-list for method input_type
	23, // [23:23] is the sub-list for extension type_name
	23, // [23:23] is the sub-list for extension extendee
	0,  // [0:23] is the sub-list for field type_name
}

func init() { file_chatto_core_v1_live_events_proto_init() }
func file_chatto_core_v1_live_events_proto_init() {
	if File_chatto_core_v1_live_events_proto != nil {
		return
	}
	file_chatto_core_v1_room_events_proto_init()
	file_chatto_core_v1_user_events_proto_init()
	file_chatto_core_v1_user_preferences_proto_init()
	file_chatto_core_v1_live_events_proto_msgTypes[0].OneofWrappers = []any{
		(*LiveEvent_UserCreated)(nil),
		(*LiveEvent_UserDeleted)(nil),
		(*LiveEvent_UserProfileUpdated)(nil),
		(*LiveEvent_ServerUserPreferencesUpdated)(nil),
		(*LiveEvent_NotificationLevelChanged)(nil),
		(*LiveEvent_ThreadFollowChanged)(nil),
		(*LiveEvent_ServerMemberDeleted)(nil),
		(*LiveEvent_ServerUpdated)(nil),
		(*LiveEvent_UserTyping)(nil),
		(*LiveEvent_PresenceChanged)(nil),
		(*LiveEvent_MentionNotification)(nil),
		(*LiveEvent_NewDirectMessageNotification)(nil),
		(*LiveEvent_CallParticipantJoined)(nil),
		(*LiveEvent_CallParticipantLeft)(nil),
		(*LiveEvent_NotificationCreated)(nil),
		(*LiveEvent_NotificationDismissed)(nil),
		(*LiveEvent_RoomMarkedAsRead)(nil),
		(*LiveEvent_MentionStatusCleared)(nil),
		(*LiveEvent_RoomGroupsUpdated)(nil),
		(*LiveEvent_SessionTerminated)(nil),
	}
	file_chatto_core_v1_live_events_proto_msgTypes[4].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_chatto_core_v1_live_events_proto_rawDesc), len(file_chatto_core_v1_live_events_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_chatto_core_v1_live_events_proto_goTypes,
		DependencyIndexes: file_chatto_core_v1_live_events_proto_depIdxs,
		MessageInfos:      file_chatto_core_v1_live_events_proto_msgTypes,
	}.Build()
	File_chatto_core_v1_live_events_proto = out.File
	file_chatto_core_v1_live_events_proto_goTypes = nil
	file_chatto_core_v1_live_events_proto_depIdxs = nil
}
