// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: chatto/core/v1/message_events.proto

package corev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MessagePostedEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Room ID - identifies which room this message belongs to
	RoomId string `protobuf:"bytes,2,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	// Threading: event ID of the message this is replying to (empty = top-level message)
	InReplyTo string `protobuf:"bytes,4,opt,name=in_reply_to,json=inReplyTo,proto3" json:"in_reply_to,omitempty"`
	// Threading: event ID of the thread root message (empty = top-level message)
	// For direct replies to a root, in_thread == in_reply_to.
	// For nested replies, in_thread references the original root.
	InThread string `protobuf:"bytes,5,opt,name=in_thread,json=inThread,proto3" json:"in_thread,omitempty"`
	// User IDs of users mentioned via @username in the message body.
	// Only includes valid, resolved user IDs (invalid mentions are silently ignored).
	MentionedUserIds []string `protobuf:"bytes,6,rep,name=mentioned_user_ids,json=mentionedUserIds,proto3" json:"mentioned_user_ids,omitempty"`
	// Event ID of the original thread reply this echoes (empty = not an echo)
	EchoOfEventId string `protobuf:"bytes,7,opt,name=echo_of_event_id,json=echoOfEventId,proto3" json:"echo_of_event_id,omitempty"`
	// Thread root event ID — the thread this echo originates from (empty = not an echo)
	EchoFromThreadRootEventId string `protobuf:"bytes,8,opt,name=echo_from_thread_root_event_id,json=echoFromThreadRootEventId,proto3" json:"echo_from_thread_root_event_id,omitempty"`
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *MessagePostedEvent) Reset() {
	*x = MessagePostedEvent{}
	mi := &file_chatto_core_v1_message_events_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessagePostedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessagePostedEvent) ProtoMessage() {}

func (x *MessagePostedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_core_v1_message_events_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessagePostedEvent.ProtoReflect.Descriptor instead.
func (*MessagePostedEvent) Descriptor() ([]byte, []int) {
	return file_chatto_core_v1_message_events_proto_rawDescGZIP(), []int{0}
}

func (x *MessagePostedEvent) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *MessagePostedEvent) GetInReplyTo() string {
	if x != nil {
		return x.InReplyTo
	}
	return ""
}

func (x *MessagePostedEvent) GetInThread() string {
	if x != nil {
		return x.InThread
	}
	return ""
}

func (x *MessagePostedEvent) GetMentionedUserIds() []string {
	if x != nil {
		return x.MentionedUserIds
	}
	return nil
}

func (x *MessagePostedEvent) GetEchoOfEventId() string {
	if x != nil {
		return x.EchoOfEventId
	}
	return ""
}

func (x *MessagePostedEvent) GetEchoFromThreadRootEventId() string {
	if x != nil {
		return x.EchoFromThreadRootEventId
	}
	return ""
}

// MessageBodyEvent carries the encrypted body payload for a message post or
// body update. It is durable, room-scoped projection input but is not delivered
// as a public live event. The target message event remains MessagePostedEvent;
// edits also emit a bodyless MessageEditedEvent as the public semantic signal.
type MessageBodyEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Room ID — identifies which room this message body belongs to.
	RoomId string `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	// Event ID of the message whose current body is being set.
	EventId string `protobuf:"bytes,2,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	// Encrypted body envelope. For new writes body.body_event_id must match the
	// outer Event envelope ID that carries this MessageBodyEvent.
	Body          *MessageBody `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageBodyEvent) Reset() {
	*x = MessageBodyEvent{}
	mi := &file_chatto_core_v1_message_events_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageBodyEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageBodyEvent) ProtoMessage() {}

func (x *MessageBodyEvent) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_core_v1_message_events_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageBodyEvent.ProtoReflect.Descriptor instead.
func (*MessageBodyEvent) Descriptor() ([]byte, []int) {
	return file_chatto_core_v1_message_events_proto_rawDescGZIP(), []int{1}
}

func (x *MessageBodyEvent) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *MessageBodyEvent) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *MessageBodyEvent) GetBody() *MessageBody {
	if x != nil {
		return x.Body
	}
	return nil
}

// MessageEditedEvent is the durable semantic event published when a message's
// body or body metadata changes. The new body is published in a preceding
// MessageBodyEvent.
type MessageEditedEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Room ID — identifies which room this message belongs to.
	RoomId string `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	// Event ID of the message being edited (the original MessagePostedEvent's
	// ID). The actor performing the edit lives on the Event envelope's
	// actor_id.
	EventId       string `protobuf:"bytes,2,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageEditedEvent) Reset() {
	*x = MessageEditedEvent{}
	mi := &file_chatto_core_v1_message_events_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageEditedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageEditedEvent) ProtoMessage() {}

func (x *MessageEditedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_core_v1_message_events_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageEditedEvent.ProtoReflect.Descriptor instead.
func (*MessageEditedEvent) Descriptor() ([]byte, []int) {
	return file_chatto_core_v1_message_events_proto_rawDescGZIP(), []int{2}
}

func (x *MessageEditedEvent) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *MessageEditedEvent) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

// MessageRetractedEvent is the durable event published when a message is
// deleted. The projection marks the message tombstoned; the event log
// keeps full history for audit. Named "Retracted" rather than "Deleted"
// because we keep the original event around — only the visible body is
// dropped.
type MessageRetractedEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Room ID — identifies which room this message belonged to.
	RoomId string `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	// Event ID of the message being retracted. The actor performing the
	// retraction lives on the Event envelope's actor_id.
	EventId string `protobuf:"bytes,2,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	// Optional human-readable reason (e.g. "spam", "user requested",
	// "moderator action"). May be empty.
	Reason        string `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageRetractedEvent) Reset() {
	*x = MessageRetractedEvent{}
	mi := &file_chatto_core_v1_message_events_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageRetractedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageRetractedEvent) ProtoMessage() {}

func (x *MessageRetractedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_core_v1_message_events_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageRetractedEvent.ProtoReflect.Descriptor instead.
func (*MessageRetractedEvent) Descriptor() ([]byte, []int) {
	return file_chatto_core_v1_message_events_proto_rawDescGZIP(), []int{3}
}

func (x *MessageRetractedEvent) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *MessageRetractedEvent) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *MessageRetractedEvent) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

// MessagePinnedEvent adds a canonical message to its channel room's pinned
// message set. The actor performing the pin lives on the Event envelope.
type MessagePinnedEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Channel room containing the message.
	RoomId string `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	// Event ID of the canonical MessagePostedEvent being pinned.
	MessageEventId string `protobuf:"bytes,2,opt,name=message_event_id,json=messageEventId,proto3" json:"message_event_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *MessagePinnedEvent) Reset() {
	*x = MessagePinnedEvent{}
	mi := &file_chatto_core_v1_message_events_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessagePinnedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessagePinnedEvent) ProtoMessage() {}

func (x *MessagePinnedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_core_v1_message_events_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessagePinnedEvent.ProtoReflect.Descriptor instead.
func (*MessagePinnedEvent) Descriptor() ([]byte, []int) {
	return file_chatto_core_v1_message_events_proto_rawDescGZIP(), []int{4}
}

func (x *MessagePinnedEvent) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *MessagePinnedEvent) GetMessageEventId() string {
	if x != nil {
		return x.MessageEventId
	}
	return ""
}

// MessageUnpinnedEvent removes a canonical message from its channel room's
// pinned message set. The actor performing the unpin lives on the Event
// envelope.
type MessageUnpinnedEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Channel room containing the message.
	RoomId string `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	// Event ID of the canonical MessagePostedEvent being unpinned.
	MessageEventId string `protobuf:"bytes,2,opt,name=message_event_id,json=messageEventId,proto3" json:"message_event_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *MessageUnpinnedEvent) Reset() {
	*x = MessageUnpinnedEvent{}
	mi := &file_chatto_core_v1_message_events_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageUnpinnedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageUnpinnedEvent) ProtoMessage() {}

func (x *MessageUnpinnedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_core_v1_message_events_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageUnpinnedEvent.ProtoReflect.Descriptor instead.
func (*MessageUnpinnedEvent) Descriptor() ([]byte, []int) {
	return file_chatto_core_v1_message_events_proto_rawDescGZIP(), []int{5}
}

func (x *MessageUnpinnedEvent) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *MessageUnpinnedEvent) GetMessageEventId() string {
	if x != nil {
		return x.MessageEventId
	}
	return ""
}

type MessageUpdatedEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Room ID - identifies which room this message belongs to
	RoomId string `protobuf:"bytes,2,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	// Compound key for body storage in KV: {userId}.{eventId}
	// The userId prefix enables efficient per-user filtering for GDPR deletion.
	MessageBodyId string `protobuf:"bytes,4,opt,name=message_body_id,json=messageBodyId,proto3" json:"message_body_id,omitempty"`
	// Threading: event ID of the message this is replying to (empty = top-level message)
	InReplyTo string `protobuf:"bytes,5,opt,name=in_reply_to,json=inReplyTo,proto3" json:"in_reply_to,omitempty"`
	// Threading: event ID of the thread root message (empty = top-level message)
	InThread string `protobuf:"bytes,6,opt,name=in_thread,json=inThread,proto3" json:"in_thread,omitempty"`
	// Event ID of the updated message for legacy live payload consumers.
	// Populated at publish time from the body key.
	MessageEventId string `protobuf:"bytes,7,opt,name=message_event_id,json=messageEventId,proto3" json:"message_event_id,omitempty"`
	// Parent event's ID (populated at read time for resolver access)
	// Used for reactions lookup since reactions are keyed by event ID
	EventId       string `protobuf:"bytes,1000,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageUpdatedEvent) Reset() {
	*x = MessageUpdatedEvent{}
	mi := &file_chatto_core_v1_message_events_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageUpdatedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageUpdatedEvent) ProtoMessage() {}

func (x *MessageUpdatedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_core_v1_message_events_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageUpdatedEvent.ProtoReflect.Descriptor instead.
func (*MessageUpdatedEvent) Descriptor() ([]byte, []int) {
	return file_chatto_core_v1_message_events_proto_rawDescGZIP(), []int{6}
}

func (x *MessageUpdatedEvent) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *MessageUpdatedEvent) GetMessageBodyId() string {
	if x != nil {
		return x.MessageBodyId
	}
	return ""
}

func (x *MessageUpdatedEvent) GetInReplyTo() string {
	if x != nil {
		return x.InReplyTo
	}
	return ""
}

func (x *MessageUpdatedEvent) GetInThread() string {
	if x != nil {
		return x.InThread
	}
	return ""
}

func (x *MessageUpdatedEvent) GetMessageEventId() string {
	if x != nil {
		return x.MessageEventId
	}
	return ""
}

func (x *MessageUpdatedEvent) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

type MessageDeletedEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Room ID - identifies which room the message belonged to
	RoomId string `protobuf:"bytes,2,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	// Compound key for body storage in KV: {userId}.{eventId}
	// The userId prefix enables efficient per-user filtering for GDPR deletion.
	MessageBodyId string `protobuf:"bytes,3,opt,name=message_body_id,json=messageBodyId,proto3" json:"message_body_id,omitempty"`
	// Event ID of the deleted message for legacy live payload consumers.
	// Populated at publish time from the body key.
	MessageEventId string `protobuf:"bytes,4,opt,name=message_event_id,json=messageEventId,proto3" json:"message_event_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *MessageDeletedEvent) Reset() {
	*x = MessageDeletedEvent{}
	mi := &file_chatto_core_v1_message_events_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageDeletedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageDeletedEvent) ProtoMessage() {}

func (x *MessageDeletedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_core_v1_message_events_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageDeletedEvent.ProtoReflect.Descriptor instead.
func (*MessageDeletedEvent) Descriptor() ([]byte, []int) {
	return file_chatto_core_v1_message_events_proto_rawDescGZIP(), []int{7}
}

func (x *MessageDeletedEvent) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *MessageDeletedEvent) GetMessageBodyId() string {
	if x != nil {
		return x.MessageBodyId
	}
	return ""
}

func (x *MessageDeletedEvent) GetMessageEventId() string {
	if x != nil {
		return x.MessageEventId
	}
	return ""
}

var File_chatto_core_v1_message_events_proto protoreflect.FileDescriptor

const file_chatto_core_v1_message_events_proto_rawDesc = "" +
	"\n" +
	"#chatto/core/v1/message_events.proto\x12\x0echatto.core.v1\x1a\x1bchatto/core/v1/models.proto\"\xb7\x02\n" +
	"\x12MessagePostedEvent\x12\x17\n" +
	"\aroom_id\x18\x02 \x01(\tR\x06roomId\x12\x1e\n" +
	"\vin_reply_to\x18\x04 \x01(\tR\tinReplyTo\x12\x1b\n" +
	"\tin_thread\x18\x05 \x01(\tR\binThread\x12,\n" +
	"\x12mentioned_user_ids\x18\x06 \x03(\tR\x10mentionedUserIds\x12'\n" +
	"\x10echo_of_event_id\x18\a \x01(\tR\rechoOfEventId\x12A\n" +
	"\x1eecho_from_thread_root_event_id\x18\b \x01(\tR\x19echoFromThreadRootEventIdJ\x04\b\x01\x10\x02J\x04\b\x03\x10\x04J\x04\b\t\x10\n" +
	"R\bspace_idR\x0fmessage_body_idR\x04body\"w\n" +
	"\x10MessageBodyEvent\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\x12\x19\n" +
	"\bevent_id\x18\x02 \x01(\tR\aeventId\x12/\n" +
	"\x04body\x18\x03 \x01(\v2\x1b.chatto.core.v1.MessageBodyR\x04body\"T\n" +
	"\x12MessageEditedEvent\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\x12\x19\n" +
	"\bevent_id\x18\x02 \x01(\tR\aeventIdJ\x04\b\x03\x10\x04R\x04body\"c\n" +
	"\x15MessageRetractedEvent\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\x12\x19\n" +
	"\bevent_id\x18\x02 \x01(\tR\aeventId\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\"W\n" +
	"\x12MessagePinnedEvent\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\x12(\n" +
	"\x10message_event_id\x18\x02 \x01(\tR\x0emessageEventId\"Y\n" +
	"\x14MessageUnpinnedEvent\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\x12(\n" +
	"\x10message_event_id\x18\x02 \x01(\tR\x0emessageEventId\"\xfc\x01\n" +
	"\x13MessageUpdatedEvent\x12\x17\n" +
	"\aroom_id\x18\x02 \x01(\tR\x06roomId\x12&\n" +
	"\x0fmessage_body_id\x18\x04 \x01(\tR\rmessageBodyId\x12\x1e\n" +
	"\vin_reply_to\x18\x05 \x01(\tR\tinReplyTo\x12\x1b\n" +
	"\tin_thread\x18\x06 \x01(\tR\binThread\x12(\n" +
	"\x10message_event_id\x18\a \x01(\tR\x0emessageEventId\x12\x1a\n" +
	"\bevent_id\x18\xe8\a \x01(\tR\aeventIdJ\x04\b\x01\x10\x02J\x04\b\x03\x10\x04R\bspace_idR\vsequence_id\"\x90\x01\n" +
	"\x13MessageDeletedEvent\x12\x17\n" +
	"\aroom_id\x18\x02 \x01(\tR\x06roomId\x12&\n" +
	"\x0fmessage_body_id\x18\x03 \x01(\tR\rmessageBodyId\x12(\n" +
	"\x10message_event_id\x18\x04 \x01(\tR\x0emessageEventIdJ\x04\b\x01\x10\x02R\bspace_idB\xb5\x01\n" +
	"\x12com.chatto.core.v1B\x12MessageEventsProtoP\x01Z1hmans.de/chatto/internal/pb/chatto/core/v1;corev1\xa2\x02\x03CCX\xaa\x02\x0eChatto.Core.V1\xca\x02\x0eChatto\\Core\\V1\xe2\x02\x1aChatto\\Core\\V1\\GPBMetadata\xea\x02\x10Chatto::Core::V1b\x06proto3"

var (
	file_chatto_core_v1_message_events_proto_rawDescOnce sync.Once
	file_chatto_core_v1_message_events_proto_rawDescData []byte
)

func file_chatto_core_v1_message_events_proto_rawDescGZIP() []byte {
	file_chatto_core_v1_message_events_proto_rawDescOnce.Do(func() {
		file_chatto_core_v1_message_events_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_chatto_core_v1_message_events_proto_rawDesc), len(file_chatto_core_v1_message_events_proto_rawDesc)))
	})
	return file_chatto_core_v1_message_events_proto_rawDescData
}

var file_chatto_core_v1_message_events_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_chatto_core_v1_message_events_proto_goTypes = []any{
	(*MessagePostedEvent)(nil),    // 0: chatto.core.v1.MessagePostedEvent
	(*MessageBodyEvent)(nil),      // 1: chatto.core.v1.MessageBodyEvent
	(*MessageEditedEvent)(nil),    // 2: chatto.core.v1.MessageEditedEvent
	(*MessageRetractedEvent)(nil), // 3: chatto.core.v1.MessageRetractedEvent
	(*MessagePinnedEvent)(nil),    // 4: chatto.core.v1.MessagePinnedEvent
	(*MessageUnpinnedEvent)(nil),  // 5: chatto.core.v1.MessageUnpinnedEvent
	(*MessageUpdatedEvent)(nil),   // 6: chatto.core.v1.MessageUpdatedEvent
	(*MessageDeletedEvent)(nil),   // 7: chatto.core.v1.MessageDeletedEvent
	(*MessageBody)(nil),           // 8: chatto.core.v1.MessageBody
}
var file_chatto_core_v1_message_events_proto_depIdxs = []int32{
	8, // 0: chatto.core.v1.MessageBodyEvent.body:type_name -> chatto.core.v1.MessageBody
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_chatto_core_v1_message_events_proto_init() }
func file_chatto_core_v1_message_events_proto_init() {
	if File_chatto_core_v1_message_events_proto != nil {
		return
	}
	file_chatto_core_v1_models_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_chatto_core_v1_message_events_proto_rawDesc), len(file_chatto_core_v1_message_events_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_chatto_core_v1_message_events_proto_goTypes,
		DependencyIndexes: file_chatto_core_v1_message_events_proto_depIdxs,
		MessageInfos:      file_chatto_core_v1_message_events_proto_msgTypes,
	}.Build()
	File_chatto_core_v1_message_events_proto = out.File
	file_chatto_core_v1_message_events_proto_goTypes = nil
	file_chatto_core_v1_message_events_proto_depIdxs = nil
}
