// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: chatto/core/v1/projection_snapshots.proto

package corev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ProjectionSnapshotGeneration is the encrypted, immutable unit published by
// the projection snapshot repository. It is derived cache data,
// not an authoritative domain record.
type ProjectionSnapshotGeneration struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	GenerationId    string                 `protobuf:"bytes,1,opt,name=generation_id,json=generationId,proto3" json:"generation_id,omitempty"`
	StreamName      string                 `protobuf:"bytes,2,opt,name=stream_name,json=streamName,proto3" json:"stream_name,omitempty"`
	CutoffSequence  uint64                 `protobuf:"varint,3,opt,name=cutoff_sequence,json=cutoffSequence,proto3" json:"cutoff_sequence,omitempty"`
	ProjectionKey   string                 `protobuf:"bytes,4,opt,name=projection_key,json=projectionKey,proto3" json:"projection_key,omitempty"`
	CompatibilityId string                 `protobuf:"bytes,5,opt,name=compatibility_id,json=compatibilityId,proto3" json:"compatibility_id,omitempty"`
	ProducerVersion string                 `protobuf:"bytes,6,opt,name=producer_version,json=producerVersion,proto3" json:"producer_version,omitempty"`
	CreatedAt       *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Payload         []byte                 `protobuf:"bytes,8,opt,name=payload,proto3" json:"payload,omitempty"`
	PayloadSize     uint64                 `protobuf:"varint,9,opt,name=payload_size,json=payloadSize,proto3" json:"payload_size,omitempty"`
	PayloadSha256   []byte                 `protobuf:"bytes,10,opt,name=payload_sha256,json=payloadSha256,proto3" json:"payload_sha256,omitempty"`
	// Versioned identity of the EVT stream incarnation.
	StreamIdentity string `protobuf:"bytes,11,opt,name=stream_identity,json=streamIdentity,proto3" json:"stream_identity,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ProjectionSnapshotGeneration) Reset() {
	*x = ProjectionSnapshotGeneration{}
	mi := &file_chatto_core_v1_projection_snapshots_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProjectionSnapshotGeneration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectionSnapshotGeneration) ProtoMessage() {}

func (x *ProjectionSnapshotGeneration) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_core_v1_projection_snapshots_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjectionSnapshotGeneration.ProtoReflect.Descriptor instead.
func (*ProjectionSnapshotGeneration) Descriptor() ([]byte, []int) {
	return file_chatto_core_v1_projection_snapshots_proto_rawDescGZIP(), []int{0}
}

func (x *ProjectionSnapshotGeneration) GetGenerationId() string {
	if x != nil {
		return x.GenerationId
	}
	return ""
}

func (x *ProjectionSnapshotGeneration) GetStreamName() string {
	if x != nil {
		return x.StreamName
	}
	return ""
}

func (x *ProjectionSnapshotGeneration) GetCutoffSequence() uint64 {
	if x != nil {
		return x.CutoffSequence
	}
	return 0
}

func (x *ProjectionSnapshotGeneration) GetProjectionKey() string {
	if x != nil {
		return x.ProjectionKey
	}
	return ""
}

func (x *ProjectionSnapshotGeneration) GetCompatibilityId() string {
	if x != nil {
		return x.CompatibilityId
	}
	return ""
}

func (x *ProjectionSnapshotGeneration) GetProducerVersion() string {
	if x != nil {
		return x.ProducerVersion
	}
	return ""
}

func (x *ProjectionSnapshotGeneration) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *ProjectionSnapshotGeneration) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ProjectionSnapshotGeneration) GetPayloadSize() uint64 {
	if x != nil {
		return x.PayloadSize
	}
	return 0
}

func (x *ProjectionSnapshotGeneration) GetPayloadSha256() []byte {
	if x != nil {
		return x.PayloadSha256
	}
	return nil
}

func (x *ProjectionSnapshotGeneration) GetStreamIdentity() string {
	if x != nil {
		return x.StreamIdentity
	}
	return ""
}

// ProjectionSnapshotPointer names the two most recently published immutable
// generations for one projection. It is encrypted and may safely be stale.
type ProjectionSnapshotPointer struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	CurrentGenerationId  string                 `protobuf:"bytes,1,opt,name=current_generation_id,json=currentGenerationId,proto3" json:"current_generation_id,omitempty"`
	PreviousGenerationId string                 `protobuf:"bytes,2,opt,name=previous_generation_id,json=previousGenerationId,proto3" json:"previous_generation_id,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *ProjectionSnapshotPointer) Reset() {
	*x = ProjectionSnapshotPointer{}
	mi := &file_chatto_core_v1_projection_snapshots_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProjectionSnapshotPointer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectionSnapshotPointer) ProtoMessage() {}

func (x *ProjectionSnapshotPointer) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_core_v1_projection_snapshots_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjectionSnapshotPointer.ProtoReflect.Descriptor instead.
func (*ProjectionSnapshotPointer) Descriptor() ([]byte, []int) {
	return file_chatto_core_v1_projection_snapshots_proto_rawDescGZIP(), []int{1}
}

func (x *ProjectionSnapshotPointer) GetCurrentGenerationId() string {
	if x != nil {
		return x.CurrentGenerationId
	}
	return ""
}

func (x *ProjectionSnapshotPointer) GetPreviousGenerationId() string {
	if x != nil {
		return x.PreviousGenerationId
	}
	return ""
}

// ThreadProjectionSnapshot is the canonical restorable state for the
// threads-v1 projection compatibility contract. Repeated fields are emitted in
// deterministic key order by the codec.
type ThreadProjectionSnapshot struct {
	state           protoimpl.MessageState         `protogen:"open.v1"`
	Threads         []*ThreadSnapshot              `protobuf:"bytes,1,rep,name=threads,proto3" json:"threads,omitempty"`
	Replies         []*ThreadReplySnapshot         `protobuf:"bytes,2,rep,name=replies,proto3" json:"replies,omitempty"`
	Follows         []*ThreadFollowSnapshot        `protobuf:"bytes,3,rep,name=follows,proto3" json:"follows,omitempty"`
	ShreddedUserIds []string                       `protobuf:"bytes,4,rep,name=shredded_user_ids,json=shreddedUserIds,proto3" json:"shredded_user_ids,omitempty"`
	ReplayGuard     *ProjectionReplayGuardSnapshot `protobuf:"bytes,5,opt,name=replay_guard,json=replayGuard,proto3" json:"replay_guard,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ThreadProjectionSnapshot) Reset() {
	*x = ThreadProjectionSnapshot{}
	mi := &file_chatto_core_v1_projection_snapshots_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ThreadProjectionSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ThreadProjectionSnapshot) ProtoMessage() {}

func (x *ThreadProjectionSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_core_v1_projection_snapshots_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ThreadProjectionSnapshot.ProtoReflect.Descriptor instead.
func (*ThreadProjectionSnapshot) Descriptor() ([]byte, []int) {
	return file_chatto_core_v1_projection_snapshots_proto_rawDescGZIP(), []int{2}
}

func (x *ThreadProjectionSnapshot) GetThreads() []*ThreadSnapshot {
	if x != nil {
		return x.Threads
	}
	return nil
}

func (x *ThreadProjectionSnapshot) GetReplies() []*ThreadReplySnapshot {
	if x != nil {
		return x.Replies
	}
	return nil
}

func (x *ThreadProjectionSnapshot) GetFollows() []*ThreadFollowSnapshot {
	if x != nil {
		return x.Follows
	}
	return nil
}

func (x *ThreadProjectionSnapshot) GetShreddedUserIds() []string {
	if x != nil {
		return x.ShreddedUserIds
	}
	return nil
}

func (x *ThreadProjectionSnapshot) GetReplayGuard() *ProjectionReplayGuardSnapshot {
	if x != nil {
		return x.ReplayGuard
	}
	return nil
}

type ThreadSnapshot struct {
	state         protoimpl.MessageState         `protogen:"open.v1"`
	RootEventId   string                         `protobuf:"bytes,1,opt,name=root_event_id,json=rootEventId,proto3" json:"root_event_id,omitempty"`
	Entries       []*ThreadTimelineEntrySnapshot `protobuf:"bytes,2,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ThreadSnapshot) Reset() {
	*x = ThreadSnapshot{}
	mi := &file_chatto_core_v1_projection_snapshots_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ThreadSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ThreadSnapshot) ProtoMessage() {}

func (x *ThreadSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_core_v1_projection_snapshots_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ThreadSnapshot.ProtoReflect.Descriptor instead.
func (*ThreadSnapshot) Descriptor() ([]byte, []int) {
	return file_chatto_core_v1_projection_snapshots_proto_rawDescGZIP(), []int{3}
}

func (x *ThreadSnapshot) GetRootEventId() string {
	if x != nil {
		return x.RootEventId
	}
	return ""
}

func (x *ThreadSnapshot) GetEntries() []*ThreadTimelineEntrySnapshot {
	if x != nil {
		return x.Entries
	}
	return nil
}

type ThreadTimelineEntrySnapshot struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	EventId        string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	StreamSequence uint64                 `protobuf:"varint,2,opt,name=stream_sequence,json=streamSequence,proto3" json:"stream_sequence,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ThreadTimelineEntrySnapshot) Reset() {
	*x = ThreadTimelineEntrySnapshot{}
	mi := &file_chatto_core_v1_projection_snapshots_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ThreadTimelineEntrySnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ThreadTimelineEntrySnapshot) ProtoMessage() {}

func (x *ThreadTimelineEntrySnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_core_v1_projection_snapshots_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ThreadTimelineEntrySnapshot.ProtoReflect.Descriptor instead.
func (*ThreadTimelineEntrySnapshot) Descriptor() ([]byte, []int) {
	return file_chatto_core_v1_projection_snapshots_proto_rawDescGZIP(), []int{4}
}

func (x *ThreadTimelineEntrySnapshot) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *ThreadTimelineEntrySnapshot) GetStreamSequence() uint64 {
	if x != nil {
		return x.StreamSequence
	}
	return 0
}

type ThreadReplySnapshot struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	EventId           string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	ThreadRootEventId string                 `protobuf:"bytes,2,opt,name=thread_root_event_id,json=threadRootEventId,proto3" json:"thread_root_event_id,omitempty"`
	ActorId           string                 `protobuf:"bytes,3,opt,name=actor_id,json=actorId,proto3" json:"actor_id,omitempty"`
	CreatedAt         *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Retracted         bool                   `protobuf:"varint,5,opt,name=retracted,proto3" json:"retracted,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ThreadReplySnapshot) Reset() {
	*x = ThreadReplySnapshot{}
	mi := &file_chatto_core_v1_projection_snapshots_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ThreadReplySnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ThreadReplySnapshot) ProtoMessage() {}

func (x *ThreadReplySnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_core_v1_projection_snapshots_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ThreadReplySnapshot.ProtoReflect.Descriptor instead.
func (*ThreadReplySnapshot) Descriptor() ([]byte, []int) {
	return file_chatto_core_v1_projection_snapshots_proto_rawDescGZIP(), []int{5}
}

func (x *ThreadReplySnapshot) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *ThreadReplySnapshot) GetThreadRootEventId() string {
	if x != nil {
		return x.ThreadRootEventId
	}
	return ""
}

func (x *ThreadReplySnapshot) GetActorId() string {
	if x != nil {
		return x.ActorId
	}
	return ""
}

func (x *ThreadReplySnapshot) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *ThreadReplySnapshot) GetRetracted() bool {
	if x != nil {
		return x.Retracted
	}
	return false
}

type ThreadFollowSnapshot struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	UserId            string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	RoomId            string                 `protobuf:"bytes,2,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	ThreadRootEventId string                 `protobuf:"bytes,3,opt,name=thread_root_event_id,json=threadRootEventId,proto3" json:"thread_root_event_id,omitempty"`
	State             string                 `protobuf:"bytes,4,opt,name=state,proto3" json:"state,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ThreadFollowSnapshot) Reset() {
	*x = ThreadFollowSnapshot{}
	mi := &file_chatto_core_v1_projection_snapshots_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ThreadFollowSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ThreadFollowSnapshot) ProtoMessage() {}

func (x *ThreadFollowSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_core_v1_projection_snapshots_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ThreadFollowSnapshot.ProtoReflect.Descriptor instead.
func (*ThreadFollowSnapshot) Descriptor() ([]byte, []int) {
	return file_chatto_core_v1_projection_snapshots_proto_rawDescGZIP(), []int{6}
}

func (x *ThreadFollowSnapshot) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ThreadFollowSnapshot) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *ThreadFollowSnapshot) GetThreadRootEventId() string {
	if x != nil {
		return x.ThreadRootEventId
	}
	return ""
}

func (x *ThreadFollowSnapshot) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

type ProjectionReplayGuardSnapshot struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	HighestSequence   uint64                 `protobuf:"varint,1,opt,name=highest_sequence,json=highestSequence,proto3" json:"highest_sequence,omitempty"`
	CompatibilityMode bool                   `protobuf:"varint,2,opt,name=compatibility_mode,json=compatibilityMode,proto3" json:"compatibility_mode,omitempty"`
	EventIds          []string               `protobuf:"bytes,3,rep,name=event_ids,json=eventIds,proto3" json:"event_ids,omitempty"`
	ReplayComplete    bool                   `protobuf:"varint,4,opt,name=replay_complete,json=replayComplete,proto3" json:"replay_complete,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ProjectionReplayGuardSnapshot) Reset() {
	*x = ProjectionReplayGuardSnapshot{}
	mi := &file_chatto_core_v1_projection_snapshots_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProjectionReplayGuardSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectionReplayGuardSnapshot) ProtoMessage() {}

func (x *ProjectionReplayGuardSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_core_v1_projection_snapshots_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjectionReplayGuardSnapshot.ProtoReflect.Descriptor instead.
func (*ProjectionReplayGuardSnapshot) Descriptor() ([]byte, []int) {
	return file_chatto_core_v1_projection_snapshots_proto_rawDescGZIP(), []int{7}
}

func (x *ProjectionReplayGuardSnapshot) GetHighestSequence() uint64 {
	if x != nil {
		return x.HighestSequence
	}
	return 0
}

func (x *ProjectionReplayGuardSnapshot) GetCompatibilityMode() bool {
	if x != nil {
		return x.CompatibilityMode
	}
	return false
}

func (x *ProjectionReplayGuardSnapshot) GetEventIds() []string {
	if x != nil {
		return x.EventIds
	}
	return nil
}

func (x *ProjectionReplayGuardSnapshot) GetReplayComplete() bool {
	if x != nil {
		return x.ReplayComplete
	}
	return false
}

var File_chatto_core_v1_projection_snapshots_proto protoreflect.FileDescriptor

const file_chatto_core_v1_projection_snapshots_proto_rawDesc = "" +
	"\n" +
	")chatto/core/v1/projection_snapshots.proto\x12\x0echatto.core.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xd2\x03\n" +
	"\x1cProjectionSnapshotGeneration\x12#\n" +
	"\rgeneration_id\x18\x01 \x01(\tR\fgenerationId\x12\x1f\n" +
	"\vstream_name\x18\x02 \x01(\tR\n" +
	"streamName\x12'\n" +
	"\x0fcutoff_sequence\x18\x03 \x01(\x04R\x0ecutoffSequence\x12%\n" +
	"\x0eprojection_key\x18\x04 \x01(\tR\rprojectionKey\x12)\n" +
	"\x10compatibility_id\x18\x05 \x01(\tR\x0fcompatibilityId\x12)\n" +
	"\x10producer_version\x18\x06 \x01(\tR\x0fproducerVersion\x129\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12\x18\n" +
	"\apayload\x18\b \x01(\fR\apayload\x12!\n" +
	"\fpayload_size\x18\t \x01(\x04R\vpayloadSize\x12%\n" +
	"\x0epayload_sha256\x18\n" +
	" \x01(\fR\rpayloadSha256\x12'\n" +
	"\x0fstream_identity\x18\v \x01(\tR\x0estreamIdentity\"\x85\x01\n" +
	"\x19ProjectionSnapshotPointer\x122\n" +
	"\x15current_generation_id\x18\x01 \x01(\tR\x13currentGenerationId\x124\n" +
	"\x16previous_generation_id\x18\x02 \x01(\tR\x14previousGenerationId\"\xd1\x02\n" +
	"\x18ThreadProjectionSnapshot\x128\n" +
	"\athreads\x18\x01 \x03(\v2\x1e.chatto.core.v1.ThreadSnapshotR\athreads\x12=\n" +
	"\areplies\x18\x02 \x03(\v2#.chatto.core.v1.ThreadReplySnapshotR\areplies\x12>\n" +
	"\afollows\x18\x03 \x03(\v2$.chatto.core.v1.ThreadFollowSnapshotR\afollows\x12*\n" +
	"\x11shredded_user_ids\x18\x04 \x03(\tR\x0fshreddedUserIds\x12P\n" +
	"\freplay_guard\x18\x05 \x01(\v2-.chatto.core.v1.ProjectionReplayGuardSnapshotR\vreplayGuard\"{\n" +
	"\x0eThreadSnapshot\x12\"\n" +
	"\rroot_event_id\x18\x01 \x01(\tR\vrootEventId\x12E\n" +
	"\aentries\x18\x02 \x03(\v2+.chatto.core.v1.ThreadTimelineEntrySnapshotR\aentries\"a\n" +
	"\x1bThreadTimelineEntrySnapshot\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x12'\n" +
	"\x0fstream_sequence\x18\x02 \x01(\x04R\x0estreamSequence\"\xd5\x01\n" +
	"\x13ThreadReplySnapshot\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x12/\n" +
	"\x14thread_root_event_id\x18\x02 \x01(\tR\x11threadRootEventId\x12\x19\n" +
	"\bactor_id\x18\x03 \x01(\tR\aactorId\x129\n" +
	"\n" +
	"created_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12\x1c\n" +
	"\tretracted\x18\x05 \x01(\bR\tretracted\"\x8f\x01\n" +
	"\x14ThreadFollowSnapshot\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x17\n" +
	"\aroom_id\x18\x02 \x01(\tR\x06roomId\x12/\n" +
	"\x14thread_root_event_id\x18\x03 \x01(\tR\x11threadRootEventId\x12\x14\n" +
	"\x05state\x18\x04 \x01(\tR\x05state\"\xbf\x01\n" +
	"\x1dProjectionReplayGuardSnapshot\x12)\n" +
	"\x10highest_sequence\x18\x01 \x01(\x04R\x0fhighestSequence\x12-\n" +
	"\x12compatibility_mode\x18\x02 \x01(\bR\x11compatibilityMode\x12\x1b\n" +
	"\tevent_ids\x18\x03 \x03(\tR\beventIds\x12'\n" +
	"\x0freplay_complete\x18\x04 \x01(\bR\x0ereplayCompleteB\xbb\x01\n" +
	"\x12com.chatto.core.v1B\x18ProjectionSnapshotsProtoP\x01Z1hmans.de/chatto/internal/pb/chatto/core/v1;corev1\xa2\x02\x03CCX\xaa\x02\x0eChatto.Core.V1\xca\x02\x0eChatto\\Core\\V1\xe2\x02\x1aChatto\\Core\\V1\\GPBMetadata\xea\x02\x10Chatto::Core::V1b\x06proto3"

var (
	file_chatto_core_v1_projection_snapshots_proto_rawDescOnce sync.Once
	file_chatto_core_v1_projection_snapshots_proto_rawDescData []byte
)

func file_chatto_core_v1_projection_snapshots_proto_rawDescGZIP() []byte {
	file_chatto_core_v1_projection_snapshots_proto_rawDescOnce.Do(func() {
		file_chatto_core_v1_projection_snapshots_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_chatto_core_v1_projection_snapshots_proto_rawDesc), len(file_chatto_core_v1_projection_snapshots_proto_rawDesc)))
	})
	return file_chatto_core_v1_projection_snapshots_proto_rawDescData
}

var file_chatto_core_v1_projection_snapshots_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_chatto_core_v1_projection_snapshots_proto_goTypes = []any{
	(*ProjectionSnapshotGeneration)(nil),  // 0: chatto.core.v1.ProjectionSnapshotGeneration
	(*ProjectionSnapshotPointer)(nil),     // 1: chatto.core.v1.ProjectionSnapshotPointer
	(*ThreadProjectionSnapshot)(nil),      // 2: chatto.core.v1.ThreadProjectionSnapshot
	(*ThreadSnapshot)(nil),                // 3: chatto.core.v1.ThreadSnapshot
	(*ThreadTimelineEntrySnapshot)(nil),   // 4: chatto.core.v1.ThreadTimelineEntrySnapshot
	(*ThreadReplySnapshot)(nil),           // 5: chatto.core.v1.ThreadReplySnapshot
	(*ThreadFollowSnapshot)(nil),          // 6: chatto.core.v1.ThreadFollowSnapshot
	(*ProjectionReplayGuardSnapshot)(nil), // 7: chatto.core.v1.ProjectionReplayGuardSnapshot
	(*timestamppb.Timestamp)(nil),         // 8: google.protobuf.Timestamp
}
var file_chatto_core_v1_projection_snapshots_proto_depIdxs = []int32{
	8, // 0: chatto.core.v1.ProjectionSnapshotGeneration.created_at:type_name -> google.protobuf.Timestamp
	3, // 1: chatto.core.v1.ThreadProjectionSnapshot.threads:type_name -> chatto.core.v1.ThreadSnapshot
	5, // 2: chatto.core.v1.ThreadProjectionSnapshot.replies:type_name -> chatto.core.v1.ThreadReplySnapshot
	6, // 3: chatto.core.v1.ThreadProjectionSnapshot.follows:type_name -> chatto.core.v1.ThreadFollowSnapshot
	7, // 4: chatto.core.v1.ThreadProjectionSnapshot.replay_guard:type_name -> chatto.core.v1.ProjectionReplayGuardSnapshot
	4, // 5: chatto.core.v1.ThreadSnapshot.entries:type_name -> chatto.core.v1.ThreadTimelineEntrySnapshot
	8, // 6: chatto.core.v1.ThreadReplySnapshot.created_at:type_name -> google.protobuf.Timestamp
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_chatto_core_v1_projection_snapshots_proto_init() }
func file_chatto_core_v1_projection_snapshots_proto_init() {
	if File_chatto_core_v1_projection_snapshots_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_chatto_core_v1_projection_snapshots_proto_rawDesc), len(file_chatto_core_v1_projection_snapshots_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_chatto_core_v1_projection_snapshots_proto_goTypes,
		DependencyIndexes: file_chatto_core_v1_projection_snapshots_proto_depIdxs,
		MessageInfos:      file_chatto_core_v1_projection_snapshots_proto_msgTypes,
	}.Build()
	File_chatto_core_v1_projection_snapshots_proto = out.File
	file_chatto_core_v1_projection_snapshots_proto_goTypes = nil
	file_chatto_core_v1_projection_snapshots_proto_depIdxs = nil
}
