// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: chatto/core/v1/user_events.proto

package corev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UserDEKPurpose int32

const (
	UserDEKPurpose_USER_DEK_PURPOSE_UNSPECIFIED  UserDEKPurpose = 0
	UserDEKPurpose_USER_DEK_PURPOSE_MESSAGE_BODY UserDEKPurpose = 1
	UserDEKPurpose_USER_DEK_PURPOSE_USER_PII     UserDEKPurpose = 2
)

// Enum value maps for UserDEKPurpose.
var (
	UserDEKPurpose_name = map[int32]string{
		0: "USER_DEK_PURPOSE_UNSPECIFIED",
		1: "USER_DEK_PURPOSE_MESSAGE_BODY",
		2: "USER_DEK_PURPOSE_USER_PII",
	}
	UserDEKPurpose_value = map[string]int32{
		"USER_DEK_PURPOSE_UNSPECIFIED":  0,
		"USER_DEK_PURPOSE_MESSAGE_BODY": 1,
		"USER_DEK_PURPOSE_USER_PII":     2,
	}
)

func (x UserDEKPurpose) Enum() *UserDEKPurpose {
	p := new(UserDEKPurpose)
	*p = x
	return p
}

func (x UserDEKPurpose) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UserDEKPurpose) Descriptor() protoreflect.EnumDescriptor {
	return file_chatto_core_v1_user_events_proto_enumTypes[0].Descriptor()
}

func (UserDEKPurpose) Type() protoreflect.EnumType {
	return &file_chatto_core_v1_user_events_proto_enumTypes[0]
}

func (x UserDEKPurpose) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use UserDEKPurpose.Descriptor instead.
func (UserDEKPurpose) EnumDescriptor() ([]byte, []int) {
	return file_chatto_core_v1_user_events_proto_rawDescGZIP(), []int{0}
}

type UserCreatedEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Login         string                 `protobuf:"bytes,2,opt,name=login,proto3" json:"login,omitempty"`
	DisplayName   string                 `protobuf:"bytes,3,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserCreatedEvent) Reset() {
	*x = UserCreatedEvent{}
	mi := &file_chatto_core_v1_user_events_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserCreatedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserCreatedEvent) ProtoMessage() {}

func (x *UserCreatedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_core_v1_user_events_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserCreatedEvent.ProtoReflect.Descriptor instead.
func (*UserCreatedEvent) Descriptor() ([]byte, []int) {
	return file_chatto_core_v1_user_events_proto_rawDescGZIP(), []int{0}
}

func (x *UserCreatedEvent) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UserCreatedEvent) GetLogin() string {
	if x != nil {
		return x.Login
	}
	return ""
}

func (x *UserCreatedEvent) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

// UserDeletedEvent records a durable user-account deletion fact in EVT.
// Transient realtime delivery uses SessionTerminatedEvent for the deleted
// user's own clients and ServerMemberDeletedEvent for server-wide invalidation.
type UserDeletedEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserDeletedEvent) Reset() {
	*x = UserDeletedEvent{}
	mi := &file_chatto_core_v1_user_events_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserDeletedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserDeletedEvent) ProtoMessage() {}

func (x *UserDeletedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_core_v1_user_events_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserDeletedEvent.ProtoReflect.Descriptor instead.
func (*UserDeletedEvent) Descriptor() ([]byte, []int) {
	return file_chatto_core_v1_user_events_proto_rawDescGZIP(), []int{1}
}

func (x *UserDeletedEvent) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

// UserProfileUpdatedEvent is published when a user's profile changes.
// This includes avatar uploads/deletions, display name changes, and login changes.
// Allows other users to see profile changes in real-time.
type UserProfileUpdatedEvent struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	UserId      string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	DisplayName string                 `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	// URL to the user's avatar, or empty if no avatar is set.
	AvatarUrl string `protobuf:"bytes,3,opt,name=avatar_url,json=avatarUrl,proto3" json:"avatar_url,omitempty"`
	// The user's current login/username.
	Login         string `protobuf:"bytes,4,opt,name=login,proto3" json:"login,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserProfileUpdatedEvent) Reset() {
	*x = UserProfileUpdatedEvent{}
	mi := &file_chatto_core_v1_user_events_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserProfileUpdatedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserProfileUpdatedEvent) ProtoMessage() {}

func (x *UserProfileUpdatedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_core_v1_user_events_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserProfileUpdatedEvent.ProtoReflect.Descriptor instead.
func (*UserProfileUpdatedEvent) Descriptor() ([]byte, []int) {
	return file_chatto_core_v1_user_events_proto_rawDescGZIP(), []int{2}
}

func (x *UserProfileUpdatedEvent) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UserProfileUpdatedEvent) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *UserProfileUpdatedEvent) GetAvatarUrl() string {
	if x != nil {
		return x.AvatarUrl
	}
	return ""
}

func (x *UserProfileUpdatedEvent) GetLogin() string {
	if x != nil {
		return x.Login
	}
	return ""
}

// ServerUserPreferencesUpdatedEvent is published when a user updates their display preferences.
// User-scoped private event for multi-tab/multi-device sync.
type ServerUserPreferencesUpdatedEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// IANA timezone name (empty = cleared/browser default).
	Timezone string `protobuf:"bytes,1,opt,name=timezone,proto3" json:"timezone,omitempty"`
	// Time display format preference.
	TimeFormat    TimeFormat `protobuf:"varint,2,opt,name=time_format,json=timeFormat,proto3,enum=chatto.core.v1.TimeFormat" json:"time_format,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerUserPreferencesUpdatedEvent) Reset() {
	*x = ServerUserPreferencesUpdatedEvent{}
	mi := &file_chatto_core_v1_user_events_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerUserPreferencesUpdatedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerUserPreferencesUpdatedEvent) ProtoMessage() {}

func (x *ServerUserPreferencesUpdatedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_core_v1_user_events_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerUserPreferencesUpdatedEvent.ProtoReflect.Descriptor instead.
func (*ServerUserPreferencesUpdatedEvent) Descriptor() ([]byte, []int) {
	return file_chatto_core_v1_user_events_proto_rawDescGZIP(), []int{3}
}

func (x *ServerUserPreferencesUpdatedEvent) GetTimezone() string {
	if x != nil {
		return x.Timezone
	}
	return ""
}

func (x *ServerUserPreferencesUpdatedEvent) GetTimeFormat() TimeFormat {
	if x != nil {
		return x.TimeFormat
	}
	return TimeFormat_TIME_FORMAT_UNSPECIFIED
}

type EncryptedUserString struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	EncryptedValue  []byte                 `protobuf:"bytes,1,opt,name=encrypted_value,json=encryptedValue,proto3" json:"encrypted_value,omitempty"`
	Nonce           []byte                 `protobuf:"bytes,2,opt,name=nonce,proto3" json:"nonce,omitempty"`
	ContentKeyEpoch int32                  `protobuf:"varint,3,opt,name=content_key_epoch,json=contentKeyEpoch,proto3" json:"content_key_epoch,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *EncryptedUserString) Reset() {
	*x = EncryptedUserString{}
	mi := &file_chatto_core_v1_user_events_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EncryptedUserString) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EncryptedUserString) ProtoMessage() {}

func (x *EncryptedUserString) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_core_v1_user_events_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EncryptedUserString.ProtoReflect.Descriptor instead.
func (*EncryptedUserString) Descriptor() ([]byte, []int) {
	return file_chatto_core_v1_user_events_proto_rawDescGZIP(), []int{4}
}

func (x *EncryptedUserString) GetEncryptedValue() []byte {
	if x != nil {
		return x.EncryptedValue
	}
	return nil
}

func (x *EncryptedUserString) GetNonce() []byte {
	if x != nil {
		return x.Nonce
	}
	return nil
}

func (x *EncryptedUserString) GetContentKeyEpoch() int32 {
	if x != nil {
		return x.ContentKeyEpoch
	}
	return 0
}

type UserAccountCreatedEvent struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	UserId string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	// Account kind. Empty/unspecified is treated as USER_KIND_HUMAN so accounts
	// created before this field existed backfill correctly (FDR-902).
	Kind                 UserKind             `protobuf:"varint,2,opt,name=kind,proto3,enum=chatto.core.v1.UserKind" json:"kind,omitempty"`
	EncryptedLogin       *EncryptedUserString `protobuf:"bytes,10,opt,name=encrypted_login,json=encryptedLogin,proto3" json:"encrypted_login,omitempty"`
	EncryptedDisplayName *EncryptedUserString `protobuf:"bytes,11,opt,name=encrypted_display_name,json=encryptedDisplayName,proto3" json:"encrypted_display_name,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *UserAccountCreatedEvent) Reset() {
	*x = UserAccountCreatedEvent{}
	mi := &file_chatto_core_v1_user_events_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserAccountCreatedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserAccountCreatedEvent) ProtoMessage() {}

func (x *UserAccountCreatedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_core_v1_user_events_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserAccountCreatedEvent.ProtoReflect.Descriptor instead.
func (*UserAccountCreatedEvent) Descriptor() ([]byte, []int) {
	return file_chatto_core_v1_user_events_proto_rawDescGZIP(), []int{5}
}

func (x *UserAccountCreatedEvent) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UserAccountCreatedEvent) GetKind() UserKind {
	if x != nil {
		return x.Kind
	}
	return UserKind_USER_KIND_UNSPECIFIED
}

func (x *UserAccountCreatedEvent) GetEncryptedLogin() *EncryptedUserString {
	if x != nil {
		return x.EncryptedLogin
	}
	return nil
}

func (x *UserAccountCreatedEvent) GetEncryptedDisplayName() *EncryptedUserString {
	if x != nil {
		return x.EncryptedDisplayName
	}
	return nil
}

type UserLoginChangedEvent struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	UserId         string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	EncryptedLogin *EncryptedUserString   `protobuf:"bytes,10,opt,name=encrypted_login,json=encryptedLogin,proto3" json:"encrypted_login,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UserLoginChangedEvent) Reset() {
	*x = UserLoginChangedEvent{}
	mi := &file_chatto_core_v1_user_events_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserLoginChangedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserLoginChangedEvent) ProtoMessage() {}

func (x *UserLoginChangedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_core_v1_user_events_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserLoginChangedEvent.ProtoReflect.Descriptor instead.
func (*UserLoginChangedEvent) Descriptor() ([]byte, []int) {
	return file_chatto_core_v1_user_events_proto_rawDescGZIP(), []int{6}
}

func (x *UserLoginChangedEvent) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UserLoginChangedEvent) GetEncryptedLogin() *EncryptedUserString {
	if x != nil {
		return x.EncryptedLogin
	}
	return nil
}

type UserDisplayNameChangedEvent struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	UserId               string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	EncryptedDisplayName *EncryptedUserString   `protobuf:"bytes,10,opt,name=encrypted_display_name,json=encryptedDisplayName,proto3" json:"encrypted_display_name,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *UserDisplayNameChangedEvent) Reset() {
	*x = UserDisplayNameChangedEvent{}
	mi := &file_chatto_core_v1_user_events_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserDisplayNameChangedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserDisplayNameChangedEvent) ProtoMessage() {}

func (x *UserDisplayNameChangedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_core_v1_user_events_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserDisplayNameChangedEvent.ProtoReflect.Descriptor instead.
func (*UserDisplayNameChangedEvent) Descriptor() ([]byte, []int) {
	return file_chatto_core_v1_user_events_proto_rawDescGZIP(), []int{7}
}

func (x *UserDisplayNameChangedEvent) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UserDisplayNameChangedEvent) GetEncryptedDisplayName() *EncryptedUserString {
	if x != nil {
		return x.EncryptedDisplayName
	}
	return nil
}

type UserAvatarSetEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Deprecated: legacy avatar storage pointer retained for decoding old
	// user events. New avatar writes append AssetCreatedEvent with
	// UserAvatarAssetOwner instead.
	UserId        string           `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Avatar        *DeprecatedAsset `protobuf:"bytes,2,opt,name=avatar,proto3" json:"avatar,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserAvatarSetEvent) Reset() {
	*x = UserAvatarSetEvent{}
	mi := &file_chatto_core_v1_user_events_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserAvatarSetEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserAvatarSetEvent) ProtoMessage() {}

func (x *UserAvatarSetEvent) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_core_v1_user_events_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserAvatarSetEvent.ProtoReflect.Descriptor instead.
func (*UserAvatarSetEvent) Descriptor() ([]byte, []int) {
	return file_chatto_core_v1_user_events_proto_rawDescGZIP(), []int{8}
}

func (x *UserAvatarSetEvent) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UserAvatarSetEvent) GetAvatar() *DeprecatedAsset {
	if x != nil {
		return x.Avatar
	}
	return nil
}

type UserAvatarClearedEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserAvatarClearedEvent) Reset() {
	*x = UserAvatarClearedEvent{}
	mi := &file_chatto_core_v1_user_events_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserAvatarClearedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserAvatarClearedEvent) ProtoMessage() {}

func (x *UserAvatarClearedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_core_v1_user_events_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserAvatarClearedEvent.ProtoReflect.Descriptor instead.
func (*UserAvatarClearedEvent) Descriptor() ([]byte, []int) {
	return file_chatto_core_v1_user_events_proto_rawDescGZIP(), []int{9}
}

func (x *UserAvatarClearedEvent) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type UserVerifiedEmailAddedEvent struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	UserId         string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	EncryptedEmail *EncryptedUserString   `protobuf:"bytes,10,opt,name=encrypted_email,json=encryptedEmail,proto3" json:"encrypted_email,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UserVerifiedEmailAddedEvent) Reset() {
	*x = UserVerifiedEmailAddedEvent{}
	mi := &file_chatto_core_v1_user_events_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserVerifiedEmailAddedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserVerifiedEmailAddedEvent) ProtoMessage() {}

func (x *UserVerifiedEmailAddedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_core_v1_user_events_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserVerifiedEmailAddedEvent.ProtoReflect.Descriptor instead.
func (*UserVerifiedEmailAddedEvent) Descriptor() ([]byte, []int) {
	return file_chatto_core_v1_user_events_proto_rawDescGZIP(), []int{10}
}

func (x *UserVerifiedEmailAddedEvent) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UserVerifiedEmailAddedEvent) GetEncryptedEmail() *EncryptedUserString {
	if x != nil {
		return x.EncryptedEmail
	}
	return nil
}

type UserPasswordHashChangedEvent struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	UserId       string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	PasswordHash []byte                 `protobuf:"bytes,2,opt,name=password_hash,json=passwordHash,proto3" json:"password_hash,omitempty"`
	// True when adding the first password to a passwordless account. Existing
	// sessions remain valid; later password changes and password resets leave
	// this false so they advance auth generation and revoke old credentials.
	PreserveExistingCredentials bool `protobuf:"varint,3,opt,name=preserve_existing_credentials,json=preserveExistingCredentials,proto3" json:"preserve_existing_credentials,omitempty"`
	unknownFields               protoimpl.UnknownFields
	sizeCache                   protoimpl.SizeCache
}

func (x *UserPasswordHashChangedEvent) Reset() {
	*x = UserPasswordHashChangedEvent{}
	mi := &file_chatto_core_v1_user_events_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserPasswordHashChangedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserPasswordHashChangedEvent) ProtoMessage() {}

func (x *UserPasswordHashChangedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_core_v1_user_events_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserPasswordHashChangedEvent.ProtoReflect.Descriptor instead.
func (*UserPasswordHashChangedEvent) Descriptor() ([]byte, []int) {
	return file_chatto_core_v1_user_events_proto_rawDescGZIP(), []int{11}
}

func (x *UserPasswordHashChangedEvent) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UserPasswordHashChangedEvent) GetPasswordHash() []byte {
	if x != nil {
		return x.PasswordHash
	}
	return nil
}

func (x *UserPasswordHashChangedEvent) GetPreserveExistingCredentials() bool {
	if x != nil {
		return x.PreserveExistingCredentials
	}
	return false
}

type UserOIDCSubjectLinkedEvent struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	UserId string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	// New writes include issuer/subject so the event is inspectable. Legacy
	// imports may only have the hash, because the old KV index key is one-way.
	Issuer        string `protobuf:"bytes,2,opt,name=issuer,proto3" json:"issuer,omitempty"`
	Subject       string `protobuf:"bytes,3,opt,name=subject,proto3" json:"subject,omitempty"`
	SubjectHash   string `protobuf:"bytes,4,opt,name=subject_hash,json=subjectHash,proto3" json:"subject_hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserOIDCSubjectLinkedEvent) Reset() {
	*x = UserOIDCSubjectLinkedEvent{}
	mi := &file_chatto_core_v1_user_events_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserOIDCSubjectLinkedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserOIDCSubjectLinkedEvent) ProtoMessage() {}

func (x *UserOIDCSubjectLinkedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_core_v1_user_events_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserOIDCSubjectLinkedEvent.ProtoReflect.Descriptor instead.
func (*UserOIDCSubjectLinkedEvent) Descriptor() ([]byte, []int) {
	return file_chatto_core_v1_user_events_proto_rawDescGZIP(), []int{12}
}

func (x *UserOIDCSubjectLinkedEvent) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UserOIDCSubjectLinkedEvent) GetIssuer() string {
	if x != nil {
		return x.Issuer
	}
	return ""
}

func (x *UserOIDCSubjectLinkedEvent) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *UserOIDCSubjectLinkedEvent) GetSubjectHash() string {
	if x != nil {
		return x.SubjectHash
	}
	return ""
}

type UserExternalIdentityLinkedEvent struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	UserId string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	// Durable identity namespace used for lookup. For OIDC providers this is the
	// verified issuer URL from the ID token, which lets the link survive local
	// provider ID or label changes. For OAuth-only providers this is the stable
	// configured local provider ID because there is no verified issuer URL.
	Issuer string `protobuf:"bytes,2,opt,name=issuer,proto3" json:"issuer,omitempty"`
	// Raw provider subjects are included only for events written after this
	// field existed. Projections prefer subject_hash when present.
	Subject     string `protobuf:"bytes,3,opt,name=subject,proto3" json:"subject,omitempty"`
	SubjectHash string `protobuf:"bytes,4,opt,name=subject_hash,json=subjectHash,proto3" json:"subject_hash,omitempty"`
	// Event-time metadata about the configured provider that created the link.
	// This is not dereferenced against current config during replay; providers
	// may be renamed, removed, or reconfigured without changing existing links.
	ProviderId    string `protobuf:"bytes,5,opt,name=provider_id,json=providerId,proto3" json:"provider_id,omitempty"`
	ProviderType  string `protobuf:"bytes,6,opt,name=provider_type,json=providerType,proto3" json:"provider_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserExternalIdentityLinkedEvent) Reset() {
	*x = UserExternalIdentityLinkedEvent{}
	mi := &file_chatto_core_v1_user_events_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserExternalIdentityLinkedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserExternalIdentityLinkedEvent) ProtoMessage() {}

func (x *UserExternalIdentityLinkedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_core_v1_user_events_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserExternalIdentityLinkedEvent.ProtoReflect.Descriptor instead.
func (*UserExternalIdentityLinkedEvent) Descriptor() ([]byte, []int) {
	return file_chatto_core_v1_user_events_proto_rawDescGZIP(), []int{13}
}

func (x *UserExternalIdentityLinkedEvent) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UserExternalIdentityLinkedEvent) GetIssuer() string {
	if x != nil {
		return x.Issuer
	}
	return ""
}

func (x *UserExternalIdentityLinkedEvent) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *UserExternalIdentityLinkedEvent) GetSubjectHash() string {
	if x != nil {
		return x.SubjectHash
	}
	return ""
}

func (x *UserExternalIdentityLinkedEvent) GetProviderId() string {
	if x != nil {
		return x.ProviderId
	}
	return ""
}

func (x *UserExternalIdentityLinkedEvent) GetProviderType() string {
	if x != nil {
		return x.ProviderType
	}
	return ""
}

type UserExternalIdentityUnlinkedEvent struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	UserId string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	// Stable one-way identity hash previously written by
	// UserExternalIdentityLinkedEvent or legacy UserOIDCSubjectLinkedEvent.
	SubjectHash   string `protobuf:"bytes,2,opt,name=subject_hash,json=subjectHash,proto3" json:"subject_hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserExternalIdentityUnlinkedEvent) Reset() {
	*x = UserExternalIdentityUnlinkedEvent{}
	mi := &file_chatto_core_v1_user_events_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserExternalIdentityUnlinkedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserExternalIdentityUnlinkedEvent) ProtoMessage() {}

func (x *UserExternalIdentityUnlinkedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_core_v1_user_events_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserExternalIdentityUnlinkedEvent.ProtoReflect.Descriptor instead.
func (*UserExternalIdentityUnlinkedEvent) Descriptor() ([]byte, []int) {
	return file_chatto_core_v1_user_events_proto_rawDescGZIP(), []int{14}
}

func (x *UserExternalIdentityUnlinkedEvent) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UserExternalIdentityUnlinkedEvent) GetSubjectHash() string {
	if x != nil {
		return x.SubjectHash
	}
	return ""
}

type UserServerPreferencesChangedEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Preferences   *ServerUserPreferences `protobuf:"bytes,2,opt,name=preferences,proto3" json:"preferences,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserServerPreferencesChangedEvent) Reset() {
	*x = UserServerPreferencesChangedEvent{}
	mi := &file_chatto_core_v1_user_events_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserServerPreferencesChangedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserServerPreferencesChangedEvent) ProtoMessage() {}

func (x *UserServerPreferencesChangedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_core_v1_user_events_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserServerPreferencesChangedEvent.ProtoReflect.Descriptor instead.
func (*UserServerPreferencesChangedEvent) Descriptor() ([]byte, []int) {
	return file_chatto_core_v1_user_events_proto_rawDescGZIP(), []int{15}
}

func (x *UserServerPreferencesChangedEvent) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UserServerPreferencesChangedEvent) GetPreferences() *ServerUserPreferences {
	if x != nil {
		return x.Preferences
	}
	return nil
}

type UserLoginCooldownStartedEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserLoginCooldownStartedEvent) Reset() {
	*x = UserLoginCooldownStartedEvent{}
	mi := &file_chatto_core_v1_user_events_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserLoginCooldownStartedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserLoginCooldownStartedEvent) ProtoMessage() {}

func (x *UserLoginCooldownStartedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_core_v1_user_events_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserLoginCooldownStartedEvent.ProtoReflect.Descriptor instead.
func (*UserLoginCooldownStartedEvent) Descriptor() ([]byte, []int) {
	return file_chatto_core_v1_user_events_proto_rawDescGZIP(), []int{16}
}

func (x *UserLoginCooldownStartedEvent) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type UserLoginCooldownClearedEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserLoginCooldownClearedEvent) Reset() {
	*x = UserLoginCooldownClearedEvent{}
	mi := &file_chatto_core_v1_user_events_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserLoginCooldownClearedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserLoginCooldownClearedEvent) ProtoMessage() {}

func (x *UserLoginCooldownClearedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_core_v1_user_events_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserLoginCooldownClearedEvent.ProtoReflect.Descriptor instead.
func (*UserLoginCooldownClearedEvent) Descriptor() ([]byte, []int) {
	return file_chatto_core_v1_user_events_proto_rawDescGZIP(), []int{17}
}

func (x *UserLoginCooldownClearedEvent) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type UserAccountDeletedEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserAccountDeletedEvent) Reset() {
	*x = UserAccountDeletedEvent{}
	mi := &file_chatto_core_v1_user_events_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserAccountDeletedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserAccountDeletedEvent) ProtoMessage() {}

func (x *UserAccountDeletedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_core_v1_user_events_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserAccountDeletedEvent.ProtoReflect.Descriptor instead.
func (*UserAccountDeletedEvent) Descriptor() ([]byte, []int) {
	return file_chatto_core_v1_user_events_proto_rawDescGZIP(), []int{18}
}

func (x *UserAccountDeletedEvent) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type UserCustomStatusSetEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Status        *CustomUserStatus      `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserCustomStatusSetEvent) Reset() {
	*x = UserCustomStatusSetEvent{}
	mi := &file_chatto_core_v1_user_events_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserCustomStatusSetEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserCustomStatusSetEvent) ProtoMessage() {}

func (x *UserCustomStatusSetEvent) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_core_v1_user_events_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserCustomStatusSetEvent.ProtoReflect.Descriptor instead.
func (*UserCustomStatusSetEvent) Descriptor() ([]byte, []int) {
	return file_chatto_core_v1_user_events_proto_rawDescGZIP(), []int{19}
}

func (x *UserCustomStatusSetEvent) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UserCustomStatusSetEvent) GetStatus() *CustomUserStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

type UserCustomStatusClearedEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserCustomStatusClearedEvent) Reset() {
	*x = UserCustomStatusClearedEvent{}
	mi := &file_chatto_core_v1_user_events_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserCustomStatusClearedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserCustomStatusClearedEvent) ProtoMessage() {}

func (x *UserCustomStatusClearedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_core_v1_user_events_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserCustomStatusClearedEvent.ProtoReflect.Descriptor instead.
func (*UserCustomStatusClearedEvent) Descriptor() ([]byte, []int) {
	return file_chatto_core_v1_user_events_proto_rawDescGZIP(), []int{20}
}

func (x *UserCustomStatusClearedEvent) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

// UserKeyShreddedEvent records physical completion of a user's
// crypto-shredding request. Historical readers also treat this event as the
// logical privacy boundary because events written before
// UserKeyShreddingRequestedEvent existed have no separate request fact.
type UserKeyShreddedEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserKeyShreddedEvent) Reset() {
	*x = UserKeyShreddedEvent{}
	mi := &file_chatto_core_v1_user_events_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserKeyShreddedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserKeyShreddedEvent) ProtoMessage() {}

func (x *UserKeyShreddedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_core_v1_user_events_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserKeyShreddedEvent.ProtoReflect.Descriptor instead.
func (*UserKeyShreddedEvent) Descriptor() ([]byte, []int) {
	return file_chatto_core_v1_user_events_proto_rawDescGZIP(), []int{21}
}

func (x *UserKeyShreddedEvent) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

// UserKeyShreddingRequestedEvent is the durable logical privacy boundary for
// user crypto-shredding. Workers reconstruct affected key coordinates from
// the user's immutable DEK-generation facts and surviving runtime DEK records
// before destructive work starts.
type UserKeyShreddingRequestedEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserKeyShreddingRequestedEvent) Reset() {
	*x = UserKeyShreddingRequestedEvent{}
	mi := &file_chatto_core_v1_user_events_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserKeyShreddingRequestedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserKeyShreddingRequestedEvent) ProtoMessage() {}

func (x *UserKeyShreddingRequestedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_core_v1_user_events_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserKeyShreddingRequestedEvent.ProtoReflect.Descriptor instead.
func (*UserKeyShreddingRequestedEvent) Descriptor() ([]byte, []int) {
	return file_chatto_core_v1_user_events_proto_rawDescGZIP(), []int{22}
}

func (x *UserKeyShreddingRequestedEvent) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

// UserDEKGeneratedEvent records the creation of one per-user data-encryption
// key epoch. Message bodies and PII payloads reference purpose-specific
// epochs; the wrapped key material lives in RUNTIME_STATE under
// content_key_ref so it can be shredded independently of immutable EVT history.
type UserDEKGeneratedEvent struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	UserId            string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Purpose           UserDEKPurpose         `protobuf:"varint,2,opt,name=purpose,proto3,enum=chatto.core.v1.UserDEKPurpose" json:"purpose,omitempty"`
	Epoch             int32                  `protobuf:"varint,3,opt,name=epoch,proto3" json:"epoch,omitempty"`
	ContentKeyRef     string                 `protobuf:"bytes,4,opt,name=content_key_ref,json=contentKeyRef,proto3" json:"content_key_ref,omitempty"`
	WrappingKeyRef    string                 `protobuf:"bytes,5,opt,name=wrapping_key_ref,json=wrappingKeyRef,proto3" json:"wrapping_key_ref,omitempty"`
	WrappingAlgorithm string                 `protobuf:"bytes,6,opt,name=wrapping_algorithm,json=wrappingAlgorithm,proto3" json:"wrapping_algorithm,omitempty"`
	WrappingMetadata  []byte                 `protobuf:"bytes,7,opt,name=wrapping_metadata,json=wrappingMetadata,proto3" json:"wrapping_metadata,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *UserDEKGeneratedEvent) Reset() {
	*x = UserDEKGeneratedEvent{}
	mi := &file_chatto_core_v1_user_events_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserDEKGeneratedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserDEKGeneratedEvent) ProtoMessage() {}

func (x *UserDEKGeneratedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_core_v1_user_events_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserDEKGeneratedEvent.ProtoReflect.Descriptor instead.
func (*UserDEKGeneratedEvent) Descriptor() ([]byte, []int) {
	return file_chatto_core_v1_user_events_proto_rawDescGZIP(), []int{23}
}

func (x *UserDEKGeneratedEvent) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UserDEKGeneratedEvent) GetPurpose() UserDEKPurpose {
	if x != nil {
		return x.Purpose
	}
	return UserDEKPurpose_USER_DEK_PURPOSE_UNSPECIFIED
}

func (x *UserDEKGeneratedEvent) GetEpoch() int32 {
	if x != nil {
		return x.Epoch
	}
	return 0
}

func (x *UserDEKGeneratedEvent) GetContentKeyRef() string {
	if x != nil {
		return x.ContentKeyRef
	}
	return ""
}

func (x *UserDEKGeneratedEvent) GetWrappingKeyRef() string {
	if x != nil {
		return x.WrappingKeyRef
	}
	return ""
}

func (x *UserDEKGeneratedEvent) GetWrappingAlgorithm() string {
	if x != nil {
		return x.WrappingAlgorithm
	}
	return ""
}

func (x *UserDEKGeneratedEvent) GetWrappingMetadata() []byte {
	if x != nil {
		return x.WrappingMetadata
	}
	return nil
}

var File_chatto_core_v1_user_events_proto protoreflect.FileDescriptor

const file_chatto_core_v1_user_events_proto_rawDesc = "" +
	"\n" +
	" chatto/core/v1/user_events.proto\x12\x0echatto.core.v1\x1a%chatto/core/v1/user_preferences.proto\x1a\x1bchatto/core/v1/models.proto\"d\n" +
	"\x10UserCreatedEvent\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x14\n" +
	"\x05login\x18\x02 \x01(\tR\x05login\x12!\n" +
	"\fdisplay_name\x18\x03 \x01(\tR\vdisplayName\"+\n" +
	"\x10UserDeletedEvent\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"\x8a\x01\n" +
	"\x17UserProfileUpdatedEvent\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12!\n" +
	"\fdisplay_name\x18\x02 \x01(\tR\vdisplayName\x12\x1d\n" +
	"\n" +
	"avatar_url\x18\x03 \x01(\tR\tavatarUrl\x12\x14\n" +
	"\x05login\x18\x04 \x01(\tR\x05login\"|\n" +
	"!ServerUserPreferencesUpdatedEvent\x12\x1a\n" +
	"\btimezone\x18\x01 \x01(\tR\btimezone\x12;\n" +
	"\vtime_format\x18\x02 \x01(\x0e2\x1a.chatto.core.v1.TimeFormatR\n" +
	"timeFormat\"\x80\x01\n" +
	"\x13EncryptedUserString\x12'\n" +
	"\x0fencrypted_value\x18\x01 \x01(\fR\x0eencryptedValue\x12\x14\n" +
	"\x05nonce\x18\x02 \x01(\fR\x05nonce\x12*\n" +
	"\x11content_key_epoch\x18\x03 \x01(\x05R\x0fcontentKeyEpoch\"\x89\x02\n" +
	"\x17UserAccountCreatedEvent\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12,\n" +
	"\x04kind\x18\x02 \x01(\x0e2\x18.chatto.core.v1.UserKindR\x04kind\x12L\n" +
	"\x0fencrypted_login\x18\n" +
	" \x01(\v2#.chatto.core.v1.EncryptedUserStringR\x0eencryptedLogin\x12Y\n" +
	"\x16encrypted_display_name\x18\v \x01(\v2#.chatto.core.v1.EncryptedUserStringR\x14encryptedDisplayName\"~\n" +
	"\x15UserLoginChangedEvent\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12L\n" +
	"\x0fencrypted_login\x18\n" +
	" \x01(\v2#.chatto.core.v1.EncryptedUserStringR\x0eencryptedLogin\"\x91\x01\n" +
	"\x1bUserDisplayNameChangedEvent\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12Y\n" +
	"\x16encrypted_display_name\x18\n" +
	" \x01(\v2#.chatto.core.v1.EncryptedUserStringR\x14encryptedDisplayName\"f\n" +
	"\x12UserAvatarSetEvent\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x127\n" +
	"\x06avatar\x18\x02 \x01(\v2\x1f.chatto.core.v1.DeprecatedAssetR\x06avatar\"1\n" +
	"\x16UserAvatarClearedEvent\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"\x84\x01\n" +
	"\x1bUserVerifiedEmailAddedEvent\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12L\n" +
	"\x0fencrypted_email\x18\n" +
	" \x01(\v2#.chatto.core.v1.EncryptedUserStringR\x0eencryptedEmail\"\xa0\x01\n" +
	"\x1cUserPasswordHashChangedEvent\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12#\n" +
	"\rpassword_hash\x18\x02 \x01(\fR\fpasswordHash\x12B\n" +
	"\x1dpreserve_existing_credentials\x18\x03 \x01(\bR\x1bpreserveExistingCredentials\"\x8a\x01\n" +
	"\x1aUserOIDCSubjectLinkedEvent\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x16\n" +
	"\x06issuer\x18\x02 \x01(\tR\x06issuer\x12\x18\n" +
	"\asubject\x18\x03 \x01(\tR\asubject\x12!\n" +
	"\fsubject_hash\x18\x04 \x01(\tR\vsubjectHash\"\xd5\x01\n" +
	"\x1fUserExternalIdentityLinkedEvent\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x16\n" +
	"\x06issuer\x18\x02 \x01(\tR\x06issuer\x12\x18\n" +
	"\asubject\x18\x03 \x01(\tR\asubject\x12!\n" +
	"\fsubject_hash\x18\x04 \x01(\tR\vsubjectHash\x12\x1f\n" +
	"\vprovider_id\x18\x05 \x01(\tR\n" +
	"providerId\x12#\n" +
	"\rprovider_type\x18\x06 \x01(\tR\fproviderType\"_\n" +
	"!UserExternalIdentityUnlinkedEvent\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12!\n" +
	"\fsubject_hash\x18\x02 \x01(\tR\vsubjectHash\"\x85\x01\n" +
	"!UserServerPreferencesChangedEvent\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12G\n" +
	"\vpreferences\x18\x02 \x01(\v2%.chatto.core.v1.ServerUserPreferencesR\vpreferences\"8\n" +
	"\x1dUserLoginCooldownStartedEvent\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"8\n" +
	"\x1dUserLoginCooldownClearedEvent\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"2\n" +
	"\x17UserAccountDeletedEvent\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"m\n" +
	"\x18UserCustomStatusSetEvent\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x128\n" +
	"\x06status\x18\x02 \x01(\v2 .chatto.core.v1.CustomUserStatusR\x06status\"7\n" +
	"\x1cUserCustomStatusClearedEvent\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"/\n" +
	"\x14UserKeyShreddedEvent\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"9\n" +
	"\x1eUserKeyShreddingRequestedEvent\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"\xae\x02\n" +
	"\x15UserDEKGeneratedEvent\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x128\n" +
	"\apurpose\x18\x02 \x01(\x0e2\x1e.chatto.core.v1.UserDEKPurposeR\apurpose\x12\x14\n" +
	"\x05epoch\x18\x03 \x01(\x05R\x05epoch\x12&\n" +
	"\x0fcontent_key_ref\x18\x04 \x01(\tR\rcontentKeyRef\x12(\n" +
	"\x10wrapping_key_ref\x18\x05 \x01(\tR\x0ewrappingKeyRef\x12-\n" +
	"\x12wrapping_algorithm\x18\x06 \x01(\tR\x11wrappingAlgorithm\x12+\n" +
	"\x11wrapping_metadata\x18\a \x01(\fR\x10wrappingMetadata*t\n" +
	"\x0eUserDEKPurpose\x12 \n" +
	"\x1cUSER_DEK_PURPOSE_UNSPECIFIED\x10\x00\x12!\n" +
	"\x1dUSER_DEK_PURPOSE_MESSAGE_BODY\x10\x01\x12\x1d\n" +
	"\x19USER_DEK_PURPOSE_USER_PII\x10\x02B\xb2\x01\n" +
	"\x12com.chatto.core.v1B\x0fUserEventsProtoP\x01Z1hmans.de/chatto/internal/pb/chatto/core/v1;corev1\xa2\x02\x03CCX\xaa\x02\x0eChatto.Core.V1\xca\x02\x0eChatto\\Core\\V1\xe2\x02\x1aChatto\\Core\\V1\\GPBMetadata\xea\x02\x10Chatto::Core::V1b\x06proto3"

var (
	file_chatto_core_v1_user_events_proto_rawDescOnce sync.Once
	file_chatto_core_v1_user_events_proto_rawDescData []byte
)

func file_chatto_core_v1_user_events_proto_rawDescGZIP() []byte {
	file_chatto_core_v1_user_events_proto_rawDescOnce.Do(func() {
		file_chatto_core_v1_user_events_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_chatto_core_v1_user_events_proto_rawDesc), len(file_chatto_core_v1_user_events_proto_rawDesc)))
	})
	return file_chatto_core_v1_user_events_proto_rawDescData
}

var file_chatto_core_v1_user_events_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_chatto_core_v1_user_events_proto_msgTypes = make([]protoimpl.MessageInfo, 24)
var file_chatto_core_v1_user_events_proto_goTypes = []any{
	(UserDEKPurpose)(0),                       // 0: chatto.core.v1.UserDEKPurpose
	(*UserCreatedEvent)(nil),                  // 1: chatto.core.v1.UserCreatedEvent
	(*UserDeletedEvent)(nil),                  // 2: chatto.core.v1.UserDeletedEvent
	(*UserProfileUpdatedEvent)(nil),           // 3: chatto.core.v1.UserProfileUpdatedEvent
	(*ServerUserPreferencesUpdatedEvent)(nil), // 4: chatto.core.v1.ServerUserPreferencesUpdatedEvent
	(*EncryptedUserString)(nil),               // 5: chatto.core.v1.EncryptedUserString
	(*UserAccountCreatedEvent)(nil),           // 6: chatto.core.v1.UserAccountCreatedEvent
	(*UserLoginChangedEvent)(nil),             // 7: chatto.core.v1.UserLoginChangedEvent
	(*UserDisplayNameChangedEvent)(nil),       // 8: chatto.core.v1.UserDisplayNameChangedEvent
	(*UserAvatarSetEvent)(nil),                // 9: chatto.core.v1.UserAvatarSetEvent
	(*UserAvatarClearedEvent)(nil),            // 10: chatto.core.v1.UserAvatarClearedEvent
	(*UserVerifiedEmailAddedEvent)(nil),       // 11: chatto.core.v1.UserVerifiedEmailAddedEvent
	(*UserPasswordHashChangedEvent)(nil),      // 12: chatto.core.v1.UserPasswordHashChangedEvent
	(*UserOIDCSubjectLinkedEvent)(nil),        // 13: chatto.core.v1.UserOIDCSubjectLinkedEvent
	(*UserExternalIdentityLinkedEvent)(nil),   // 14: chatto.core.v1.UserExternalIdentityLinkedEvent
	(*UserExternalIdentityUnlinkedEvent)(nil), // 15: chatto.core.v1.UserExternalIdentityUnlinkedEvent
	(*UserServerPreferencesChangedEvent)(nil), // 16: chatto.core.v1.UserServerPreferencesChangedEvent
	(*UserLoginCooldownStartedEvent)(nil),     // 17: chatto.core.v1.UserLoginCooldownStartedEvent
	(*UserLoginCooldownClearedEvent)(nil),     // 18: chatto.core.v1.UserLoginCooldownClearedEvent
	(*UserAccountDeletedEvent)(nil),           // 19: chatto.core.v1.UserAccountDeletedEvent
	(*UserCustomStatusSetEvent)(nil),          // 20: chatto.core.v1.UserCustomStatusSetEvent
	(*UserCustomStatusClearedEvent)(nil),      // 21: chatto.core.v1.UserCustomStatusClearedEvent
	(*UserKeyShreddedEvent)(nil),              // 22: chatto.core.v1.UserKeyShreddedEvent
	(*UserKeyShreddingRequestedEvent)(nil),    // 23: chatto.core.v1.UserKeyShreddingRequestedEvent
	(*UserDEKGeneratedEvent)(nil),             // 24: chatto.core.v1.UserDEKGeneratedEvent
	(TimeFormat)(0),                           // 25: chatto.core.v1.TimeFormat
	(UserKind)(0),                             // 26: chatto.core.v1.UserKind
	(*DeprecatedAsset)(nil),                   // 27: chatto.core.v1.DeprecatedAsset
	(*ServerUserPreferences)(nil),             // 28: chatto.core.v1.ServerUserPreferences
	(*CustomUserStatus)(nil),                  // 29: chatto.core.v1.CustomUserStatus
}
var file_chatto_core_v1_user_events_proto_depIdxs = []int32{
	25, // 0: chatto.core.v1.ServerUserPreferencesUpdatedEvent.time_format:type_name -> chatto.core.v1.TimeFormat
	26, // 1: chatto.core.v1.UserAccountCreatedEvent.kind:type_name -> chatto.core.v1.UserKind
	5,  // 2: chatto.core.v1.UserAccountCreatedEvent.encrypted_login:type_name -> chatto.core.v1.EncryptedUserString
	5,  // 3: chatto.core.v1.UserAccountCreatedEvent.encrypted_display_name:type_name -> chatto.core.v1.EncryptedUserString
	5,  // 4: chatto.core.v1.UserLoginChangedEvent.encrypted_login:type_name -> chatto.core.v1.EncryptedUserString
	5,  // 5: chatto.core.v1.UserDisplayNameChangedEvent.encrypted_display_name:type_name -> chatto.core.v1.EncryptedUserString
	27, // 6: chatto.core.v1.UserAvatarSetEvent.avatar:type_name -> chatto.core.v1.DeprecatedAsset
	5,  // 7: chatto.core.v1.UserVerifiedEmailAddedEvent.encrypted_email:type_name -> chatto.core.v1.EncryptedUserString
	28, // 8: chatto.core.v1.UserServerPreferencesChangedEvent.preferences:type_name -> chatto.core.v1.ServerUserPreferences
	29, // 9: chatto.core.v1.UserCustomStatusSetEvent.status:type_name -> chatto.core.v1.CustomUserStatus
	0,  // 10: chatto.core.v1.UserDEKGeneratedEvent.purpose:type_name -> chatto.core.v1.UserDEKPurpose
	11, // [11:11] is the sub-list for method output_type
	11, // [11:11] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_chatto_core_v1_user_events_proto_init() }
func file_chatto_core_v1_user_events_proto_init() {
	if File_chatto_core_v1_user_events_proto != nil {
		return
	}
	file_chatto_core_v1_user_preferences_proto_init()
	file_chatto_core_v1_models_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_chatto_core_v1_user_events_proto_rawDesc), len(file_chatto_core_v1_user_events_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   24,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_chatto_core_v1_user_events_proto_goTypes,
		DependencyIndexes: file_chatto_core_v1_user_events_proto_depIdxs,
		EnumInfos:         file_chatto_core_v1_user_events_proto_enumTypes,
		MessageInfos:      file_chatto_core_v1_user_events_proto_msgTypes,
	}.Build()
	File_chatto_core_v1_user_events_proto = out.File
	file_chatto_core_v1_user_events_proto_goTypes = nil
	file_chatto_core_v1_user_events_proto_depIdxs = nil
}
