// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: chatto/api/v1/push_notifications.proto

package apiv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "hmans.de/chatto/internal/pb/chatto/api/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// PushNotificationServiceName is the fully-qualified name of the PushNotificationService service.
	PushNotificationServiceName = "chatto.api.v1.PushNotificationService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// PushNotificationServiceSubscribeProcedure is the fully-qualified name of the
	// PushNotificationService's Subscribe RPC.
	PushNotificationServiceSubscribeProcedure = "/chatto.api.v1.PushNotificationService/Subscribe"
	// PushNotificationServiceUnsubscribeProcedure is the fully-qualified name of the
	// PushNotificationService's Unsubscribe RPC.
	PushNotificationServiceUnsubscribeProcedure = "/chatto.api.v1.PushNotificationService/Unsubscribe"
	// PushNotificationServiceSendTestNotificationProcedure is the fully-qualified name of the
	// PushNotificationService's SendTestNotification RPC.
	PushNotificationServiceSendTestNotificationProcedure = "/chatto.api.v1.PushNotificationService/SendTestNotification"
)

// PushNotificationServiceClient is a client for the chatto.api.v1.PushNotificationService service.
type PushNotificationServiceClient interface {
	// Stores or updates the caller's browser push subscription.
	//
	// The server must have Web Push configured. Clients normally call this after
	// the browser grants notification permission and returns a PushSubscription.
	Subscribe(context.Context, *connect.Request[v1.SubscribePushRequest]) (*connect.Response[v1.SubscribePushResponse], error)
	// Removes the caller's browser push subscription by endpoint.
	//
	// The call is idempotent: removing an unknown endpoint still succeeds.
	Unsubscribe(context.Context, *connect.Request[v1.UnsubscribePushRequest]) (*connect.Response[v1.UnsubscribePushResponse], error)
	// Sends a test notification to the caller's registered browser subscriptions.
	SendTestNotification(context.Context, *connect.Request[v1.SendTestPushNotificationRequest]) (*connect.Response[v1.SendTestPushNotificationResponse], error)
}

// NewPushNotificationServiceClient constructs a client for the
// chatto.api.v1.PushNotificationService service. By default, it uses the Connect protocol with the
// binary Protobuf Codec, asks for gzipped responses, and sends uncompressed requests. To use the
// gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewPushNotificationServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) PushNotificationServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	pushNotificationServiceMethods := v1.File_chatto_api_v1_push_notifications_proto.Services().ByName("PushNotificationService").Methods()
	return &pushNotificationServiceClient{
		subscribe: connect.NewClient[v1.SubscribePushRequest, v1.SubscribePushResponse](
			httpClient,
			baseURL+PushNotificationServiceSubscribeProcedure,
			connect.WithSchema(pushNotificationServiceMethods.ByName("Subscribe")),
			connect.WithClientOptions(opts...),
		),
		unsubscribe: connect.NewClient[v1.UnsubscribePushRequest, v1.UnsubscribePushResponse](
			httpClient,
			baseURL+PushNotificationServiceUnsubscribeProcedure,
			connect.WithSchema(pushNotificationServiceMethods.ByName("Unsubscribe")),
			connect.WithIdempotency(connect.IdempotencyIdempotent),
			connect.WithClientOptions(opts...),
		),
		sendTestNotification: connect.NewClient[v1.SendTestPushNotificationRequest, v1.SendTestPushNotificationResponse](
			httpClient,
			baseURL+PushNotificationServiceSendTestNotificationProcedure,
			connect.WithSchema(pushNotificationServiceMethods.ByName("SendTestNotification")),
			connect.WithClientOptions(opts...),
		),
	}
}

// pushNotificationServiceClient implements PushNotificationServiceClient.
type pushNotificationServiceClient struct {
	subscribe            *connect.Client[v1.SubscribePushRequest, v1.SubscribePushResponse]
	unsubscribe          *connect.Client[v1.UnsubscribePushRequest, v1.UnsubscribePushResponse]
	sendTestNotification *connect.Client[v1.SendTestPushNotificationRequest, v1.SendTestPushNotificationResponse]
}

// Subscribe calls chatto.api.v1.PushNotificationService.Subscribe.
func (c *pushNotificationServiceClient) Subscribe(ctx context.Context, req *connect.Request[v1.SubscribePushRequest]) (*connect.Response[v1.SubscribePushResponse], error) {
	return c.subscribe.CallUnary(ctx, req)
}

// Unsubscribe calls chatto.api.v1.PushNotificationService.Unsubscribe.
func (c *pushNotificationServiceClient) Unsubscribe(ctx context.Context, req *connect.Request[v1.UnsubscribePushRequest]) (*connect.Response[v1.UnsubscribePushResponse], error) {
	return c.unsubscribe.CallUnary(ctx, req)
}

// SendTestNotification calls chatto.api.v1.PushNotificationService.SendTestNotification.
func (c *pushNotificationServiceClient) SendTestNotification(ctx context.Context, req *connect.Request[v1.SendTestPushNotificationRequest]) (*connect.Response[v1.SendTestPushNotificationResponse], error) {
	return c.sendTestNotification.CallUnary(ctx, req)
}

// PushNotificationServiceHandler is an implementation of the chatto.api.v1.PushNotificationService
// service.
type PushNotificationServiceHandler interface {
	// Stores or updates the caller's browser push subscription.
	//
	// The server must have Web Push configured. Clients normally call this after
	// the browser grants notification permission and returns a PushSubscription.
	Subscribe(context.Context, *connect.Request[v1.SubscribePushRequest]) (*connect.Response[v1.SubscribePushResponse], error)
	// Removes the caller's browser push subscription by endpoint.
	//
	// The call is idempotent: removing an unknown endpoint still succeeds.
	Unsubscribe(context.Context, *connect.Request[v1.UnsubscribePushRequest]) (*connect.Response[v1.UnsubscribePushResponse], error)
	// Sends a test notification to the caller's registered browser subscriptions.
	SendTestNotification(context.Context, *connect.Request[v1.SendTestPushNotificationRequest]) (*connect.Response[v1.SendTestPushNotificationResponse], error)
}

// NewPushNotificationServiceHandler builds an HTTP handler from the service implementation. It
// returns the path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewPushNotificationServiceHandler(svc PushNotificationServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	pushNotificationServiceMethods := v1.File_chatto_api_v1_push_notifications_proto.Services().ByName("PushNotificationService").Methods()
	pushNotificationServiceSubscribeHandler := connect.NewUnaryHandler(
		PushNotificationServiceSubscribeProcedure,
		svc.Subscribe,
		connect.WithSchema(pushNotificationServiceMethods.ByName("Subscribe")),
		connect.WithHandlerOptions(opts...),
	)
	pushNotificationServiceUnsubscribeHandler := connect.NewUnaryHandler(
		PushNotificationServiceUnsubscribeProcedure,
		svc.Unsubscribe,
		connect.WithSchema(pushNotificationServiceMethods.ByName("Unsubscribe")),
		connect.WithIdempotency(connect.IdempotencyIdempotent),
		connect.WithHandlerOptions(opts...),
	)
	pushNotificationServiceSendTestNotificationHandler := connect.NewUnaryHandler(
		PushNotificationServiceSendTestNotificationProcedure,
		svc.SendTestNotification,
		connect.WithSchema(pushNotificationServiceMethods.ByName("SendTestNotification")),
		connect.WithHandlerOptions(opts...),
	)
	return "/chatto.api.v1.PushNotificationService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case PushNotificationServiceSubscribeProcedure:
			pushNotificationServiceSubscribeHandler.ServeHTTP(w, r)
		case PushNotificationServiceUnsubscribeProcedure:
			pushNotificationServiceUnsubscribeHandler.ServeHTTP(w, r)
		case PushNotificationServiceSendTestNotificationProcedure:
			pushNotificationServiceSendTestNotificationHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedPushNotificationServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedPushNotificationServiceHandler struct{}

func (UnimplementedPushNotificationServiceHandler) Subscribe(context.Context, *connect.Request[v1.SubscribePushRequest]) (*connect.Response[v1.SubscribePushResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("chatto.api.v1.PushNotificationService.Subscribe is not implemented"))
}

func (UnimplementedPushNotificationServiceHandler) Unsubscribe(context.Context, *connect.Request[v1.UnsubscribePushRequest]) (*connect.Response[v1.UnsubscribePushResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("chatto.api.v1.PushNotificationService.Unsubscribe is not implemented"))
}

func (UnimplementedPushNotificationServiceHandler) SendTestNotification(context.Context, *connect.Request[v1.SendTestPushNotificationRequest]) (*connect.Response[v1.SendTestPushNotificationResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("chatto.api.v1.PushNotificationService.SendTestNotification is not implemented"))
}
