// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: chatto/api/v1/message_actions.proto

package apiv1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/descriptorpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Visual treatment for a message action button.
type MessageActionStyle int32

const (
	// Uses the normal secondary button treatment.
	MessageActionStyle_MESSAGE_ACTION_STYLE_UNSPECIFIED MessageActionStyle = 0
	// Emphasises the primary action.
	MessageActionStyle_MESSAGE_ACTION_STYLE_PRIMARY MessageActionStyle = 1
	// Uses the normal secondary button treatment.
	MessageActionStyle_MESSAGE_ACTION_STYLE_SECONDARY MessageActionStyle = 2
	// Indicates a successful or affirmative action.
	MessageActionStyle_MESSAGE_ACTION_STYLE_SUCCESS MessageActionStyle = 3
	// Indicates a destructive or dangerous action.
	MessageActionStyle_MESSAGE_ACTION_STYLE_DANGER MessageActionStyle = 4
)

// Enum value maps for MessageActionStyle.
var (
	MessageActionStyle_name = map[int32]string{
		0: "MESSAGE_ACTION_STYLE_UNSPECIFIED",
		1: "MESSAGE_ACTION_STYLE_PRIMARY",
		2: "MESSAGE_ACTION_STYLE_SECONDARY",
		3: "MESSAGE_ACTION_STYLE_SUCCESS",
		4: "MESSAGE_ACTION_STYLE_DANGER",
	}
	MessageActionStyle_value = map[string]int32{
		"MESSAGE_ACTION_STYLE_UNSPECIFIED": 0,
		"MESSAGE_ACTION_STYLE_PRIMARY":     1,
		"MESSAGE_ACTION_STYLE_SECONDARY":   2,
		"MESSAGE_ACTION_STYLE_SUCCESS":     3,
		"MESSAGE_ACTION_STYLE_DANGER":      4,
	}
)

func (x MessageActionStyle) Enum() *MessageActionStyle {
	p := new(MessageActionStyle)
	*p = x
	return p
}

func (x MessageActionStyle) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MessageActionStyle) Descriptor() protoreflect.EnumDescriptor {
	return file_chatto_api_v1_message_actions_proto_enumTypes[0].Descriptor()
}

func (MessageActionStyle) Type() protoreflect.EnumType {
	return &file_chatto_api_v1_message_actions_proto_enumTypes[0]
}

func (x MessageActionStyle) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MessageActionStyle.Descriptor instead.
func (MessageActionStyle) EnumDescriptor() ([]byte, []int) {
	return file_chatto_api_v1_message_actions_proto_rawDescGZIP(), []int{0}
}

// Author-defined button attached to a message.
//
// The action ID is opaque integration data visible to room members and
// returned to the message author when a member invokes the button. Chatto does
// not interpret it.
type MessageAction struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Stable integration-defined ID within this message.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Visible button label.
	Label string `protobuf:"bytes,2,opt,name=label,proto3" json:"label,omitempty"`
	// Visual treatment. Unspecified uses the secondary treatment.
	Style MessageActionStyle `protobuf:"varint,3,opt,name=style,proto3,enum=chatto.api.v1.MessageActionStyle" json:"style,omitempty"`
	// Whether the button is visible but cannot currently be invoked.
	Disabled      bool `protobuf:"varint,4,opt,name=disabled,proto3" json:"disabled,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageAction) Reset() {
	*x = MessageAction{}
	mi := &file_chatto_api_v1_message_actions_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageAction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageAction) ProtoMessage() {}

func (x *MessageAction) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_api_v1_message_actions_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageAction.ProtoReflect.Descriptor instead.
func (*MessageAction) Descriptor() ([]byte, []int) {
	return file_chatto_api_v1_message_actions_proto_rawDescGZIP(), []int{0}
}

func (x *MessageAction) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *MessageAction) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *MessageAction) GetStyle() MessageActionStyle {
	if x != nil {
		return x.Style
	}
	return MessageActionStyle_MESSAGE_ACTION_STYLE_UNSPECIFIED
}

func (x *MessageAction) GetDisabled() bool {
	if x != nil {
		return x.Disabled
	}
	return false
}

// Complete replacement set used when creating or updating a message.
type MessageActionSet struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Ordered action buttons. IDs must be unique within the set.
	Actions       []*MessageAction `protobuf:"bytes,1,rep,name=actions,proto3" json:"actions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageActionSet) Reset() {
	*x = MessageActionSet{}
	mi := &file_chatto_api_v1_message_actions_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageActionSet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageActionSet) ProtoMessage() {}

func (x *MessageActionSet) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_api_v1_message_actions_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageActionSet.ProtoReflect.Descriptor instead.
func (*MessageActionSet) Descriptor() ([]byte, []int) {
	return file_chatto_api_v1_message_actions_proto_rawDescGZIP(), []int{1}
}

func (x *MessageActionSet) GetActions() []*MessageAction {
	if x != nil {
		return x.Actions
	}
	return nil
}

// One pending action invocation delivered privately to the message author.
type MessageActionInvocation struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Caller-supplied idempotency key and stable invocation ID.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Room containing the message.
	RoomId string `protobuf:"bytes,2,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	// Canonical message event ID. Invocations made from a thread echo refer to
	// the original message event.
	MessageEventId string `protobuf:"bytes,3,opt,name=message_event_id,json=messageEventId,proto3" json:"message_event_id,omitempty"`
	// Integration-defined action ID from the message.
	ActionId string `protobuf:"bytes,4,opt,name=action_id,json=actionId,proto3" json:"action_id,omitempty"`
	// User who invoked the action.
	ActorId string `protobuf:"bytes,5,opt,name=actor_id,json=actorId,proto3" json:"actor_id,omitempty"`
	// Time when Chatto accepted the invocation.
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageActionInvocation) Reset() {
	*x = MessageActionInvocation{}
	mi := &file_chatto_api_v1_message_actions_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageActionInvocation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageActionInvocation) ProtoMessage() {}

func (x *MessageActionInvocation) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_api_v1_message_actions_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageActionInvocation.ProtoReflect.Descriptor instead.
func (*MessageActionInvocation) Descriptor() ([]byte, []int) {
	return file_chatto_api_v1_message_actions_proto_rawDescGZIP(), []int{2}
}

func (x *MessageActionInvocation) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *MessageActionInvocation) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *MessageActionInvocation) GetMessageEventId() string {
	if x != nil {
		return x.MessageEventId
	}
	return ""
}

func (x *MessageActionInvocation) GetActionId() string {
	if x != nil {
		return x.ActionId
	}
	return ""
}

func (x *MessageActionInvocation) GetActorId() string {
	if x != nil {
		return x.ActorId
	}
	return ""
}

func (x *MessageActionInvocation) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

// Request to invoke one enabled action on a visible message.
type InvokeMessageActionRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required. Room containing the message.
	RoomId string `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	// Required. Message event ID as rendered to the caller.
	MessageEventId string `protobuf:"bytes,2,opt,name=message_event_id,json=messageEventId,proto3" json:"message_event_id,omitempty"`
	// Required. Action ID attached to the message.
	ActionId string `protobuf:"bytes,3,opt,name=action_id,json=actionId,proto3" json:"action_id,omitempty"`
	// Required. Random client-generated idempotency key. Retrying the same
	// request with this key returns the original invocation.
	RequestId     string `protobuf:"bytes,4,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InvokeMessageActionRequest) Reset() {
	*x = InvokeMessageActionRequest{}
	mi := &file_chatto_api_v1_message_actions_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InvokeMessageActionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvokeMessageActionRequest) ProtoMessage() {}

func (x *InvokeMessageActionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_api_v1_message_actions_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvokeMessageActionRequest.ProtoReflect.Descriptor instead.
func (*InvokeMessageActionRequest) Descriptor() ([]byte, []int) {
	return file_chatto_api_v1_message_actions_proto_rawDescGZIP(), []int{3}
}

func (x *InvokeMessageActionRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *InvokeMessageActionRequest) GetMessageEventId() string {
	if x != nil {
		return x.MessageEventId
	}
	return ""
}

func (x *InvokeMessageActionRequest) GetActionId() string {
	if x != nil {
		return x.ActionId
	}
	return ""
}

func (x *InvokeMessageActionRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

// Result of invoking a message action.
type InvokeMessageActionResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Accepted pending invocation.
	Invocation    *MessageActionInvocation `protobuf:"bytes,1,opt,name=invocation,proto3" json:"invocation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InvokeMessageActionResponse) Reset() {
	*x = InvokeMessageActionResponse{}
	mi := &file_chatto_api_v1_message_actions_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InvokeMessageActionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvokeMessageActionResponse) ProtoMessage() {}

func (x *InvokeMessageActionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_api_v1_message_actions_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvokeMessageActionResponse.ProtoReflect.Descriptor instead.
func (*InvokeMessageActionResponse) Descriptor() ([]byte, []int) {
	return file_chatto_api_v1_message_actions_proto_rawDescGZIP(), []int{4}
}

func (x *InvokeMessageActionResponse) GetInvocation() *MessageActionInvocation {
	if x != nil {
		return x.Invocation
	}
	return nil
}

// Request for pending invocations owned by the authenticated message author.
type ListMessageActionInvocationsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Page request. Defaults to 50 results when absent or limit is zero.
	Page          *PageRequest `protobuf:"bytes,1,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMessageActionInvocationsRequest) Reset() {
	*x = ListMessageActionInvocationsRequest{}
	mi := &file_chatto_api_v1_message_actions_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMessageActionInvocationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMessageActionInvocationsRequest) ProtoMessage() {}

func (x *ListMessageActionInvocationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_api_v1_message_actions_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMessageActionInvocationsRequest.ProtoReflect.Descriptor instead.
func (*ListMessageActionInvocationsRequest) Descriptor() ([]byte, []int) {
	return file_chatto_api_v1_message_actions_proto_rawDescGZIP(), []int{5}
}

func (x *ListMessageActionInvocationsRequest) GetPage() *PageRequest {
	if x != nil {
		return x.Page
	}
	return nil
}

// Page of pending action invocations.
type ListMessageActionInvocationsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Pending invocations, oldest first.
	Invocations []*MessageActionInvocation `protobuf:"bytes,1,rep,name=invocations,proto3" json:"invocations,omitempty"`
	// Page metadata.
	Page          *PageInfo `protobuf:"bytes,2,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMessageActionInvocationsResponse) Reset() {
	*x = ListMessageActionInvocationsResponse{}
	mi := &file_chatto_api_v1_message_actions_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMessageActionInvocationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMessageActionInvocationsResponse) ProtoMessage() {}

func (x *ListMessageActionInvocationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_api_v1_message_actions_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMessageActionInvocationsResponse.ProtoReflect.Descriptor instead.
func (*ListMessageActionInvocationsResponse) Descriptor() ([]byte, []int) {
	return file_chatto_api_v1_message_actions_proto_rawDescGZIP(), []int{6}
}

func (x *ListMessageActionInvocationsResponse) GetInvocations() []*MessageActionInvocation {
	if x != nil {
		return x.Invocations
	}
	return nil
}

func (x *ListMessageActionInvocationsResponse) GetPage() *PageInfo {
	if x != nil {
		return x.Page
	}
	return nil
}

// Request to acknowledge one pending action invocation.
type AcknowledgeMessageActionInvocationRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required. Invocation owned by the authenticated message author.
	InvocationId  string `protobuf:"bytes,1,opt,name=invocation_id,json=invocationId,proto3" json:"invocation_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AcknowledgeMessageActionInvocationRequest) Reset() {
	*x = AcknowledgeMessageActionInvocationRequest{}
	mi := &file_chatto_api_v1_message_actions_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcknowledgeMessageActionInvocationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcknowledgeMessageActionInvocationRequest) ProtoMessage() {}

func (x *AcknowledgeMessageActionInvocationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_api_v1_message_actions_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcknowledgeMessageActionInvocationRequest.ProtoReflect.Descriptor instead.
func (*AcknowledgeMessageActionInvocationRequest) Descriptor() ([]byte, []int) {
	return file_chatto_api_v1_message_actions_proto_rawDescGZIP(), []int{7}
}

func (x *AcknowledgeMessageActionInvocationRequest) GetInvocationId() string {
	if x != nil {
		return x.InvocationId
	}
	return ""
}

// Result of acknowledging an action invocation.
type AcknowledgeMessageActionInvocationResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// True when the invocation is no longer pending.
	Acknowledged  bool `protobuf:"varint,1,opt,name=acknowledged,proto3" json:"acknowledged,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AcknowledgeMessageActionInvocationResponse) Reset() {
	*x = AcknowledgeMessageActionInvocationResponse{}
	mi := &file_chatto_api_v1_message_actions_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcknowledgeMessageActionInvocationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcknowledgeMessageActionInvocationResponse) ProtoMessage() {}

func (x *AcknowledgeMessageActionInvocationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_api_v1_message_actions_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcknowledgeMessageActionInvocationResponse.ProtoReflect.Descriptor instead.
func (*AcknowledgeMessageActionInvocationResponse) Descriptor() ([]byte, []int) {
	return file_chatto_api_v1_message_actions_proto_rawDescGZIP(), []int{8}
}

func (x *AcknowledgeMessageActionInvocationResponse) GetAcknowledged() bool {
	if x != nil {
		return x.Acknowledged
	}
	return false
}

var File_chatto_api_v1_message_actions_proto protoreflect.FileDescriptor

const file_chatto_api_v1_message_actions_proto_rawDesc = "" +
	"\n" +
	"#chatto/api/v1/message_actions.proto\x12\rchatto.api.v1\x1a\x1bbuf/validate/validate.proto\x1a\x1echatto/api/v1/pagination.proto\x1a google/protobuf/descriptor.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xbc\x01\n" +
	"\rMessageAction\x12+\n" +
	"\x02id\x18\x01 \x01(\tB\x1b\xbaH\x18r\x16\x10\x01\x18@2\x10^[A-Za-z0-9_-]+$R\x02id\x12\x1f\n" +
	"\x05label\x18\x02 \x01(\tB\t\xbaH\x06r\x04\x10\x01(PR\x05label\x12A\n" +
	"\x05style\x18\x03 \x01(\x0e2!.chatto.api.v1.MessageActionStyleB\b\xbaH\x05\x82\x01\x02\x10\x01R\x05style\x12\x1a\n" +
	"\bdisabled\x18\x04 \x01(\bR\bdisabled\"T\n" +
	"\x10MessageActionSet\x12@\n" +
	"\aactions\x18\x01 \x03(\v2\x1c.chatto.api.v1.MessageActionB\b\xbaH\x05\x92\x01\x02\x10\x05R\aactions\"\xdf\x01\n" +
	"\x17MessageActionInvocation\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\aroom_id\x18\x02 \x01(\tR\x06roomId\x12(\n" +
	"\x10message_event_id\x18\x03 \x01(\tR\x0emessageEventId\x12\x1b\n" +
	"\taction_id\x18\x04 \x01(\tR\bactionId\x12\x19\n" +
	"\bactor_id\x18\x05 \x01(\tR\aactorId\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"\xe7\x01\n" +
	"\x1aInvokeMessageActionRequest\x12 \n" +
	"\aroom_id\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x06roomId\x121\n" +
	"\x10message_event_id\x18\x02 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x0emessageEventId\x128\n" +
	"\taction_id\x18\x03 \x01(\tB\x1b\xbaH\x18r\x16\x10\x01\x18@2\x10^[A-Za-z0-9_-]+$R\bactionId\x12:\n" +
	"\n" +
	"request_id\x18\x04 \x01(\tB\x1b\xbaH\x18r\x16\x10\x10\x18@2\x10^[A-Za-z0-9_-]+$R\trequestId\"e\n" +
	"\x1bInvokeMessageActionResponse\x12F\n" +
	"\n" +
	"invocation\x18\x01 \x01(\v2&.chatto.api.v1.MessageActionInvocationR\n" +
	"invocation\"U\n" +
	"#ListMessageActionInvocationsRequest\x12.\n" +
	"\x04page\x18\x01 \x01(\v2\x1a.chatto.api.v1.PageRequestR\x04page\"\x9d\x01\n" +
	"$ListMessageActionInvocationsResponse\x12H\n" +
	"\vinvocations\x18\x01 \x03(\v2&.chatto.api.v1.MessageActionInvocationR\vinvocations\x12+\n" +
	"\x04page\x18\x02 \x01(\v2\x17.chatto.api.v1.PageInfoR\x04page\"m\n" +
	")AcknowledgeMessageActionInvocationRequest\x12@\n" +
	"\rinvocation_id\x18\x01 \x01(\tB\x1b\xbaH\x18r\x16\x10\x10\x18@2\x10^[A-Za-z0-9_-]+$R\finvocationId\"P\n" +
	"*AcknowledgeMessageActionInvocationResponse\x12\"\n" +
	"\facknowledged\x18\x01 \x01(\bR\facknowledged*\xc3\x01\n" +
	"\x12MessageActionStyle\x12$\n" +
	" MESSAGE_ACTION_STYLE_UNSPECIFIED\x10\x00\x12 \n" +
	"\x1cMESSAGE_ACTION_STYLE_PRIMARY\x10\x01\x12\"\n" +
	"\x1eMESSAGE_ACTION_STYLE_SECONDARY\x10\x02\x12 \n" +
	"\x1cMESSAGE_ACTION_STYLE_SUCCESS\x10\x03\x12\x1f\n" +
	"\x1bMESSAGE_ACTION_STYLE_DANGER\x10\x042\xb4\x03\n" +
	"\x14MessageActionService\x12q\n" +
	"\x13InvokeMessageAction\x12).chatto.api.v1.InvokeMessageActionRequest\x1a*.chatto.api.v1.InvokeMessageActionResponse\"\x03\x90\x02\x02\x12\x87\x01\n" +
	"\x1cListMessageActionInvocations\x122.chatto.api.v1.ListMessageActionInvocationsRequest\x1a3.chatto.api.v1.ListMessageActionInvocationsResponse\x12\x9e\x01\n" +
	"\"AcknowledgeMessageActionInvocation\x128.chatto.api.v1.AcknowledgeMessageActionInvocationRequest\x1a9.chatto.api.v1.AcknowledgeMessageActionInvocationResponse\"\x03\x90\x02\x02B\xaf\x01\n" +
	"\x11com.chatto.api.v1B\x13MessageActionsProtoP\x01Z/hmans.de/chatto/internal/pb/chatto/api/v1;apiv1\xa2\x02\x03CAX\xaa\x02\rChatto.Api.V1\xca\x02\rChatto\\Api\\V1\xe2\x02\x19Chatto\\Api\\V1\\GPBMetadata\xea\x02\x0fChatto::Api::V1b\x06proto3"

var (
	file_chatto_api_v1_message_actions_proto_rawDescOnce sync.Once
	file_chatto_api_v1_message_actions_proto_rawDescData []byte
)

func file_chatto_api_v1_message_actions_proto_rawDescGZIP() []byte {
	file_chatto_api_v1_message_actions_proto_rawDescOnce.Do(func() {
		file_chatto_api_v1_message_actions_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_chatto_api_v1_message_actions_proto_rawDesc), len(file_chatto_api_v1_message_actions_proto_rawDesc)))
	})
	return file_chatto_api_v1_message_actions_proto_rawDescData
}

var file_chatto_api_v1_message_actions_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_chatto_api_v1_message_actions_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_chatto_api_v1_message_actions_proto_goTypes = []any{
	(MessageActionStyle)(0),                            // 0: chatto.api.v1.MessageActionStyle
	(*MessageAction)(nil),                              // 1: chatto.api.v1.MessageAction
	(*MessageActionSet)(nil),                           // 2: chatto.api.v1.MessageActionSet
	(*MessageActionInvocation)(nil),                    // 3: chatto.api.v1.MessageActionInvocation
	(*InvokeMessageActionRequest)(nil),                 // 4: chatto.api.v1.InvokeMessageActionRequest
	(*InvokeMessageActionResponse)(nil),                // 5: chatto.api.v1.InvokeMessageActionResponse
	(*ListMessageActionInvocationsRequest)(nil),        // 6: chatto.api.v1.ListMessageActionInvocationsRequest
	(*ListMessageActionInvocationsResponse)(nil),       // 7: chatto.api.v1.ListMessageActionInvocationsResponse
	(*AcknowledgeMessageActionInvocationRequest)(nil),  // 8: chatto.api.v1.AcknowledgeMessageActionInvocationRequest
	(*AcknowledgeMessageActionInvocationResponse)(nil), // 9: chatto.api.v1.AcknowledgeMessageActionInvocationResponse
	(*timestamppb.Timestamp)(nil),                      // 10: google.protobuf.Timestamp
	(*PageRequest)(nil),                                // 11: chatto.api.v1.PageRequest
	(*PageInfo)(nil),                                   // 12: chatto.api.v1.PageInfo
}
var file_chatto_api_v1_message_actions_proto_depIdxs = []int32{
	0,  // 0: chatto.api.v1.MessageAction.style:type_name -> chatto.api.v1.MessageActionStyle
	1,  // 1: chatto.api.v1.MessageActionSet.actions:type_name -> chatto.api.v1.MessageAction
	10, // 2: chatto.api.v1.MessageActionInvocation.created_at:type_name -> google.protobuf.Timestamp
	3,  // 3: chatto.api.v1.InvokeMessageActionResponse.invocation:type_name -> chatto.api.v1.MessageActionInvocation
	11, // 4: chatto.api.v1.ListMessageActionInvocationsRequest.page:type_name -> chatto.api.v1.PageRequest
	3,  // 5: chatto.api.v1.ListMessageActionInvocationsResponse.invocations:type_name -> chatto.api.v1.MessageActionInvocation
	12, // 6: chatto.api.v1.ListMessageActionInvocationsResponse.page:type_name -> chatto.api.v1.PageInfo
	4,  // 7: chatto.api.v1.MessageActionService.InvokeMessageAction:input_type -> chatto.api.v1.InvokeMessageActionRequest
	6,  // 8: chatto.api.v1.MessageActionService.ListMessageActionInvocations:input_type -> chatto.api.v1.ListMessageActionInvocationsRequest
	8,  // 9: chatto.api.v1.MessageActionService.AcknowledgeMessageActionInvocation:input_type -> chatto.api.v1.AcknowledgeMessageActionInvocationRequest
	5,  // 10: chatto.api.v1.MessageActionService.InvokeMessageAction:output_type -> chatto.api.v1.InvokeMessageActionResponse
	7,  // 11: chatto.api.v1.MessageActionService.ListMessageActionInvocations:output_type -> chatto.api.v1.ListMessageActionInvocationsResponse
	9,  // 12: chatto.api.v1.MessageActionService.AcknowledgeMessageActionInvocation:output_type -> chatto.api.v1.AcknowledgeMessageActionInvocationResponse
	10, // [10:13] is the sub-list for method output_type
	7,  // [7:10] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_chatto_api_v1_message_actions_proto_init() }
func file_chatto_api_v1_message_actions_proto_init() {
	if File_chatto_api_v1_message_actions_proto != nil {
		return
	}
	file_chatto_api_v1_pagination_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_chatto_api_v1_message_actions_proto_rawDesc), len(file_chatto_api_v1_message_actions_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_chatto_api_v1_message_actions_proto_goTypes,
		DependencyIndexes: file_chatto_api_v1_message_actions_proto_depIdxs,
		EnumInfos:         file_chatto_api_v1_message_actions_proto_enumTypes,
		MessageInfos:      file_chatto_api_v1_message_actions_proto_msgTypes,
	}.Build()
	File_chatto_api_v1_message_actions_proto = out.File
	file_chatto_api_v1_message_actions_proto_goTypes = nil
	file_chatto_api_v1_message_actions_proto_depIdxs = nil
}
