// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: chatto/api/v1/permissions.proto

package apiv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Effective decision for one permission key.
type PermissionGrant struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Stable permission key, such as "server.manage".
	Permission string `protobuf:"bytes,1,opt,name=permission,proto3" json:"permission,omitempty"`
	// Whether the permission is currently granted.
	Granted       bool `protobuf:"varint,2,opt,name=granted,proto3" json:"granted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PermissionGrant) Reset() {
	*x = PermissionGrant{}
	mi := &file_chatto_api_v1_permissions_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PermissionGrant) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PermissionGrant) ProtoMessage() {}

func (x *PermissionGrant) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_api_v1_permissions_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PermissionGrant.ProtoReflect.Descriptor instead.
func (*PermissionGrant) Descriptor() ([]byte, []int) {
	return file_chatto_api_v1_permissions_proto_rawDescGZIP(), []int{0}
}

func (x *PermissionGrant) GetPermission() string {
	if x != nil {
		return x.Permission
	}
	return ""
}

func (x *PermissionGrant) GetGranted() bool {
	if x != nil {
		return x.Granted
	}
	return false
}

// Effective decision for one capability key.
//
// Built-in keys currently include:
// - admin.view
// - dm.start
// - admin.view-users
// - user.manage-accounts
// - user.invite
// - role.assign
// - role.view
// - role.manage
// - admin.view-system
// - admin.view-audit
// - user.manage-permissions
//
// Clients should ignore unknown keys so servers can add capabilities over time.
type CapabilityGrant struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Stable capability key, such as "admin.view" or "dm.start".
	Capability string `protobuf:"bytes,1,opt,name=capability,proto3" json:"capability,omitempty"`
	// Whether the capability is currently available.
	Granted       bool `protobuf:"varint,2,opt,name=granted,proto3" json:"granted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CapabilityGrant) Reset() {
	*x = CapabilityGrant{}
	mi := &file_chatto_api_v1_permissions_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CapabilityGrant) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CapabilityGrant) ProtoMessage() {}

func (x *CapabilityGrant) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_api_v1_permissions_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CapabilityGrant.ProtoReflect.Descriptor instead.
func (*CapabilityGrant) Descriptor() ([]byte, []int) {
	return file_chatto_api_v1_permissions_proto_rawDescGZIP(), []int{1}
}

func (x *CapabilityGrant) GetCapability() string {
	if x != nil {
		return x.Capability
	}
	return ""
}

func (x *CapabilityGrant) GetGranted() bool {
	if x != nil {
		return x.Granted
	}
	return false
}

var File_chatto_api_v1_permissions_proto protoreflect.FileDescriptor

const file_chatto_api_v1_permissions_proto_rawDesc = "" +
	"\n" +
	"\x1fchatto/api/v1/permissions.proto\x12\rchatto.api.v1\"K\n" +
	"\x0fPermissionGrant\x12\x1e\n" +
	"\n" +
	"permission\x18\x01 \x01(\tR\n" +
	"permission\x12\x18\n" +
	"\agranted\x18\x02 \x01(\bR\agranted\"K\n" +
	"\x0fCapabilityGrant\x12\x1e\n" +
	"\n" +
	"capability\x18\x01 \x01(\tR\n" +
	"capability\x12\x18\n" +
	"\agranted\x18\x02 \x01(\bR\agrantedB\xac\x01\n" +
	"\x11com.chatto.api.v1B\x10PermissionsProtoP\x01Z/hmans.de/chatto/internal/pb/chatto/api/v1;apiv1\xa2\x02\x03CAX\xaa\x02\rChatto.Api.V1\xca\x02\rChatto\\Api\\V1\xe2\x02\x19Chatto\\Api\\V1\\GPBMetadata\xea\x02\x0fChatto::Api::V1b\x06proto3"

var (
	file_chatto_api_v1_permissions_proto_rawDescOnce sync.Once
	file_chatto_api_v1_permissions_proto_rawDescData []byte
)

func file_chatto_api_v1_permissions_proto_rawDescGZIP() []byte {
	file_chatto_api_v1_permissions_proto_rawDescOnce.Do(func() {
		file_chatto_api_v1_permissions_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_chatto_api_v1_permissions_proto_rawDesc), len(file_chatto_api_v1_permissions_proto_rawDesc)))
	})
	return file_chatto_api_v1_permissions_proto_rawDescData
}

var file_chatto_api_v1_permissions_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_chatto_api_v1_permissions_proto_goTypes = []any{
	(*PermissionGrant)(nil), // 0: chatto.api.v1.PermissionGrant
	(*CapabilityGrant)(nil), // 1: chatto.api.v1.CapabilityGrant
}
var file_chatto_api_v1_permissions_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_chatto_api_v1_permissions_proto_init() }
func file_chatto_api_v1_permissions_proto_init() {
	if File_chatto_api_v1_permissions_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_chatto_api_v1_permissions_proto_rawDesc), len(file_chatto_api_v1_permissions_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_chatto_api_v1_permissions_proto_goTypes,
		DependencyIndexes: file_chatto_api_v1_permissions_proto_depIdxs,
		MessageInfos:      file_chatto_api_v1_permissions_proto_msgTypes,
	}.Build()
	File_chatto_api_v1_permissions_proto = out.File
	file_chatto_api_v1_permissions_proto_goTypes = nil
	file_chatto_api_v1_permissions_proto_depIdxs = nil
}
