// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: chatto/api/v1/rooms.proto

package apiv1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Kind of room represented by the public API.
type RoomKind int32

const (
	// The room kind was not specified.
	RoomKind_ROOM_KIND_UNSPECIFIED RoomKind = 0
	// A regular channel governed by server and room permissions.
	RoomKind_ROOM_KIND_CHANNEL RoomKind = 1
	// A direct-message conversation between members.
	RoomKind_ROOM_KIND_DM RoomKind = 2
)

// Enum value maps for RoomKind.
var (
	RoomKind_name = map[int32]string{
		0: "ROOM_KIND_UNSPECIFIED",
		1: "ROOM_KIND_CHANNEL",
		2: "ROOM_KIND_DM",
	}
	RoomKind_value = map[string]int32{
		"ROOM_KIND_UNSPECIFIED": 0,
		"ROOM_KIND_CHANNEL":     1,
		"ROOM_KIND_DM":          2,
	}
)

func (x RoomKind) Enum() *RoomKind {
	p := new(RoomKind)
	*p = x
	return p
}

func (x RoomKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RoomKind) Descriptor() protoreflect.EnumDescriptor {
	return file_chatto_api_v1_rooms_proto_enumTypes[0].Descriptor()
}

func (RoomKind) Type() protoreflect.EnumType {
	return &file_chatto_api_v1_rooms_proto_enumTypes[0]
}

func (x RoomKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RoomKind.Descriptor instead.
func (RoomKind) EnumDescriptor() ([]byte, []int) {
	return file_chatto_api_v1_rooms_proto_rawDescGZIP(), []int{0}
}

// Public room metadata returned by room commands.
type Room struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Stable room ID.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Room kind.
	Kind RoomKind `protobuf:"varint,2,opt,name=kind,proto3,enum=chatto.api.v1.RoomKind" json:"kind,omitempty"`
	// Room name. Direct-message rooms may have an empty name because clients
	// derive their display label from participants.
	Name string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	// Optional room description.
	Description string `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	// True when the room is archived and hidden from active room lists.
	Archived bool `protobuf:"varint,5,opt,name=archived,proto3" json:"archived,omitempty"`
	// Room group ID for channel rooms. Empty for direct-message rooms.
	GroupId string `protobuf:"bytes,6,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	// True when a channel grants effective membership to eligible server members.
	Universal bool `protobuf:"varint,7,opt,name=universal,proto3" json:"universal,omitempty"`
	// Minimum number of seconds a non-exempt member must wait between message
	// posts. Channel rooms only; zero means slow mode is disabled.
	SlowModeSeconds uint32 `protobuf:"varint,8,opt,name=slow_mode_seconds,json=slowModeSeconds,proto3" json:"slow_mode_seconds,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Room) Reset() {
	*x = Room{}
	mi := &file_chatto_api_v1_rooms_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Room) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Room) ProtoMessage() {}

func (x *Room) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_api_v1_rooms_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Room.ProtoReflect.Descriptor instead.
func (*Room) Descriptor() ([]byte, []int) {
	return file_chatto_api_v1_rooms_proto_rawDescGZIP(), []int{0}
}

func (x *Room) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Room) GetKind() RoomKind {
	if x != nil {
		return x.Kind
	}
	return RoomKind_ROOM_KIND_UNSPECIFIED
}

func (x *Room) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Room) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Room) GetArchived() bool {
	if x != nil {
		return x.Archived
	}
	return false
}

func (x *Room) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *Room) GetUniversal() bool {
	if x != nil {
		return x.Universal
	}
	return false
}

func (x *Room) GetSlowModeSeconds() uint32 {
	if x != nil {
		return x.SlowModeSeconds
	}
	return 0
}

// Lightweight room reference for cross-resource rows.
type RoomSummary struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Stable room ID.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Room kind.
	Kind RoomKind `protobuf:"varint,2,opt,name=kind,proto3,enum=chatto.api.v1.RoomKind" json:"kind,omitempty"`
	// Room name. Direct-message rooms may have an empty name because clients
	// derive their display label from participants.
	Name          string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoomSummary) Reset() {
	*x = RoomSummary{}
	mi := &file_chatto_api_v1_rooms_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoomSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomSummary) ProtoMessage() {}

func (x *RoomSummary) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_api_v1_rooms_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomSummary.ProtoReflect.Descriptor instead.
func (*RoomSummary) Descriptor() ([]byte, []int) {
	return file_chatto_api_v1_rooms_proto_rawDescGZIP(), []int{1}
}

func (x *RoomSummary) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RoomSummary) GetKind() RoomKind {
	if x != nil {
		return x.Kind
	}
	return RoomKind_ROOM_KIND_UNSPECIFIED
}

func (x *RoomSummary) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// Request to create a channel room.
type CreateRoomRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required. Visible 1–30-code-point Unicode name of the new channel room.
	// The server trims and stores it in NFC form. Control characters and Unicode
	// line or paragraph separators are rejected.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Optional room description.
	Description string `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	// Required. Room group that should contain the new channel.
	GroupId string `protobuf:"bytes,3,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	// Whether the new channel should grant effective membership to eligible
	// server members.
	Universal     bool `protobuf:"varint,4,opt,name=universal,proto3" json:"universal,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRoomRequest) Reset() {
	*x = CreateRoomRequest{}
	mi := &file_chatto_api_v1_rooms_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRoomRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRoomRequest) ProtoMessage() {}

func (x *CreateRoomRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_api_v1_rooms_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRoomRequest.ProtoReflect.Descriptor instead.
func (*CreateRoomRequest) Descriptor() ([]byte, []int) {
	return file_chatto_api_v1_rooms_proto_rawDescGZIP(), []int{2}
}

func (x *CreateRoomRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateRoomRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateRoomRequest) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *CreateRoomRequest) GetUniversal() bool {
	if x != nil {
		return x.Universal
	}
	return false
}

// Result of creating a room.
type CreateRoomResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Created room.
	Room          *Room `protobuf:"bytes,1,opt,name=room,proto3" json:"room,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRoomResponse) Reset() {
	*x = CreateRoomResponse{}
	mi := &file_chatto_api_v1_rooms_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRoomResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRoomResponse) ProtoMessage() {}

func (x *CreateRoomResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_api_v1_rooms_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRoomResponse.ProtoReflect.Descriptor instead.
func (*CreateRoomResponse) Descriptor() ([]byte, []int) {
	return file_chatto_api_v1_rooms_proto_rawDescGZIP(), []int{3}
}

func (x *CreateRoomResponse) GetRoom() *Room {
	if x != nil {
		return x.Room
	}
	return nil
}

// Request to update a room's editable metadata.
type UpdateRoomRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required. Room to update.
	RoomId string `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	// New visible 1–30-code-point Unicode room name, when changing it. The server
	// trims and stores it in NFC form. Control characters and Unicode line or
	// paragraph separators are rejected.
	Name *string `protobuf:"bytes,2,opt,name=name,proto3,oneof" json:"name,omitempty"`
	// New room description, when changing it. Empty clears the description.
	Description *string `protobuf:"bytes,3,opt,name=description,proto3,oneof" json:"description,omitempty"`
	// New universal membership state, when changing it. Direct-message rooms
	// cannot be universal.
	Universal *bool `protobuf:"varint,4,opt,name=universal,proto3,oneof" json:"universal,omitempty"`
	// New per-user posting interval in seconds. Zero disables slow mode. The
	// maximum supported interval is six hours. Direct-message rooms cannot use
	// slow mode.
	SlowModeSeconds *uint32 `protobuf:"varint,5,opt,name=slow_mode_seconds,json=slowModeSeconds,proto3,oneof" json:"slow_mode_seconds,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *UpdateRoomRequest) Reset() {
	*x = UpdateRoomRequest{}
	mi := &file_chatto_api_v1_rooms_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRoomRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRoomRequest) ProtoMessage() {}

func (x *UpdateRoomRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_api_v1_rooms_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRoomRequest.ProtoReflect.Descriptor instead.
func (*UpdateRoomRequest) Descriptor() ([]byte, []int) {
	return file_chatto_api_v1_rooms_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateRoomRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *UpdateRoomRequest) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *UpdateRoomRequest) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *UpdateRoomRequest) GetUniversal() bool {
	if x != nil && x.Universal != nil {
		return *x.Universal
	}
	return false
}

func (x *UpdateRoomRequest) GetSlowModeSeconds() uint32 {
	if x != nil && x.SlowModeSeconds != nil {
		return *x.SlowModeSeconds
	}
	return 0
}

// Result of updating a room.
type UpdateRoomResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Updated room.
	Room          *Room `protobuf:"bytes,1,opt,name=room,proto3" json:"room,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateRoomResponse) Reset() {
	*x = UpdateRoomResponse{}
	mi := &file_chatto_api_v1_rooms_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRoomResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRoomResponse) ProtoMessage() {}

func (x *UpdateRoomResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_api_v1_rooms_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRoomResponse.ProtoReflect.Descriptor instead.
func (*UpdateRoomResponse) Descriptor() ([]byte, []int) {
	return file_chatto_api_v1_rooms_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateRoomResponse) GetRoom() *Room {
	if x != nil {
		return x.Room
	}
	return nil
}

// Request to archive a room.
type ArchiveRoomRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required. Room to archive.
	RoomId        string `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArchiveRoomRequest) Reset() {
	*x = ArchiveRoomRequest{}
	mi := &file_chatto_api_v1_rooms_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArchiveRoomRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArchiveRoomRequest) ProtoMessage() {}

func (x *ArchiveRoomRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_api_v1_rooms_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArchiveRoomRequest.ProtoReflect.Descriptor instead.
func (*ArchiveRoomRequest) Descriptor() ([]byte, []int) {
	return file_chatto_api_v1_rooms_proto_rawDescGZIP(), []int{6}
}

func (x *ArchiveRoomRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

// Result of archiving a room.
type ArchiveRoomResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Archived room.
	Room          *Room `protobuf:"bytes,1,opt,name=room,proto3" json:"room,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArchiveRoomResponse) Reset() {
	*x = ArchiveRoomResponse{}
	mi := &file_chatto_api_v1_rooms_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArchiveRoomResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArchiveRoomResponse) ProtoMessage() {}

func (x *ArchiveRoomResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_api_v1_rooms_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArchiveRoomResponse.ProtoReflect.Descriptor instead.
func (*ArchiveRoomResponse) Descriptor() ([]byte, []int) {
	return file_chatto_api_v1_rooms_proto_rawDescGZIP(), []int{7}
}

func (x *ArchiveRoomResponse) GetRoom() *Room {
	if x != nil {
		return x.Room
	}
	return nil
}

// Request to unarchive a room.
type UnarchiveRoomRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required. Room to unarchive.
	RoomId        string `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnarchiveRoomRequest) Reset() {
	*x = UnarchiveRoomRequest{}
	mi := &file_chatto_api_v1_rooms_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnarchiveRoomRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnarchiveRoomRequest) ProtoMessage() {}

func (x *UnarchiveRoomRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_api_v1_rooms_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnarchiveRoomRequest.ProtoReflect.Descriptor instead.
func (*UnarchiveRoomRequest) Descriptor() ([]byte, []int) {
	return file_chatto_api_v1_rooms_proto_rawDescGZIP(), []int{8}
}

func (x *UnarchiveRoomRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

// Result of unarchiving a room.
type UnarchiveRoomResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unarchived room.
	Room          *Room `protobuf:"bytes,1,opt,name=room,proto3" json:"room,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnarchiveRoomResponse) Reset() {
	*x = UnarchiveRoomResponse{}
	mi := &file_chatto_api_v1_rooms_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnarchiveRoomResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnarchiveRoomResponse) ProtoMessage() {}

func (x *UnarchiveRoomResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_api_v1_rooms_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnarchiveRoomResponse.ProtoReflect.Descriptor instead.
func (*UnarchiveRoomResponse) Descriptor() ([]byte, []int) {
	return file_chatto_api_v1_rooms_proto_rawDescGZIP(), []int{9}
}

func (x *UnarchiveRoomResponse) GetRoom() *Room {
	if x != nil {
		return x.Room
	}
	return nil
}

// Request to join a room as the current user.
type JoinRoomRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required. Room to join.
	RoomId        string `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinRoomRequest) Reset() {
	*x = JoinRoomRequest{}
	mi := &file_chatto_api_v1_rooms_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinRoomRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinRoomRequest) ProtoMessage() {}

func (x *JoinRoomRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_api_v1_rooms_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinRoomRequest.ProtoReflect.Descriptor instead.
func (*JoinRoomRequest) Descriptor() ([]byte, []int) {
	return file_chatto_api_v1_rooms_proto_rawDescGZIP(), []int{10}
}

func (x *JoinRoomRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

// Result of joining a room.
type JoinRoomResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Joined room.
	Room          *Room `protobuf:"bytes,1,opt,name=room,proto3" json:"room,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinRoomResponse) Reset() {
	*x = JoinRoomResponse{}
	mi := &file_chatto_api_v1_rooms_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinRoomResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinRoomResponse) ProtoMessage() {}

func (x *JoinRoomResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_api_v1_rooms_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinRoomResponse.ProtoReflect.Descriptor instead.
func (*JoinRoomResponse) Descriptor() ([]byte, []int) {
	return file_chatto_api_v1_rooms_proto_rawDescGZIP(), []int{11}
}

func (x *JoinRoomResponse) GetRoom() *Room {
	if x != nil {
		return x.Room
	}
	return nil
}

// Request to join all joinable rooms in one room group.
type JoinRoomGroupRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required. Room group whose rooms should be joined.
	GroupId       string `protobuf:"bytes,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinRoomGroupRequest) Reset() {
	*x = JoinRoomGroupRequest{}
	mi := &file_chatto_api_v1_rooms_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinRoomGroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinRoomGroupRequest) ProtoMessage() {}

func (x *JoinRoomGroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_api_v1_rooms_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinRoomGroupRequest.ProtoReflect.Descriptor instead.
func (*JoinRoomGroupRequest) Descriptor() ([]byte, []int) {
	return file_chatto_api_v1_rooms_proto_rawDescGZIP(), []int{12}
}

func (x *JoinRoomGroupRequest) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

// Result of joining all joinable rooms in one room group.
type JoinRoomGroupResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Room IDs that transitioned from not joined to joined.
	JoinedRoomIds []string `protobuf:"bytes,1,rep,name=joined_room_ids,json=joinedRoomIds,proto3" json:"joined_room_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinRoomGroupResponse) Reset() {
	*x = JoinRoomGroupResponse{}
	mi := &file_chatto_api_v1_rooms_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinRoomGroupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinRoomGroupResponse) ProtoMessage() {}

func (x *JoinRoomGroupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_api_v1_rooms_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinRoomGroupResponse.ProtoReflect.Descriptor instead.
func (*JoinRoomGroupResponse) Descriptor() ([]byte, []int) {
	return file_chatto_api_v1_rooms_proto_rawDescGZIP(), []int{13}
}

func (x *JoinRoomGroupResponse) GetJoinedRoomIds() []string {
	if x != nil {
		return x.JoinedRoomIds
	}
	return nil
}

// Request to start or fetch a direct-message room.
type StartDMRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Other participants to include in the direct-message room. The current user
	// is always included by the server. An empty list creates or fetches the
	// caller's self-DM.
	ParticipantIds []string `protobuf:"bytes,1,rep,name=participant_ids,json=participantIds,proto3" json:"participant_ids,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *StartDMRequest) Reset() {
	*x = StartDMRequest{}
	mi := &file_chatto_api_v1_rooms_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartDMRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartDMRequest) ProtoMessage() {}

func (x *StartDMRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_api_v1_rooms_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartDMRequest.ProtoReflect.Descriptor instead.
func (*StartDMRequest) Descriptor() ([]byte, []int) {
	return file_chatto_api_v1_rooms_proto_rawDescGZIP(), []int{14}
}

func (x *StartDMRequest) GetParticipantIds() []string {
	if x != nil {
		return x.ParticipantIds
	}
	return nil
}

// Result of starting or fetching a direct-message room.
type StartDMResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Direct-message room for the participant set.
	Room          *Room `protobuf:"bytes,1,opt,name=room,proto3" json:"room,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartDMResponse) Reset() {
	*x = StartDMResponse{}
	mi := &file_chatto_api_v1_rooms_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartDMResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartDMResponse) ProtoMessage() {}

func (x *StartDMResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_api_v1_rooms_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartDMResponse.ProtoReflect.Descriptor instead.
func (*StartDMResponse) Descriptor() ([]byte, []int) {
	return file_chatto_api_v1_rooms_proto_rawDescGZIP(), []int{15}
}

func (x *StartDMResponse) GetRoom() *Room {
	if x != nil {
		return x.Room
	}
	return nil
}

// Request to leave a room as the current user.
type LeaveRoomRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required. Room to leave.
	RoomId        string `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaveRoomRequest) Reset() {
	*x = LeaveRoomRequest{}
	mi := &file_chatto_api_v1_rooms_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaveRoomRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaveRoomRequest) ProtoMessage() {}

func (x *LeaveRoomRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_api_v1_rooms_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaveRoomRequest.ProtoReflect.Descriptor instead.
func (*LeaveRoomRequest) Descriptor() ([]byte, []int) {
	return file_chatto_api_v1_rooms_proto_rawDescGZIP(), []int{16}
}

func (x *LeaveRoomRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

// Result of leaving a room.
type LeaveRoomResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// True when the current user is no longer an explicit member after the call.
	Left          bool `protobuf:"varint,1,opt,name=left,proto3" json:"left,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaveRoomResponse) Reset() {
	*x = LeaveRoomResponse{}
	mi := &file_chatto_api_v1_rooms_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaveRoomResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaveRoomResponse) ProtoMessage() {}

func (x *LeaveRoomResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_api_v1_rooms_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaveRoomResponse.ProtoReflect.Descriptor instead.
func (*LeaveRoomResponse) Descriptor() ([]byte, []int) {
	return file_chatto_api_v1_rooms_proto_rawDescGZIP(), []int{17}
}

func (x *LeaveRoomResponse) GetLeft() bool {
	if x != nil {
		return x.Left
	}
	return false
}

// Request to add a user to a channel room.
type AddMemberRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required. Channel room to add the user to.
	RoomId string `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	// Required. User to add as an explicit room member.
	UserId        string `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddMemberRequest) Reset() {
	*x = AddMemberRequest{}
	mi := &file_chatto_api_v1_rooms_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddMemberRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddMemberRequest) ProtoMessage() {}

func (x *AddMemberRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_api_v1_rooms_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddMemberRequest.ProtoReflect.Descriptor instead.
func (*AddMemberRequest) Descriptor() ([]byte, []int) {
	return file_chatto_api_v1_rooms_proto_rawDescGZIP(), []int{18}
}

func (x *AddMemberRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *AddMemberRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

// Result of adding a user to a room.
type AddMemberResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Added room member.
	Member        *DirectoryMember `protobuf:"bytes,1,opt,name=member,proto3" json:"member,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddMemberResponse) Reset() {
	*x = AddMemberResponse{}
	mi := &file_chatto_api_v1_rooms_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddMemberResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddMemberResponse) ProtoMessage() {}

func (x *AddMemberResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_api_v1_rooms_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddMemberResponse.ProtoReflect.Descriptor instead.
func (*AddMemberResponse) Descriptor() ([]byte, []int) {
	return file_chatto_api_v1_rooms_proto_rawDescGZIP(), []int{19}
}

func (x *AddMemberResponse) GetMember() *DirectoryMember {
	if x != nil {
		return x.Member
	}
	return nil
}

// Request to remove a user from a channel room.
type RemoveMemberRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required. Channel room to remove the user from.
	RoomId string `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	// Required. User to remove from the room's explicit members.
	UserId        string `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveMemberRequest) Reset() {
	*x = RemoveMemberRequest{}
	mi := &file_chatto_api_v1_rooms_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveMemberRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveMemberRequest) ProtoMessage() {}

func (x *RemoveMemberRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_api_v1_rooms_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveMemberRequest.ProtoReflect.Descriptor instead.
func (*RemoveMemberRequest) Descriptor() ([]byte, []int) {
	return file_chatto_api_v1_rooms_proto_rawDescGZIP(), []int{20}
}

func (x *RemoveMemberRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *RemoveMemberRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

// Result of removing a user from a room.
type RemoveMemberResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// True when an explicit room membership was removed by this call.
	Removed       bool `protobuf:"varint,1,opt,name=removed,proto3" json:"removed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveMemberResponse) Reset() {
	*x = RemoveMemberResponse{}
	mi := &file_chatto_api_v1_rooms_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveMemberResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveMemberResponse) ProtoMessage() {}

func (x *RemoveMemberResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_api_v1_rooms_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveMemberResponse.ProtoReflect.Descriptor instead.
func (*RemoveMemberResponse) Descriptor() ([]byte, []int) {
	return file_chatto_api_v1_rooms_proto_rawDescGZIP(), []int{21}
}

func (x *RemoveMemberResponse) GetRemoved() bool {
	if x != nil {
		return x.Removed
	}
	return false
}

// Request to ban a member from a channel room.
type BanMemberRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required. Channel room to ban the user from.
	RoomId string `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	// Required. User to ban from the room.
	UserId string `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	// Required moderator-entered reason stored for audit.
	Reason string `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	// Optional future time when the ban expires.
	ExpiresAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BanMemberRequest) Reset() {
	*x = BanMemberRequest{}
	mi := &file_chatto_api_v1_rooms_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BanMemberRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BanMemberRequest) ProtoMessage() {}

func (x *BanMemberRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_api_v1_rooms_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BanMemberRequest.ProtoReflect.Descriptor instead.
func (*BanMemberRequest) Descriptor() ([]byte, []int) {
	return file_chatto_api_v1_rooms_proto_rawDescGZIP(), []int{22}
}

func (x *BanMemberRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *BanMemberRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *BanMemberRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *BanMemberRequest) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

// Result of banning a room member.
type BanMemberResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// True when the ban operation completed.
	Banned        bool `protobuf:"varint,1,opt,name=banned,proto3" json:"banned,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BanMemberResponse) Reset() {
	*x = BanMemberResponse{}
	mi := &file_chatto_api_v1_rooms_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BanMemberResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BanMemberResponse) ProtoMessage() {}

func (x *BanMemberResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_api_v1_rooms_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BanMemberResponse.ProtoReflect.Descriptor instead.
func (*BanMemberResponse) Descriptor() ([]byte, []int) {
	return file_chatto_api_v1_rooms_proto_rawDescGZIP(), []int{23}
}

func (x *BanMemberResponse) GetBanned() bool {
	if x != nil {
		return x.Banned
	}
	return false
}

// Request to remove a channel room ban.
type UnbanMemberRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required. Channel room to unban the user from.
	RoomId string `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	// Required. User to unban.
	UserId string `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	// Required moderator-entered reason stored for audit.
	Reason        string `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnbanMemberRequest) Reset() {
	*x = UnbanMemberRequest{}
	mi := &file_chatto_api_v1_rooms_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnbanMemberRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnbanMemberRequest) ProtoMessage() {}

func (x *UnbanMemberRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_api_v1_rooms_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnbanMemberRequest.ProtoReflect.Descriptor instead.
func (*UnbanMemberRequest) Descriptor() ([]byte, []int) {
	return file_chatto_api_v1_rooms_proto_rawDescGZIP(), []int{24}
}

func (x *UnbanMemberRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *UnbanMemberRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UnbanMemberRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

// Result of removing a room ban.
type UnbanMemberResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// True when the unban operation completed.
	Unbanned      bool `protobuf:"varint,1,opt,name=unbanned,proto3" json:"unbanned,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnbanMemberResponse) Reset() {
	*x = UnbanMemberResponse{}
	mi := &file_chatto_api_v1_rooms_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnbanMemberResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnbanMemberResponse) ProtoMessage() {}

func (x *UnbanMemberResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_api_v1_rooms_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnbanMemberResponse.ProtoReflect.Descriptor instead.
func (*UnbanMemberResponse) Descriptor() ([]byte, []int) {
	return file_chatto_api_v1_rooms_proto_rawDescGZIP(), []int{25}
}

func (x *UnbanMemberResponse) GetUnbanned() bool {
	if x != nil {
		return x.Unbanned
	}
	return false
}

// Active channel room ban with optional hydrated room and user references.
type RoomBan struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Stable ban event ID.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Channel room ID.
	RoomId string `protobuf:"bytes,2,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	// Channel room metadata, when the referenced room still exists.
	Room *Room `protobuf:"bytes,3,opt,name=room,proto3" json:"room,omitempty"`
	// Banned user ID.
	UserId string `protobuf:"bytes,4,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	// Banned user profile, when the referenced user still exists.
	User *DirectoryMember `protobuf:"bytes,5,opt,name=user,proto3" json:"user,omitempty"`
	// Moderator user ID that created the ban.
	ModeratorId string `protobuf:"bytes,6,opt,name=moderator_id,json=moderatorId,proto3" json:"moderator_id,omitempty"`
	// Moderator profile, when the referenced user still exists.
	Moderator *DirectoryMember `protobuf:"bytes,7,opt,name=moderator,proto3" json:"moderator,omitempty"`
	// Moderator-entered ban reason.
	Reason string `protobuf:"bytes,8,opt,name=reason,proto3" json:"reason,omitempty"`
	// Time the ban was created.
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// Optional future time when the ban expires.
	ExpiresAt     *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoomBan) Reset() {
	*x = RoomBan{}
	mi := &file_chatto_api_v1_rooms_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoomBan) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomBan) ProtoMessage() {}

func (x *RoomBan) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_api_v1_rooms_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomBan.ProtoReflect.Descriptor instead.
func (*RoomBan) Descriptor() ([]byte, []int) {
	return file_chatto_api_v1_rooms_proto_rawDescGZIP(), []int{26}
}

func (x *RoomBan) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RoomBan) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *RoomBan) GetRoom() *Room {
	if x != nil {
		return x.Room
	}
	return nil
}

func (x *RoomBan) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *RoomBan) GetUser() *DirectoryMember {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *RoomBan) GetModeratorId() string {
	if x != nil {
		return x.ModeratorId
	}
	return ""
}

func (x *RoomBan) GetModerator() *DirectoryMember {
	if x != nil {
		return x.Moderator
	}
	return nil
}

func (x *RoomBan) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *RoomBan) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *RoomBan) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

// Request to list active room bans.
type ListBansRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Optional channel room filter. Empty lists active bans across all rooms.
	RoomId string `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	// Page request. Defaults are applied when absent or limit is zero.
	Page          *PageRequest `protobuf:"bytes,2,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBansRequest) Reset() {
	*x = ListBansRequest{}
	mi := &file_chatto_api_v1_rooms_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBansRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBansRequest) ProtoMessage() {}

func (x *ListBansRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_api_v1_rooms_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBansRequest.ProtoReflect.Descriptor instead.
func (*ListBansRequest) Descriptor() ([]byte, []int) {
	return file_chatto_api_v1_rooms_proto_rawDescGZIP(), []int{27}
}

func (x *ListBansRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *ListBansRequest) GetPage() *PageRequest {
	if x != nil {
		return x.Page
	}
	return nil
}

// Active room bans visible to the current moderator.
type ListBansResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Active bans, newest first.
	Bans []*RoomBan `protobuf:"bytes,1,rep,name=bans,proto3" json:"bans,omitempty"`
	// Page metadata.
	Page          *PageInfo `protobuf:"bytes,2,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBansResponse) Reset() {
	*x = ListBansResponse{}
	mi := &file_chatto_api_v1_rooms_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBansResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBansResponse) ProtoMessage() {}

func (x *ListBansResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_api_v1_rooms_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBansResponse.ProtoReflect.Descriptor instead.
func (*ListBansResponse) Descriptor() ([]byte, []int) {
	return file_chatto_api_v1_rooms_proto_rawDescGZIP(), []int{28}
}

func (x *ListBansResponse) GetBans() []*RoomBan {
	if x != nil {
		return x.Bans
	}
	return nil
}

func (x *ListBansResponse) GetPage() *PageInfo {
	if x != nil {
		return x.Page
	}
	return nil
}

// Request for room-scoped attachment list pages.
type ListRoomAttachmentsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required room ID.
	RoomId string `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	// Thumbnail URL options. Defaults are applied when absent.
	Thumbnail *ImageTransformOptions `protobuf:"bytes,4,opt,name=thumbnail,proto3" json:"thumbnail,omitempty"`
	// Page request. Defaults are applied when absent or limit is zero.
	Page          *PageRequest `protobuf:"bytes,5,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRoomAttachmentsRequest) Reset() {
	*x = ListRoomAttachmentsRequest{}
	mi := &file_chatto_api_v1_rooms_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRoomAttachmentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRoomAttachmentsRequest) ProtoMessage() {}

func (x *ListRoomAttachmentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_api_v1_rooms_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRoomAttachmentsRequest.ProtoReflect.Descriptor instead.
func (*ListRoomAttachmentsRequest) Descriptor() ([]byte, []int) {
	return file_chatto_api_v1_rooms_proto_rawDescGZIP(), []int{29}
}

func (x *ListRoomAttachmentsRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *ListRoomAttachmentsRequest) GetThumbnail() *ImageTransformOptions {
	if x != nil {
		return x.Thumbnail
	}
	return nil
}

func (x *ListRoomAttachmentsRequest) GetPage() *PageRequest {
	if x != nil {
		return x.Page
	}
	return nil
}

// Room-scoped attachment list response.
type ListRoomAttachmentsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Current attachments in newest message order.
	Attachments []*RoomAttachmentListItem `protobuf:"bytes,1,rep,name=attachments,proto3" json:"attachments,omitempty"`
	// Page metadata.
	Page          *PageInfo `protobuf:"bytes,4,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRoomAttachmentsResponse) Reset() {
	*x = ListRoomAttachmentsResponse{}
	mi := &file_chatto_api_v1_rooms_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRoomAttachmentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRoomAttachmentsResponse) ProtoMessage() {}

func (x *ListRoomAttachmentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_api_v1_rooms_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRoomAttachmentsResponse.ProtoReflect.Descriptor instead.
func (*ListRoomAttachmentsResponse) Descriptor() ([]byte, []int) {
	return file_chatto_api_v1_rooms_proto_rawDescGZIP(), []int{30}
}

func (x *ListRoomAttachmentsResponse) GetAttachments() []*RoomAttachmentListItem {
	if x != nil {
		return x.Attachments
	}
	return nil
}

func (x *ListRoomAttachmentsResponse) GetPage() *PageInfo {
	if x != nil {
		return x.Page
	}
	return nil
}

// One current pinned message in a channel room.
type PinnedMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Current renderable message. Retracted messages are omitted from pin lists.
	Message       *Message `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PinnedMessage) Reset() {
	*x = PinnedMessage{}
	mi := &file_chatto_api_v1_rooms_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PinnedMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PinnedMessage) ProtoMessage() {}

func (x *PinnedMessage) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_api_v1_rooms_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PinnedMessage.ProtoReflect.Descriptor instead.
func (*PinnedMessage) Descriptor() ([]byte, []int) {
	return file_chatto_api_v1_rooms_proto_rawDescGZIP(), []int{31}
}

func (x *PinnedMessage) GetMessage() *Message {
	if x != nil {
		return x.Message
	}
	return nil
}

// Request to list a channel room's current pinned messages.
type ListPinnedMessagesRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required channel room ID.
	RoomId string `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	// Page request. Defaults are applied when absent or limit is zero.
	Page          *PageRequest `protobuf:"bytes,2,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPinnedMessagesRequest) Reset() {
	*x = ListPinnedMessagesRequest{}
	mi := &file_chatto_api_v1_rooms_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPinnedMessagesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPinnedMessagesRequest) ProtoMessage() {}

func (x *ListPinnedMessagesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_api_v1_rooms_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPinnedMessagesRequest.ProtoReflect.Descriptor instead.
func (*ListPinnedMessagesRequest) Descriptor() ([]byte, []int) {
	return file_chatto_api_v1_rooms_proto_rawDescGZIP(), []int{32}
}

func (x *ListPinnedMessagesRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *ListPinnedMessagesRequest) GetPage() *PageRequest {
	if x != nil {
		return x.Page
	}
	return nil
}

// Current pinned messages in one channel room.
type ListPinnedMessagesResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Pinned messages in newest-pin-first order.
	PinnedMessages []*PinnedMessage `protobuf:"bytes,1,rep,name=pinned_messages,json=pinnedMessages,proto3" json:"pinned_messages,omitempty"`
	// Page metadata.
	Page *PageInfo `protobuf:"bytes,2,opt,name=page,proto3" json:"page,omitempty"`
	// Opaque marker for the latest pin fact observed for this room. The value
	// remains stable when pins are removed so clients can detect new pins
	// without comparing wall-clock timestamps. Clients must not interpret it.
	LatestPinMarker string `protobuf:"bytes,3,opt,name=latest_pin_marker,json=latestPinMarker,proto3" json:"latest_pin_marker,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ListPinnedMessagesResponse) Reset() {
	*x = ListPinnedMessagesResponse{}
	mi := &file_chatto_api_v1_rooms_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPinnedMessagesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPinnedMessagesResponse) ProtoMessage() {}

func (x *ListPinnedMessagesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_api_v1_rooms_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPinnedMessagesResponse.ProtoReflect.Descriptor instead.
func (*ListPinnedMessagesResponse) Descriptor() ([]byte, []int) {
	return file_chatto_api_v1_rooms_proto_rawDescGZIP(), []int{33}
}

func (x *ListPinnedMessagesResponse) GetPinnedMessages() []*PinnedMessage {
	if x != nil {
		return x.PinnedMessages
	}
	return nil
}

func (x *ListPinnedMessagesResponse) GetPage() *PageInfo {
	if x != nil {
		return x.Page
	}
	return nil
}

func (x *ListPinnedMessagesResponse) GetLatestPinMarker() string {
	if x != nil {
		return x.LatestPinMarker
	}
	return ""
}

// Request to pin a message in a channel room.
type CreatePinnedMessageRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required channel room ID.
	RoomId string `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	// Required canonical message event ID. Thread replies are supported.
	MessageEventId string `protobuf:"bytes,2,opt,name=message_event_id,json=messageEventId,proto3" json:"message_event_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreatePinnedMessageRequest) Reset() {
	*x = CreatePinnedMessageRequest{}
	mi := &file_chatto_api_v1_rooms_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePinnedMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePinnedMessageRequest) ProtoMessage() {}

func (x *CreatePinnedMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_api_v1_rooms_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePinnedMessageRequest.ProtoReflect.Descriptor instead.
func (*CreatePinnedMessageRequest) Descriptor() ([]byte, []int) {
	return file_chatto_api_v1_rooms_proto_rawDescGZIP(), []int{34}
}

func (x *CreatePinnedMessageRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *CreatePinnedMessageRequest) GetMessageEventId() string {
	if x != nil {
		return x.MessageEventId
	}
	return ""
}

// Result of pinning a message.
type CreatePinnedMessageResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Current pinned-message resource. Repeating an existing pin returns it.
	PinnedMessage *PinnedMessage `protobuf:"bytes,1,opt,name=pinned_message,json=pinnedMessage,proto3" json:"pinned_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePinnedMessageResponse) Reset() {
	*x = CreatePinnedMessageResponse{}
	mi := &file_chatto_api_v1_rooms_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePinnedMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePinnedMessageResponse) ProtoMessage() {}

func (x *CreatePinnedMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_api_v1_rooms_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePinnedMessageResponse.ProtoReflect.Descriptor instead.
func (*CreatePinnedMessageResponse) Descriptor() ([]byte, []int) {
	return file_chatto_api_v1_rooms_proto_rawDescGZIP(), []int{35}
}

func (x *CreatePinnedMessageResponse) GetPinnedMessage() *PinnedMessage {
	if x != nil {
		return x.PinnedMessage
	}
	return nil
}

// Request to unpin a message from a channel room.
type DeletePinnedMessageRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required channel room ID.
	RoomId string `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	// Required canonical message event ID.
	MessageEventId string `protobuf:"bytes,2,opt,name=message_event_id,json=messageEventId,proto3" json:"message_event_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DeletePinnedMessageRequest) Reset() {
	*x = DeletePinnedMessageRequest{}
	mi := &file_chatto_api_v1_rooms_proto_msgTypes[36]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeletePinnedMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePinnedMessageRequest) ProtoMessage() {}

func (x *DeletePinnedMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_api_v1_rooms_proto_msgTypes[36]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePinnedMessageRequest.ProtoReflect.Descriptor instead.
func (*DeletePinnedMessageRequest) Descriptor() ([]byte, []int) {
	return file_chatto_api_v1_rooms_proto_rawDescGZIP(), []int{36}
}

func (x *DeletePinnedMessageRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *DeletePinnedMessageRequest) GetMessageEventId() string {
	if x != nil {
		return x.MessageEventId
	}
	return ""
}

// Result of unpinning a message.
type DeletePinnedMessageResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// True when the message is not pinned after this call.
	Deleted       bool `protobuf:"varint,1,opt,name=deleted,proto3" json:"deleted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeletePinnedMessageResponse) Reset() {
	*x = DeletePinnedMessageResponse{}
	mi := &file_chatto_api_v1_rooms_proto_msgTypes[37]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeletePinnedMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePinnedMessageResponse) ProtoMessage() {}

func (x *DeletePinnedMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_api_v1_rooms_proto_msgTypes[37]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePinnedMessageResponse.ProtoReflect.Descriptor instead.
func (*DeletePinnedMessageResponse) Descriptor() ([]byte, []int) {
	return file_chatto_api_v1_rooms_proto_rawDescGZIP(), []int{37}
}

func (x *DeletePinnedMessageResponse) GetDeleted() bool {
	if x != nil {
		return x.Deleted
	}
	return false
}

// Request to refresh the current user's live-only typing indicator.
type UpdateTypingIndicatorRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required. Room where the current user is typing.
	RoomId string `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	// Event ID of the thread root when typing inside a thread.
	ThreadRootEventId string `protobuf:"bytes,2,opt,name=thread_root_event_id,json=threadRootEventId,proto3" json:"thread_root_event_id,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *UpdateTypingIndicatorRequest) Reset() {
	*x = UpdateTypingIndicatorRequest{}
	mi := &file_chatto_api_v1_rooms_proto_msgTypes[38]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTypingIndicatorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTypingIndicatorRequest) ProtoMessage() {}

func (x *UpdateTypingIndicatorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_api_v1_rooms_proto_msgTypes[38]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTypingIndicatorRequest.ProtoReflect.Descriptor instead.
func (*UpdateTypingIndicatorRequest) Descriptor() ([]byte, []int) {
	return file_chatto_api_v1_rooms_proto_rawDescGZIP(), []int{38}
}

func (x *UpdateTypingIndicatorRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *UpdateTypingIndicatorRequest) GetThreadRootEventId() string {
	if x != nil {
		return x.ThreadRootEventId
	}
	return ""
}

// Result of refreshing a typing indicator.
type UpdateTypingIndicatorResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// True when the typing indicator was accepted for publish.
	Updated       bool `protobuf:"varint,1,opt,name=updated,proto3" json:"updated,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTypingIndicatorResponse) Reset() {
	*x = UpdateTypingIndicatorResponse{}
	mi := &file_chatto_api_v1_rooms_proto_msgTypes[39]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTypingIndicatorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTypingIndicatorResponse) ProtoMessage() {}

func (x *UpdateTypingIndicatorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_api_v1_rooms_proto_msgTypes[39]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTypingIndicatorResponse.ProtoReflect.Descriptor instead.
func (*UpdateTypingIndicatorResponse) Descriptor() ([]byte, []int) {
	return file_chatto_api_v1_rooms_proto_rawDescGZIP(), []int{39}
}

func (x *UpdateTypingIndicatorResponse) GetUpdated() bool {
	if x != nil {
		return x.Updated
	}
	return false
}

var File_chatto_api_v1_rooms_proto protoreflect.FileDescriptor

const file_chatto_api_v1_rooms_proto_rawDesc = "" +
	"\n" +
	"\x19chatto/api/v1/rooms.proto\x12\rchatto.api.v1\x1a\x1bbuf/validate/validate.proto\x1a\x1fchatto/api/v1/attachments.proto\x1a\x1achatto/api/v1/common.proto\x1a$chatto/api/v1/member_directory.proto\x1a\x1echatto/api/v1/pagination.proto\x1a\x1echatto/api/v1/read_state.proto\x1a!chatto/api/v1/room_timeline.proto\x1a!chatto/api/v1/message_types.proto\x1a\x19chatto/api/v1/users.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xfa\x01\n" +
	"\x04Room\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12+\n" +
	"\x04kind\x18\x02 \x01(\x0e2\x17.chatto.api.v1.RoomKindR\x04kind\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x1a\n" +
	"\barchived\x18\x05 \x01(\bR\barchived\x12\x19\n" +
	"\bgroup_id\x18\x06 \x01(\tR\agroupId\x12\x1c\n" +
	"\tuniversal\x18\a \x01(\bR\tuniversal\x12*\n" +
	"\x11slow_mode_seconds\x18\b \x01(\rR\x0fslowModeSeconds\"^\n" +
	"\vRoomSummary\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12+\n" +
	"\x04kind\x18\x02 \x01(\x0e2\x17.chatto.api.v1.RoomKindR\x04kind\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\"\xa0\x01\n" +
	"\x11CreateRoomRequest\x12\x1d\n" +
	"\x04name\x18\x01 \x01(\tB\t\xbaH\x06r\x04\x10\x01\x18\x1eR\x04name\x12*\n" +
	"\vdescription\x18\x02 \x01(\tB\b\xbaH\x05r\x03\x18\xf4\x03R\vdescription\x12\"\n" +
	"\bgroup_id\x18\x03 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\agroupId\x12\x1c\n" +
	"\tuniversal\x18\x04 \x01(\bR\tuniversal\"=\n" +
	"\x12CreateRoomResponse\x12'\n" +
	"\x04room\x18\x01 \x01(\v2\x13.chatto.api.v1.RoomR\x04room\"\xa6\x02\n" +
	"\x11UpdateRoomRequest\x12 \n" +
	"\aroom_id\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x06roomId\x12\"\n" +
	"\x04name\x18\x02 \x01(\tB\t\xbaH\x06r\x04\x10\x01\x18\x1eH\x00R\x04name\x88\x01\x01\x12/\n" +
	"\vdescription\x18\x03 \x01(\tB\b\xbaH\x05r\x03\x18\xf4\x03H\x01R\vdescription\x88\x01\x01\x12!\n" +
	"\tuniversal\x18\x04 \x01(\bH\x02R\tuniversal\x88\x01\x01\x12:\n" +
	"\x11slow_mode_seconds\x18\x05 \x01(\rB\t\xbaH\x06*\x04\x18\xe0\xa8\x01H\x03R\x0fslowModeSeconds\x88\x01\x01B\a\n" +
	"\x05_nameB\x0e\n" +
	"\f_descriptionB\f\n" +
	"\n" +
	"_universalB\x14\n" +
	"\x12_slow_mode_seconds\"=\n" +
	"\x12UpdateRoomResponse\x12'\n" +
	"\x04room\x18\x01 \x01(\v2\x13.chatto.api.v1.RoomR\x04room\"6\n" +
	"\x12ArchiveRoomRequest\x12 \n" +
	"\aroom_id\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x06roomId\">\n" +
	"\x13ArchiveRoomResponse\x12'\n" +
	"\x04room\x18\x01 \x01(\v2\x13.chatto.api.v1.RoomR\x04room\"8\n" +
	"\x14UnarchiveRoomRequest\x12 \n" +
	"\aroom_id\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x06roomId\"@\n" +
	"\x15UnarchiveRoomResponse\x12'\n" +
	"\x04room\x18\x01 \x01(\v2\x13.chatto.api.v1.RoomR\x04room\"3\n" +
	"\x0fJoinRoomRequest\x12 \n" +
	"\aroom_id\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x06roomId\";\n" +
	"\x10JoinRoomResponse\x12'\n" +
	"\x04room\x18\x01 \x01(\v2\x13.chatto.api.v1.RoomR\x04room\":\n" +
	"\x14JoinRoomGroupRequest\x12\"\n" +
	"\bgroup_id\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\agroupId\"?\n" +
	"\x15JoinRoomGroupResponse\x12&\n" +
	"\x0fjoined_room_ids\x18\x01 \x03(\tR\rjoinedRoomIds\"I\n" +
	"\x0eStartDMRequest\x127\n" +
	"\x0fparticipant_ids\x18\x01 \x03(\tB\x0e\xbaH\v\x92\x01\b\x10\t\"\x04r\x02\x10\x01R\x0eparticipantIds\":\n" +
	"\x0fStartDMResponse\x12'\n" +
	"\x04room\x18\x01 \x01(\v2\x13.chatto.api.v1.RoomR\x04room\"4\n" +
	"\x10LeaveRoomRequest\x12 \n" +
	"\aroom_id\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x06roomId\"'\n" +
	"\x11LeaveRoomResponse\x12\x12\n" +
	"\x04left\x18\x01 \x01(\bR\x04left\"V\n" +
	"\x10AddMemberRequest\x12 \n" +
	"\aroom_id\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x06roomId\x12 \n" +
	"\auser_id\x18\x02 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x06userId\"K\n" +
	"\x11AddMemberResponse\x126\n" +
	"\x06member\x18\x01 \x01(\v2\x1e.chatto.api.v1.DirectoryMemberR\x06member\"Y\n" +
	"\x13RemoveMemberRequest\x12 \n" +
	"\aroom_id\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x06roomId\x12 \n" +
	"\auser_id\x18\x02 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x06userId\"0\n" +
	"\x14RemoveMemberResponse\x12\x18\n" +
	"\aremoved\x18\x01 \x01(\bR\aremoved\"\xb5\x01\n" +
	"\x10BanMemberRequest\x12 \n" +
	"\aroom_id\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x06roomId\x12 \n" +
	"\auser_id\x18\x02 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x06userId\x12\"\n" +
	"\x06reason\x18\x03 \x01(\tB\n" +
	"\xbaH\ar\x05\x10\x01\x18\xe8\aR\x06reason\x129\n" +
	"\n" +
	"expires_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\"+\n" +
	"\x11BanMemberResponse\x12\x16\n" +
	"\x06banned\x18\x01 \x01(\bR\x06banned\"|\n" +
	"\x12UnbanMemberRequest\x12 \n" +
	"\aroom_id\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x06roomId\x12 \n" +
	"\auser_id\x18\x02 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x06userId\x12\"\n" +
	"\x06reason\x18\x03 \x01(\tB\n" +
	"\xbaH\ar\x05\x10\x01\x18\xe8\aR\x06reason\"1\n" +
	"\x13UnbanMemberResponse\x12\x1a\n" +
	"\bunbanned\x18\x01 \x01(\bR\bunbanned\"\x97\x03\n" +
	"\aRoomBan\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\aroom_id\x18\x02 \x01(\tR\x06roomId\x12'\n" +
	"\x04room\x18\x03 \x01(\v2\x13.chatto.api.v1.RoomR\x04room\x12\x17\n" +
	"\auser_id\x18\x04 \x01(\tR\x06userId\x122\n" +
	"\x04user\x18\x05 \x01(\v2\x1e.chatto.api.v1.DirectoryMemberR\x04user\x12!\n" +
	"\fmoderator_id\x18\x06 \x01(\tR\vmoderatorId\x12<\n" +
	"\tmoderator\x18\a \x01(\v2\x1e.chatto.api.v1.DirectoryMemberR\tmoderator\x12\x16\n" +
	"\x06reason\x18\b \x01(\tR\x06reason\x129\n" +
	"\n" +
	"created_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"expires_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\"Z\n" +
	"\x0fListBansRequest\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\x12.\n" +
	"\x04page\x18\x02 \x01(\v2\x1a.chatto.api.v1.PageRequestR\x04page\"k\n" +
	"\x10ListBansResponse\x12*\n" +
	"\x04bans\x18\x01 \x03(\v2\x16.chatto.api.v1.RoomBanR\x04bans\x12+\n" +
	"\x04page\x18\x02 \x01(\v2\x17.chatto.api.v1.PageInfoR\x04page\"\xcd\x01\n" +
	"\x1aListRoomAttachmentsRequest\x12 \n" +
	"\aroom_id\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x06roomId\x12B\n" +
	"\tthumbnail\x18\x04 \x01(\v2$.chatto.api.v1.ImageTransformOptionsR\tthumbnail\x12.\n" +
	"\x04page\x18\x05 \x01(\v2\x1a.chatto.api.v1.PageRequestR\x04pageJ\x04\b\x02\x10\x03J\x04\b\x03\x10\x04R\x05limitR\x06offset\"\xb6\x01\n" +
	"\x1bListRoomAttachmentsResponse\x12G\n" +
	"\vattachments\x18\x01 \x03(\v2%.chatto.api.v1.RoomAttachmentListItemR\vattachments\x12+\n" +
	"\x04page\x18\x04 \x01(\v2\x17.chatto.api.v1.PageInfoR\x04pageJ\x04\b\x02\x10\x03J\x04\b\x03\x10\x04R\vtotal_countR\bhas_more\"A\n" +
	"\rPinnedMessage\x120\n" +
	"\amessage\x18\x01 \x01(\v2\x16.chatto.api.v1.MessageR\amessage\"m\n" +
	"\x19ListPinnedMessagesRequest\x12 \n" +
	"\aroom_id\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x06roomId\x12.\n" +
	"\x04page\x18\x02 \x01(\v2\x1a.chatto.api.v1.PageRequestR\x04page\"\xbc\x01\n" +
	"\x1aListPinnedMessagesResponse\x12E\n" +
	"\x0fpinned_messages\x18\x01 \x03(\v2\x1c.chatto.api.v1.PinnedMessageR\x0epinnedMessages\x12+\n" +
	"\x04page\x18\x02 \x01(\v2\x17.chatto.api.v1.PageInfoR\x04page\x12*\n" +
	"\x11latest_pin_marker\x18\x03 \x01(\tR\x0flatestPinMarker\"q\n" +
	"\x1aCreatePinnedMessageRequest\x12 \n" +
	"\aroom_id\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x06roomId\x121\n" +
	"\x10message_event_id\x18\x02 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x0emessageEventId\"b\n" +
	"\x1bCreatePinnedMessageResponse\x12C\n" +
	"\x0epinned_message\x18\x01 \x01(\v2\x1c.chatto.api.v1.PinnedMessageR\rpinnedMessage\"q\n" +
	"\x1aDeletePinnedMessageRequest\x12 \n" +
	"\aroom_id\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x06roomId\x121\n" +
	"\x10message_event_id\x18\x02 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x0emessageEventId\"7\n" +
	"\x1bDeletePinnedMessageResponse\x12\x18\n" +
	"\adeleted\x18\x01 \x01(\bR\adeleted\"q\n" +
	"\x1cUpdateTypingIndicatorRequest\x12 \n" +
	"\aroom_id\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x06roomId\x12/\n" +
	"\x14thread_root_event_id\x18\x02 \x01(\tR\x11threadRootEventId\"9\n" +
	"\x1dUpdateTypingIndicatorResponse\x12\x18\n" +
	"\aupdated\x18\x01 \x01(\bR\aupdated*N\n" +
	"\bRoomKind\x12\x19\n" +
	"\x15ROOM_KIND_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11ROOM_KIND_CHANNEL\x10\x01\x12\x10\n" +
	"\fROOM_KIND_DM\x10\x022\xb6\x11\n" +
	"\vRoomService\x12Q\n" +
	"\n" +
	"CreateRoom\x12 .chatto.api.v1.CreateRoomRequest\x1a!.chatto.api.v1.CreateRoomResponse\x12Q\n" +
	"\n" +
	"UpdateRoom\x12 .chatto.api.v1.UpdateRoomRequest\x1a!.chatto.api.v1.UpdateRoomResponse\x12T\n" +
	"\vArchiveRoom\x12!.chatto.api.v1.ArchiveRoomRequest\x1a\".chatto.api.v1.ArchiveRoomResponse\x12Z\n" +
	"\rUnarchiveRoom\x12#.chatto.api.v1.UnarchiveRoomRequest\x1a$.chatto.api.v1.UnarchiveRoomResponse\x12K\n" +
	"\bJoinRoom\x12\x1e.chatto.api.v1.JoinRoomRequest\x1a\x1f.chatto.api.v1.JoinRoomResponse\x12Z\n" +
	"\rJoinRoomGroup\x12#.chatto.api.v1.JoinRoomGroupRequest\x1a$.chatto.api.v1.JoinRoomGroupResponse\x12H\n" +
	"\aStartDM\x12\x1d.chatto.api.v1.StartDMRequest\x1a\x1e.chatto.api.v1.StartDMResponse\x12N\n" +
	"\tLeaveRoom\x12\x1f.chatto.api.v1.LeaveRoomRequest\x1a .chatto.api.v1.LeaveRoomResponse\x12\\\n" +
	"\vListMembers\x12%.chatto.api.v1.ListRoomMembersRequest\x1a&.chatto.api.v1.ListRoomMembersResponse\x12V\n" +
	"\tGetMember\x12#.chatto.api.v1.GetRoomMemberRequest\x1a$.chatto.api.v1.GetRoomMemberResponse\x12h\n" +
	"\x0fBatchGetMembers\x12).chatto.api.v1.BatchGetRoomMembersRequest\x1a*.chatto.api.v1.BatchGetRoomMembersResponse\x12N\n" +
	"\tAddMember\x12\x1f.chatto.api.v1.AddMemberRequest\x1a .chatto.api.v1.AddMemberResponse\x12W\n" +
	"\fRemoveMember\x12\".chatto.api.v1.RemoveMemberRequest\x1a#.chatto.api.v1.RemoveMemberResponse\x12K\n" +
	"\bListBans\x12\x1e.chatto.api.v1.ListBansRequest\x1a\x1f.chatto.api.v1.ListBansResponse\x12l\n" +
	"\x13ListRoomAttachments\x12).chatto.api.v1.ListRoomAttachmentsRequest\x1a*.chatto.api.v1.ListRoomAttachmentsResponse\x12i\n" +
	"\x12ListPinnedMessages\x12(.chatto.api.v1.ListPinnedMessagesRequest\x1a).chatto.api.v1.ListPinnedMessagesResponse\x12l\n" +
	"\x13CreatePinnedMessage\x12).chatto.api.v1.CreatePinnedMessageRequest\x1a*.chatto.api.v1.CreatePinnedMessageResponse\x12l\n" +
	"\x13DeletePinnedMessage\x12).chatto.api.v1.DeletePinnedMessageRequest\x1a*.chatto.api.v1.DeletePinnedMessageResponse\x12r\n" +
	"\x15UpdateTypingIndicator\x12+.chatto.api.v1.UpdateTypingIndicatorRequest\x1a,.chatto.api.v1.UpdateTypingIndicatorResponse\x12Z\n" +
	"\rGetRoomEvents\x12#.chatto.api.v1.GetRoomEventsRequest\x1a$.chatto.api.v1.GetRoomEventsResponse\x12l\n" +
	"\x13GetRoomEventsAround\x12).chatto.api.v1.GetRoomEventsAroundRequest\x1a*.chatto.api.v1.GetRoomEventsAroundResponse\x12]\n" +
	"\x0eMarkRoomAsRead\x12$.chatto.api.v1.MarkRoomAsReadRequest\x1a%.chatto.api.v1.MarkRoomAsReadResponse\x12N\n" +
	"\tBanMember\x12\x1f.chatto.api.v1.BanMemberRequest\x1a .chatto.api.v1.BanMemberResponse\x12T\n" +
	"\vUnbanMember\x12!.chatto.api.v1.UnbanMemberRequest\x1a\".chatto.api.v1.UnbanMemberResponseB\xa6\x01\n" +
	"\x11com.chatto.api.v1B\n" +
	"RoomsProtoP\x01Z/hmans.de/chatto/internal/pb/chatto/api/v1;apiv1\xa2\x02\x03CAX\xaa\x02\rChatto.Api.V1\xca\x02\rChatto\\Api\\V1\xe2\x02\x19Chatto\\Api\\V1\\GPBMetadata\xea\x02\x0fChatto::Api::V1b\x06proto3"

var (
	file_chatto_api_v1_rooms_proto_rawDescOnce sync.Once
	file_chatto_api_v1_rooms_proto_rawDescData []byte
)

func file_chatto_api_v1_rooms_proto_rawDescGZIP() []byte {
	file_chatto_api_v1_rooms_proto_rawDescOnce.Do(func() {
		file_chatto_api_v1_rooms_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_chatto_api_v1_rooms_proto_rawDesc), len(file_chatto_api_v1_rooms_proto_rawDesc)))
	})
	return file_chatto_api_v1_rooms_proto_rawDescData
}

var file_chatto_api_v1_rooms_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_chatto_api_v1_rooms_proto_msgTypes = make([]protoimpl.MessageInfo, 40)
var file_chatto_api_v1_rooms_proto_goTypes = []any{
	(RoomKind)(0),                         // 0: chatto.api.v1.RoomKind
	(*Room)(nil),                          // 1: chatto.api.v1.Room
	(*RoomSummary)(nil),                   // 2: chatto.api.v1.RoomSummary
	(*CreateRoomRequest)(nil),             // 3: chatto.api.v1.CreateRoomRequest
	(*CreateRoomResponse)(nil),            // 4: chatto.api.v1.CreateRoomResponse
	(*UpdateRoomRequest)(nil),             // 5: chatto.api.v1.UpdateRoomRequest
	(*UpdateRoomResponse)(nil),            // 6: chatto.api.v1.UpdateRoomResponse
	(*ArchiveRoomRequest)(nil),            // 7: chatto.api.v1.ArchiveRoomRequest
	(*ArchiveRoomResponse)(nil),           // 8: chatto.api.v1.ArchiveRoomResponse
	(*UnarchiveRoomRequest)(nil),          // 9: chatto.api.v1.UnarchiveRoomRequest
	(*UnarchiveRoomResponse)(nil),         // 10: chatto.api.v1.UnarchiveRoomResponse
	(*JoinRoomRequest)(nil),               // 11: chatto.api.v1.JoinRoomRequest
	(*JoinRoomResponse)(nil),              // 12: chatto.api.v1.JoinRoomResponse
	(*JoinRoomGroupRequest)(nil),          // 13: chatto.api.v1.JoinRoomGroupRequest
	(*JoinRoomGroupResponse)(nil),         // 14: chatto.api.v1.JoinRoomGroupResponse
	(*StartDMRequest)(nil),                // 15: chatto.api.v1.StartDMRequest
	(*StartDMResponse)(nil),               // 16: chatto.api.v1.StartDMResponse
	(*LeaveRoomRequest)(nil),              // 17: chatto.api.v1.LeaveRoomRequest
	(*LeaveRoomResponse)(nil),             // 18: chatto.api.v1.LeaveRoomResponse
	(*AddMemberRequest)(nil),              // 19: chatto.api.v1.AddMemberRequest
	(*AddMemberResponse)(nil),             // 20: chatto.api.v1.AddMemberResponse
	(*RemoveMemberRequest)(nil),           // 21: chatto.api.v1.RemoveMemberRequest
	(*RemoveMemberResponse)(nil),          // 22: chatto.api.v1.RemoveMemberResponse
	(*BanMemberRequest)(nil),              // 23: chatto.api.v1.BanMemberRequest
	(*BanMemberResponse)(nil),             // 24: chatto.api.v1.BanMemberResponse
	(*UnbanMemberRequest)(nil),            // 25: chatto.api.v1.UnbanMemberRequest
	(*UnbanMemberResponse)(nil),           // 26: chatto.api.v1.UnbanMemberResponse
	(*RoomBan)(nil),                       // 27: chatto.api.v1.RoomBan
	(*ListBansRequest)(nil),               // 28: chatto.api.v1.ListBansRequest
	(*ListBansResponse)(nil),              // 29: chatto.api.v1.ListBansResponse
	(*ListRoomAttachmentsRequest)(nil),    // 30: chatto.api.v1.ListRoomAttachmentsRequest
	(*ListRoomAttachmentsResponse)(nil),   // 31: chatto.api.v1.ListRoomAttachmentsResponse
	(*PinnedMessage)(nil),                 // 32: chatto.api.v1.PinnedMessage
	(*ListPinnedMessagesRequest)(nil),     // 33: chatto.api.v1.ListPinnedMessagesRequest
	(*ListPinnedMessagesResponse)(nil),    // 34: chatto.api.v1.ListPinnedMessagesResponse
	(*CreatePinnedMessageRequest)(nil),    // 35: chatto.api.v1.CreatePinnedMessageRequest
	(*CreatePinnedMessageResponse)(nil),   // 36: chatto.api.v1.CreatePinnedMessageResponse
	(*DeletePinnedMessageRequest)(nil),    // 37: chatto.api.v1.DeletePinnedMessageRequest
	(*DeletePinnedMessageResponse)(nil),   // 38: chatto.api.v1.DeletePinnedMessageResponse
	(*UpdateTypingIndicatorRequest)(nil),  // 39: chatto.api.v1.UpdateTypingIndicatorRequest
	(*UpdateTypingIndicatorResponse)(nil), // 40: chatto.api.v1.UpdateTypingIndicatorResponse
	(*DirectoryMember)(nil),               // 41: chatto.api.v1.DirectoryMember
	(*timestamppb.Timestamp)(nil),         // 42: google.protobuf.Timestamp
	(*PageRequest)(nil),                   // 43: chatto.api.v1.PageRequest
	(*PageInfo)(nil),                      // 44: chatto.api.v1.PageInfo
	(*ImageTransformOptions)(nil),         // 45: chatto.api.v1.ImageTransformOptions
	(*RoomAttachmentListItem)(nil),        // 46: chatto.api.v1.RoomAttachmentListItem
	(*Message)(nil),                       // 47: chatto.api.v1.Message
	(*ListRoomMembersRequest)(nil),        // 48: chatto.api.v1.ListRoomMembersRequest
	(*GetRoomMemberRequest)(nil),          // 49: chatto.api.v1.GetRoomMemberRequest
	(*BatchGetRoomMembersRequest)(nil),    // 50: chatto.api.v1.BatchGetRoomMembersRequest
	(*GetRoomEventsRequest)(nil),          // 51: chatto.api.v1.GetRoomEventsRequest
	(*GetRoomEventsAroundRequest)(nil),    // 52: chatto.api.v1.GetRoomEventsAroundRequest
	(*MarkRoomAsReadRequest)(nil),         // 53: chatto.api.v1.MarkRoomAsReadRequest
	(*ListRoomMembersResponse)(nil),       // 54: chatto.api.v1.ListRoomMembersResponse
	(*GetRoomMemberResponse)(nil),         // 55: chatto.api.v1.GetRoomMemberResponse
	(*BatchGetRoomMembersResponse)(nil),   // 56: chatto.api.v1.BatchGetRoomMembersResponse
	(*GetRoomEventsResponse)(nil),         // 57: chatto.api.v1.GetRoomEventsResponse
	(*GetRoomEventsAroundResponse)(nil),   // 58: chatto.api.v1.GetRoomEventsAroundResponse
	(*MarkRoomAsReadResponse)(nil),        // 59: chatto.api.v1.MarkRoomAsReadResponse
}
var file_chatto_api_v1_rooms_proto_depIdxs = []int32{
	0,  // 0: chatto.api.v1.Room.kind:type_name -> chatto.api.v1.RoomKind
	0,  // 1: chatto.api.v1.RoomSummary.kind:type_name -> chatto.api.v1.RoomKind
	1,  // 2: chatto.api.v1.CreateRoomResponse.room:type_name -> chatto.api.v1.Room
	1,  // 3: chatto.api.v1.UpdateRoomResponse.room:type_name -> chatto.api.v1.Room
	1,  // 4: chatto.api.v1.ArchiveRoomResponse.room:type_name -> chatto.api.v1.Room
	1,  // 5: chatto.api.v1.UnarchiveRoomResponse.room:type_name -> chatto.api.v1.Room
	1,  // 6: chatto.api.v1.JoinRoomResponse.room:type_name -> chatto.api.v1.Room
	1,  // 7: chatto.api.v1.StartDMResponse.room:type_name -> chatto.api.v1.Room
	41, // 8: chatto.api.v1.AddMemberResponse.member:type_name -> chatto.api.v1.DirectoryMember
	42, // 9: chatto.api.v1.BanMemberRequest.expires_at:type_name -> google.protobuf.Timestamp
	1,  // 10: chatto.api.v1.RoomBan.room:type_name -> chatto.api.v1.Room
	41, // 11: chatto.api.v1.RoomBan.user:type_name -> chatto.api.v1.DirectoryMember
	41, // 12: chatto.api.v1.RoomBan.moderator:type_name -> chatto.api.v1.DirectoryMember
	42, // 13: chatto.api.v1.RoomBan.created_at:type_name -> google.protobuf.Timestamp
	42, // 14: chatto.api.v1.RoomBan.expires_at:type_name -> google.protobuf.Timestamp
	43, // 15: chatto.api.v1.ListBansRequest.page:type_name -> chatto.api.v1.PageRequest
	27, // 16: chatto.api.v1.ListBansResponse.bans:type_name -> chatto.api.v1.RoomBan
	44, // 17: chatto.api.v1.ListBansResponse.page:type_name -> chatto.api.v1.PageInfo
	45, // 18: chatto.api.v1.ListRoomAttachmentsRequest.thumbnail:type_name -> chatto.api.v1.ImageTransformOptions
	43, // 19: chatto.api.v1.ListRoomAttachmentsRequest.page:type_name -> chatto.api.v1.PageRequest
	46, // 20: chatto.api.v1.ListRoomAttachmentsResponse.attachments:type_name -> chatto.api.v1.RoomAttachmentListItem
	44, // 21: chatto.api.v1.ListRoomAttachmentsResponse.page:type_name -> chatto.api.v1.PageInfo
	47, // 22: chatto.api.v1.PinnedMessage.message:type_name -> chatto.api.v1.Message
	43, // 23: chatto.api.v1.ListPinnedMessagesRequest.page:type_name -> chatto.api.v1.PageRequest
	32, // 24: chatto.api.v1.ListPinnedMessagesResponse.pinned_messages:type_name -> chatto.api.v1.PinnedMessage
	44, // 25: chatto.api.v1.ListPinnedMessagesResponse.page:type_name -> chatto.api.v1.PageInfo
	32, // 26: chatto.api.v1.CreatePinnedMessageResponse.pinned_message:type_name -> chatto.api.v1.PinnedMessage
	3,  // 27: chatto.api.v1.RoomService.CreateRoom:input_type -> chatto.api.v1.CreateRoomRequest
	5,  // 28: chatto.api.v1.RoomService.UpdateRoom:input_type -> chatto.api.v1.UpdateRoomRequest
	7,  // 29: chatto.api.v1.RoomService.ArchiveRoom:input_type -> chatto.api.v1.ArchiveRoomRequest
	9,  // 30: chatto.api.v1.RoomService.UnarchiveRoom:input_type -> chatto.api.v1.UnarchiveRoomRequest
	11, // 31: chatto.api.v1.RoomService.JoinRoom:input_type -> chatto.api.v1.JoinRoomRequest
	13, // 32: chatto.api.v1.RoomService.JoinRoomGroup:input_type -> chatto.api.v1.JoinRoomGroupRequest
	15, // 33: chatto.api.v1.RoomService.StartDM:input_type -> chatto.api.v1.StartDMRequest
	17, // 34: chatto.api.v1.RoomService.LeaveRoom:input_type -> chatto.api.v1.LeaveRoomRequest
	48, // 35: chatto.api.v1.RoomService.ListMembers:input_type -> chatto.api.v1.ListRoomMembersRequest
	49, // 36: chatto.api.v1.RoomService.GetMember:input_type -> chatto.api.v1.GetRoomMemberRequest
	50, // 37: chatto.api.v1.RoomService.BatchGetMembers:input_type -> chatto.api.v1.BatchGetRoomMembersRequest
	19, // 38: chatto.api.v1.RoomService.AddMember:input_type -> chatto.api.v1.AddMemberRequest
	21, // 39: chatto.api.v1.RoomService.RemoveMember:input_type -> chatto.api.v1.RemoveMemberRequest
	28, // 40: chatto.api.v1.RoomService.ListBans:input_type -> chatto.api.v1.ListBansRequest
	30, // 41: chatto.api.v1.RoomService.ListRoomAttachments:input_type -> chatto.api.v1.ListRoomAttachmentsRequest
	33, // 42: chatto.api.v1.RoomService.ListPinnedMessages:input_type -> chatto.api.v1.ListPinnedMessagesRequest
	35, // 43: chatto.api.v1.RoomService.CreatePinnedMessage:input_type -> chatto.api.v1.CreatePinnedMessageRequest
	37, // 44: chatto.api.v1.RoomService.DeletePinnedMessage:input_type -> chatto.api.v1.DeletePinnedMessageRequest
	39, // 45: chatto.api.v1.RoomService.UpdateTypingIndicator:input_type -> chatto.api.v1.UpdateTypingIndicatorRequest
	51, // 46: chatto.api.v1.RoomService.GetRoomEvents:input_type -> chatto.api.v1.GetRoomEventsRequest
	52, // 47: chatto.api.v1.RoomService.GetRoomEventsAround:input_type -> chatto.api.v1.GetRoomEventsAroundRequest
	53, // 48: chatto.api.v1.RoomService.MarkRoomAsRead:input_type -> chatto.api.v1.MarkRoomAsReadRequest
	23, // 49: chatto.api.v1.RoomService.BanMember:input_type -> chatto.api.v1.BanMemberRequest
	25, // 50: chatto.api.v1.RoomService.UnbanMember:input_type -> chatto.api.v1.UnbanMemberRequest
	4,  // 51: chatto.api.v1.RoomService.CreateRoom:output_type -> chatto.api.v1.CreateRoomResponse
	6,  // 52: chatto.api.v1.RoomService.UpdateRoom:output_type -> chatto.api.v1.UpdateRoomResponse
	8,  // 53: chatto.api.v1.RoomService.ArchiveRoom:output_type -> chatto.api.v1.ArchiveRoomResponse
	10, // 54: chatto.api.v1.RoomService.UnarchiveRoom:output_type -> chatto.api.v1.UnarchiveRoomResponse
	12, // 55: chatto.api.v1.RoomService.JoinRoom:output_type -> chatto.api.v1.JoinRoomResponse
	14, // 56: chatto.api.v1.RoomService.JoinRoomGroup:output_type -> chatto.api.v1.JoinRoomGroupResponse
	16, // 57: chatto.api.v1.RoomService.StartDM:output_type -> chatto.api.v1.StartDMResponse
	18, // 58: chatto.api.v1.RoomService.LeaveRoom:output_type -> chatto.api.v1.LeaveRoomResponse
	54, // 59: chatto.api.v1.RoomService.ListMembers:output_type -> chatto.api.v1.ListRoomMembersResponse
	55, // 60: chatto.api.v1.RoomService.GetMember:output_type -> chatto.api.v1.GetRoomMemberResponse
	56, // 61: chatto.api.v1.RoomService.BatchGetMembers:output_type -> chatto.api.v1.BatchGetRoomMembersResponse
	20, // 62: chatto.api.v1.RoomService.AddMember:output_type -> chatto.api.v1.AddMemberResponse
	22, // 63: chatto.api.v1.RoomService.RemoveMember:output_type -> chatto.api.v1.RemoveMemberResponse
	29, // 64: chatto.api.v1.RoomService.ListBans:output_type -> chatto.api.v1.ListBansResponse
	31, // 65: chatto.api.v1.RoomService.ListRoomAttachments:output_type -> chatto.api.v1.ListRoomAttachmentsResponse
	34, // 66: chatto.api.v1.RoomService.ListPinnedMessages:output_type -> chatto.api.v1.ListPinnedMessagesResponse
	36, // 67: chatto.api.v1.RoomService.CreatePinnedMessage:output_type -> chatto.api.v1.CreatePinnedMessageResponse
	38, // 68: chatto.api.v1.RoomService.DeletePinnedMessage:output_type -> chatto.api.v1.DeletePinnedMessageResponse
	40, // 69: chatto.api.v1.RoomService.UpdateTypingIndicator:output_type -> chatto.api.v1.UpdateTypingIndicatorResponse
	57, // 70: chatto.api.v1.RoomService.GetRoomEvents:output_type -> chatto.api.v1.GetRoomEventsResponse
	58, // 71: chatto.api.v1.RoomService.GetRoomEventsAround:output_type -> chatto.api.v1.GetRoomEventsAroundResponse
	59, // 72: chatto.api.v1.RoomService.MarkRoomAsRead:output_type -> chatto.api.v1.MarkRoomAsReadResponse
	24, // 73: chatto.api.v1.RoomService.BanMember:output_type -> chatto.api.v1.BanMemberResponse
	26, // 74: chatto.api.v1.RoomService.UnbanMember:output_type -> chatto.api.v1.UnbanMemberResponse
	51, // [51:75] is the sub-list for method output_type
	27, // [27:51] is the sub-list for method input_type
	27, // [27:27] is the sub-list for extension type_name
	27, // [27:27] is the sub-list for extension extendee
	0,  // [0:27] is the sub-list for field type_name
}

func init() { file_chatto_api_v1_rooms_proto_init() }
func file_chatto_api_v1_rooms_proto_init() {
	if File_chatto_api_v1_rooms_proto != nil {
		return
	}
	file_chatto_api_v1_attachments_proto_init()
	file_chatto_api_v1_common_proto_init()
	file_chatto_api_v1_member_directory_proto_init()
	file_chatto_api_v1_pagination_proto_init()
	file_chatto_api_v1_read_state_proto_init()
	file_chatto_api_v1_room_timeline_proto_init()
	file_chatto_api_v1_message_types_proto_init()
	file_chatto_api_v1_users_proto_init()
	file_chatto_api_v1_rooms_proto_msgTypes[4].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_chatto_api_v1_rooms_proto_rawDesc), len(file_chatto_api_v1_rooms_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   40,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_chatto_api_v1_rooms_proto_goTypes,
		DependencyIndexes: file_chatto_api_v1_rooms_proto_depIdxs,
		EnumInfos:         file_chatto_api_v1_rooms_proto_enumTypes,
		MessageInfos:      file_chatto_api_v1_rooms_proto_msgTypes,
	}.Build()
	File_chatto_api_v1_rooms_proto = out.File
	file_chatto_api_v1_rooms_proto_goTypes = nil
	file_chatto_api_v1_rooms_proto_depIdxs = nil
}
